### ISSUE TITLE
Make MetaPoco.cs a Nuget Source Code Transformation

### ISSUE THREAD

**Issue by mwrock** [CollaboratingPlatypus/PetaPoco#102]
First, great project! I just added this to my project replacing EF4 code first and I now have .Net 3.5 compatibility with little effort.

Currently, if I consume via Nuget, PetaPoco.cs is added to my project in a "Model" folder and under the PetaPoco namespace. This namespace could potentially conflict with other projects in the same app that also use PetaPoco. I think that renaming Patapoco.cs to PetaPoco.pp and changing the namespace declaration to `namespace $rootnamespace$.Models` would make the Nuget more portable.

Less importantly, I think Model might not be the best directory to place the class. It is very MVC specific and even at that assumes a very simple Model. I'd prefer something more generic and specific to a common DAL like "Data."

**Comment by pleb** [comment]
There's not a compiled version, which should ease the pain. The main problem I see is that everyone will want the file deploy versions in a different folder. Can anybody think of the way to make this configurable?

**Comment by pleb** [comment]
There's complied version of PP now. Given the aforementioned, and that fact it would be hard to allow the selection of different locations when saving the PP single file, I'm going to close this issue.
