### ISSUE TITLE
There is already an open DataReader associated with this Command

### ISSUE THREAD

**Issue by joeriks** [CollaboratingPlatypus/PetaPoco#103]
Does anyone else get this? I get it when there's quite a lot of traffic on a site which is (only) using PetaPoco as Orm. I tried adding MARS in the connection string, but that does not feel as the right way of solving possibly not closed connections / readers. No multiple threads. And only about 20 users on the site at the same time. Heavy db usage by the site functions though.

**Comment by pleb** [comment]
@Edddy thanks for answering this
