### ISSUE TITLE
Allow overriding EscapeTableName/EscapeSqlIdentifier

### ISSUE THREAD

**Issue by pruiz** [CollaboratingPlatypus/PetaPoco#110]
Changing EscapeTableName/EscapeSqlIdentifier methods to be overrideable, or adding Escaping methods to IMapper would be a great help when working with mixed case identifier on some databases like postgres.

Greets
Pablo

**Comment by pleb** [comment]
Hi @pruiz, sorry it's been so long. This has been addressed and will be in the next release
