### ISSUE TITLE
No deafult constructor error reporting

### ISSUE THREAD

**Issue by nyxiscoo1** [CollaboratingPlatypus/PetaPoco#115]
PetaPoco looks for type's default constructor, but when there is no appropreate one it passes null to il.Emit and last one throws ArgumentNullException with obscure message that parameter 'con' should not be null.

It would be great if PetaPoco will ceck type's default constructor for null and throw  exception with more helpful message.
You need to change GetFactory:
```
il.Emit(OpCodes.Newobj, type.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[0], null));
```
to
```
var ctor = type.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[0], null);
if (ctor == null)
    throw new ApplicationException("Type [" + type.FullName + "] should have default public or non-public constructor");

il.Emit(OpCodes.Newobj, ctor);
```

**Comment by pleb** [comment]
thanks @nyxiscoo1 for the suggestion and sample code. This will be in the next release of PP. Version > 5.1.62

**Comment by guideX** [comment]
Thanks!
