### ISSUE TITLE
Conditional Compilation Bug - v4.x

### ISSUE THREAD

**Issue by TheAjItator** [CollaboratingPlatypus/PetaPoco#118]
The preprocessor directive for dynamic support in 4.x, and earlier, isn't working correctly.

The code has:
```C#
#if !PETAPOCO_NO_DYNAMIC
```
But this isn't processed as you would think.

A fix would be to use:
```C#
#if (!PETAPOCO_NO_DYNAMIC)
```

You can see the issue if you debug into the file without setting PETAPOCO_NO_DYNAMIC and see it is acting as if it was set.

**Comment by pleb** [comment]
Closing this as there's no more preprocessor directives being used.
