### ISSUE TITLE
v5: Db.Update() fails with anonymous type

### ISSUE THREAD

**Issue by fdcastel** [CollaboratingPlatypus/PetaPoco#119]
This used to work in v4

    Db.Update("MyTable", "MyPk", new { Col1 = valC1, Col2 = valC2 }, valPK);

But in v5 it is failing here (@Repository.cs)

```c#
    // Find the property info for the primary key
    PropertyInfo pkpi=null;
    if (primaryKeyName != null)
    {
-->      pkpi = pd.Columns[primaryKeyName].PropertyInfo;
    }
```

At this point pd.Columns doesn't have a "MyPk" entry.

**Workaround**

    Db.Update("MyTable", "MyPk", new { MyPK = 0, Col1 = valC1, Col2 = valC2 }, valPK);

or 

    Db.Update("MyTable", "MyPk", new { MyPK = valPK, Col1 = valC1, Col2 = valC2 });

**Comment by pleb** [comment]
We'll track this with #191.

Thanks for reporting it.
