### ISSUE TITLE
Sql.Append not appending

### ISSUE THREAD

**Issue by yaegerbomb** [CollaboratingPlatypus/PetaPoco#123]
I have the following code:

                sql.Append("UPDATE [Resource] SET ")
                    .Append("[ResourceName] = @0", resource.ResourceName)
                    .Append(",[ResourceDescription] = @0", resource.ResourceDescription)
                    .Append(",[ResourceContent] = @0", resource.ResourceContent);

                if (resource.ResourceData != null)
                {
                    sql.Append(",[ResourceData] = @0", resource.ResourceData);
                }

                if (resource.ResourceGUID != null)
                {
                    sql.Append(",[ResourceGUID] = @0", resource.ResourceGUID);
                }

                if (resource.LaunchPath != null) 
                {
                    sql.Append(",[LaunchPath] = @0", resource.LaunchPath);
                }

                sql.Append(",[ResourceType] = @0", (int)resource.ResourceType)
                    .Append(",[ContentType] = @0", resource.ContentType)
                    .Append(",[SchoolID] = @0", resource.SchoolID)
                    .Append(",[DistrictID] = @0", resource.DistrictID)
                    .Append(",[IsActive] = @0", resource.IsActive)
                    .Append(",[UpdatedBy] = @0", resource.UpdatedBy)
                    .Append(",[UpdatedDate] = @0", resource.UpdatedDate)
                    .Append(",[Extension] = @0", resource.Extension);
                sql.Append(" WHERE ResourceID=@0", resource.ResourceID);
            }

The first four lines work. They append as they should. However when we get down to the sql.Append(", [ResourceType]....") the append fails to do anything. This caused 1000 lines of data to get Nerfed. Any reason why this is happening? Cannot seem to find anything on the issue.

**Comment by pleb** [comment]
Can't reproduce.

```
        [Fact]
        [Description("Investigation of report bug #123")]
        public void Append_GivenMultipleAppends_IsValid()
        {
            var sql = new Sql();

            var resource = new
            {
                ResourceName = "p1",
                ResourceDescription = "p2",
                ResourceContent = "p3",
                ResourceData = "p4",
                ResourceGUID = Guid.Parse("C32B630F-FCFE-49FF-A27C-2E4105D4003E"),
                LaunchPath = "p5",
                ResourceType = OrderStatus.Deleted,
                ContentType = "p5",
                SchoolID = "p5",
                DistrictID = "p5",
                UpdatedBy = 87,
                UpdatedDate = new DateTime(2000, 1, 1, 1, 1, 1, DateTimeKind.Utc),
                IsActive = true,
                Extension = "p9",
                ResourceID = 99,
            };

            sql.Append("UPDATE [Resource] SET ")
                .Append("[ResourceName] = @0", resource.ResourceName)
                .Append(",[ResourceDescription] = @0", resource.ResourceDescription)
                .Append(",[ResourceContent] = @0", resource.ResourceContent);

            sql.Append(",[ResourceData] = @0", resource.ResourceData);

            sql.Append(",[ResourceGUID] = @0", resource.ResourceGUID);

            sql.Append(",[LaunchPath] = @0", resource.LaunchPath);

            sql.Append(",[ResourceType] = @0", (int) resource.ResourceType)
                .Append(",[ContentType] = @0", resource.ContentType)
                .Append(",[SchoolID] = @0", resource.SchoolID)
                .Append(",[DistrictID] = @0", resource.DistrictID)
                .Append(",[IsActive] = @0", resource.IsActive)
                .Append(",[UpdatedBy] = @0", resource.UpdatedBy)
                .Append(",[UpdatedDate] = @0", resource.UpdatedDate)
                .Append(",[Extension] = @0", resource.Extension);
            sql.Append(" WHERE ResourceID=@0", resource.ResourceID);

            sql.SQL.Replace("\n", "").Replace("\r", "").ShouldBe(@"UPDATE [Resource] SET [ResourceName] = @0,[ResourceDescription] = @1,[ResourceContent] = @2,[ResourceData] = @3,[ResourceGUID] = @4,[LaunchPath] = @5,[ResourceType] = @6,[ContentType] = @7,[SchoolID] = @8,[DistrictID] = @9,[IsActive] = @10,[UpdatedBy] = @11,[UpdatedDate] = @12,[Extension] = @13 WHERE ResourceID=@14");
        }```

**Comment by pynej** [comment]
This is likely due to the issue noted in #106
