### ISSUE TITLE
Conversion from Enum to numeric sql parameter fails

### ISSUE THREAD

**Issue by JCKodel** [CollaboratingPlatypus/PetaPoco#126]
In Database.cs, method AddParam(cmd, value, pi), there is an implicit cast to int from an Enum:

if (t.IsEnum)		// PostgreSQL .NET driver wont cast enum to int
{
	p.Value = (int)value;
}

This fails when the Enum is based on other integral type but int: (i.e. public enum Foo : byte), with a tinyint column on database.

To correct this, change the above to:

	p.Value = Convert.ChangeType(value, ((Enum)value).GetTypeCode());

This will ensure that p.Value gets the correct typed integral value of the enum.

**Comment by pleb** [comment]
I'm sorry that your issue has been left for so long. In an effort to reboot PetaPoco your issue has been closed. If you think this is still a problem. Please feel free to open and another issue. Please pass the word on that PetaPoco is back. We're looking for people #204.

**Comment by pleb** [comment]
Has been fixed
