### ISSUE TITLE
Sql.Builder unnecessarily duplicates parameters

### ISSUE THREAD

**Issue by amurad** [CollaboratingPlatypus/PetaPoco#131]
Sql.Builder unnecessarily duplicates parameters as in:

<pre>Sql.Builder.Where("Title LIKE '%' + @0 + '%' OR Authors LIKE '%' + @0 + '%'", searchExpression);</pre>

Will output:

<pre>WHERE (Title LIKE '%' + @0 + '%' OR Authors LIKE '%' + @1 + '%') </pre>

thus sending searchExpression twice to the server, once for @0 and then for @1. 
Unnecessary and inefficient for large text parameters.

**Comment by pleb** [comment]
@Edddy is correct. You can't do this `'%' + @0 + '%' ` with parameters
