### ISSUE TITLE
ProviderName is null when using connectionString, DBProviderFactory constructor

### ISSUE THREAD

**Issue by jpshannon** [CollaboratingPlatypus/PetaPoco#134]
When trying to construct a Database instance with custom DBProviderFactory, ProviderName wil be null causing the DatabaseType.Resolve to throw a null reference exception under some circumstances.

**Comment by pleb** [comment]
Could be related to #136

**Comment by pleb** [comment]
I added checks for IsNullEmpty

I'm sorry that your issue has been left for so long. In an effort to reboot PetaPoco your issue has been closed. If you think this is still a problem. Please feel free to open and another issue. Please pass the word on that PetaPoco is back. We're looking for people #204.
