### ISSUE TITLE
Creating PetaPoco.Database with SqlConnection

### ISSUE THREAD

**Issue by rickelprior** [CollaboratingPlatypus/PetaPoco#136]
I tried to use PetaPoco this way :

            using (var connection = new SqlConnection(MyConnectionString))
            {
                connection.Open();
                IEnumerable<Person> personList = (new PetaPoco.Database(connection)).Fetch<Person>(MySqlSelect);
                return persons;
            }

And I get a System.NullReferenceException in PetaPoco.Resolve method (because ProviderName is null).

But it works if in PetaPoco.Resolve method you replace this line :

            if (TypeName.StartsWith("System.Data.SqlClient."))

by this one :

            if (TypeName.StartsWith("SqlConnection"))

because TypeName is a IDBConnection.Name and not a IDBConnection.FullName.

**Comment by pleb** [comment]
I'm sorry that your issue has been left for so long. In an effort to reboot PetaPoco your issue has been closed. If you think this is still a problem. Please feel free to open and another issue. Please pass the word on that PetaPoco is back. We're looking for people #204.
