### ISSUE TITLE
Problem Resolving database type when passing in SqlConnection.

### ISSUE THREAD

**Issue by johanlbotha** [CollaboratingPlatypus/PetaPoco#139]
I am getting an object null error when passing in the Connection object. The line causing the problem appears to be:
    // Resolve the DB Type
    string DBTypeName = (_factory == null ? _sharedConnection.GetType() : _factory.GetType()).Name;
I changed it to:
    // Resolve the DB Type
    string DBTypeName = (_factory == null ? _sharedConnection.GetType() : _factory.GetType()).FullName;

The reason for that was this line:
    if (TypeName.StartsWith("System.Data.SqlClient.")) 
But using name gives just SqlConnection.

**Comment by pleb** [comment]
Dup of #136
