### ISSUE TITLE
generate all tables in db when use with mysql

### ISSUE THREAD

**Issue by sdhjl2000** [CollaboratingPlatypus/PetaPoco#140]
when use t4 template with mysql,it will generate all the table in database,correct  TABLE_SQL  should be:
			SELECT * 
			FROM information_schema.tables 
			WHERE (table_type='BASE TABLE' OR table_type='VIEW') and  TABLE_SCHEMA=database();

**Comment by pleb** [comment]
Fixed. Will be in version > 5.1.62
