### ISSUE TITLE
Returning WRONG POCO / Empty .cs

### ISSUE THREAD

**Issue by biju-ps** [CollaboratingPlatypus/PetaPoco#143]
Hi,
I am using petapoco with MySQL 5.1 
I have 3 Databases in this application . The Poco for   two database is generating without anyproblem. 
For a database its Creating wrong POCO . Its at times generating a HUGE poco incliding other tables in the other Database too . Some times its not generating POCO at all .

Any idea

**Comment by pleb** [comment]
I'm sorry that your issue has been left for so long. In an effort to reboot PetaPoco your issue has been closed. If you think this is still a problem. Please feel free to open and another issue. Please pass the word on that PetaPoco is back. We're looking for people #204.
