### ISSUE TITLE
Table with two columns in PK fails T4 scripts

### ISSUE THREAD

**Issue by Finzzownt** [CollaboratingPlatypus/PetaPoco#144]
A table with (only) two columns, both part of a primary key fail generation of classes via T4 because Column.PK generates an exception, since two columns are IsPK. Emerged when generating against MySQL 5.
    public Column PK
    {
        get
        {
            return this.Columns.SingleOrDefault(x=>x.IsPK);
        }
    }

**Comment by pleb** [comment]
I'm sorry that your issue has been left for so long. In an effort to reboot PetaPoco your issue has been closed. If you think this is still a problem. Please feel free to open and another issue. Please pass the word on that PetaPoco is back. We're looking for people #204.
