### ISSUE TITLE
SqlConnection constructor issue

### ISSUE THREAD

**Issue by yetanotherchris** [CollaboratingPlatypus/PetaPoco#148]
There's a small bug on line 204, when you pass in a SqlConnection:

     string dbtype = (_factory == null ? _sharedConnection.GetType() : _factory.GetType()).Name

should read

    string dbtype = (_factory == null ? _sharedConnection.GetType() : _factory.GetType()).FullName;

The switch statement following it fails with just the Name property.

(Sorry I'm too lazy to clone + provide a patch)

**Comment by pleb** [comment]
Can't reproduce. 

Please issue a PR with failing integration test to show bug.
