### ISSUE TITLE
Documentation: Add explicit link to IMapper as alternative to attribute in POCO

### ISSUE THREAD

**Issue by OnesimusUnbound** [CollaboratingPlatypus/PetaPoco#150]
I was reading the [documention](http://www.toptensoftware.com/petapoco/), under `Hey! Wait a minute... they're not POCO objects!` there's no mention of IMapper. Hopefully, the documentation can be updated with link to [PetaPoco - Custom mapping with the Mapper interface](http://www.toptensoftware.com/Articles/92/PetaPoco-Custom-mapping-with-the-Mapper-interface).

Thanks :)

**Comment by pleb** [comment]
I hoping to rewrite the documentation. We're looking for people to help #204
