### ISSUE TITLE
Allow Nullable types for SQL Server

### ISSUE THREAD

**Issue by kpconnell** [CollaboratingPlatypus/PetaPoco#153]
I understand a custom mapper could be used but out of the box support for nullable CLR types, e.g. Double? Int? etc would be great.  They currently cause a casting exception.

**Comment by herebebeasties** [comment]
I'm behind a firewall that won't let me submit a proper pull request, but you need to change it like so:

    - converter = delegate(object src) { return Convert.ChangeType(src, dstType, null); };
    + var underlyingType = Nullable.GetUnderlyingType(dstType) ?? dstType;
    + converter = src => Convert.ChangeType(src, underlyingType, null);

This is currently failing for things like coercing a `float` column into a `double?` data type.

**Comment by pleb** [comment]
Closing as there's integration tests for nullable types now, and I don't think this is an issue anymore. Please reopen if you believe I'm wrong.
