### ISSUE TITLE
`pwd` command does not exist on Windows

### ISSUE THREAD

**Issue by kohenkatz** [CollaboratingPlatypus/PetaPoco#155]
The PostBuild.bat file which, in v5, creates the single-file version of PetaPoco, calls `pwd` on its second line.

`pwd` is a linux command to get the current path, not a Windows command.  The equivalent Windows command is `echo %cd%`.

**Comment by pleb** [comment]
I nuked the file. The new commands don't have `pwd`.

**Comment by tfischinger-tgm** [comment]
Thanks man!

**Comment by lagupa** [comment]
just use 
echo %cd%
