### ISSUE TITLE
Does petapoco support Oracle's stored procedure? 

### ISSUE THREAD

**Issue by mankind80** [CollaboratingPlatypus/PetaPoco#158]
Hi, I would like to know does petapoco can execute a stored procedure on Oracle DB? 

 Below is the sample sp written on Oracle DB

CREATE OR REPLACE PROCEDURE USER.GET_DATA(p_recordset OUT SYS_REFCURSOR)
IS
BEGIN

  OPEN p_recordset FOR SELECT DATA FROM TABLE;

END;

Do anybody have any experience how to write .Net code on how to execute sp by using petapoco.

Sample code written but failed to work.

 using (PetaPoco.Database db = new PetaPoco.Database(OracleDataConnection.GetConnectionString(), "Oracle.DataAccess.Client"))
            { 
                var cur = new OracleParameter("p_recordset", OracleDbType.RefCursor, ParameterDirection.Output);
                var a = db.Query<DataList>("exec USER.GET_DATA @@p_recordset OUTPUT", new { p_recordset = cur });
            };

Thanks in advance.

**Comment by pleb** [comment]
I would be happy to review, and if the review passes, accept a PR for this

**Comment by MB34** [comment]
cjpit, would love to see your solution. I have a LOT of functions that return ref cursors and if I don't find a solution, I have to rewrite all of them to pipeline the data.

**Comment by cjpit** [comment]
We transitioned to npoco, but I think this is what you are looking for. - These need to be set up as new interfaces for IDatabase

`
public IDbCommand CreateRefCursorCommand(IDbConnection connection, string sql, params object[] args)
        {
            // Perform parameter prefix replacements
            if (_paramPrefix != "@")
                sql = ParameterHelper.rxParamsPrefix.Replace(sql, m => _paramPrefix + m.Value.Substring(1));
            sql = sql.Replace("@@", "@");		   // <- double @@ escapes a single @

            
            // Create the command and add parameters
            IDbCommand cmd = connection.CreateCommand();
            cmd.Connection = connection;
            cmd.CommandText = sql;
            cmd.Transaction = _transaction;
            cmd.CommandType = CommandType.StoredProcedure;



            //Now we need to add the oracle specific parameter for the ref cursor return.
            // create parameter object for the cursor
            OracleParameter p_refcursor = new OracleParameter();

            p_refcursor.ParameterName = "ReturnValue";
            // this is vital to set when using ref cursors
            p_refcursor.OracleDbType = OracleDbType.RefCursor;

            // this is a function return value so we must indicate that fact
            p_refcursor.Direction = ParameterDirection.ReturnValue;
            //p_refcursor.Value = DBNull.Value;

            // add the parameter to the collection

            //Insert into args.
            List<object> newparms = args.ToList();
            newparms.Insert(0, p_refcursor);
            args = newparms.ToArray();


            foreach (var item in args)
            {
                AddParameter(cmd, item);
            }


            // Notify the DB type
            _dbType.PreExecute(cmd,false);

            // Call logging
            if (!String.IsNullOrEmpty(sql))
                DoPreExecute(cmd);

            return cmd;
        }

        public IEnumerable<T> RefCursorQuery<T>(string sql, params object[] args)
        {
            return RefCursorQuery<T>(default(T), sql, args);
        }


        public IEnumerable<T> RefCursorQuery<T>(T instance,string sql, params object[] args)
        {
            
            try
            {
                OpenSharedConnectionInternal();

                using (var cmd = CreateRefCursorCommand(_sharedConnection, sql, args))
                {
                    IDataReader r;
                    var pd = PocoDataFactory.ForType(typeof(T));
                    try
                    {
                        int result = cmd.ExecuteNonQuery();
                        r = ((OracleRefCursor)((IDataParameter)(cmd.Parameters[0])).Value).GetDataReader();
                        OnExecutedCommand(cmd);
                    }
                    catch (Exception x)
                    {
                        OnException(x);
                        throw;
                    }
                    var factory = pd.MappingFactory.GetFactory(cmd.CommandText, _sharedConnection.ConnectionString, 0, r.FieldCount, r, instance) as Func<IDataReader, T, T>;
                    using (r)
                    {
                        while (true)
                        {
                            T poco;
                            try
                            {
                                if (!r.Read())
                                    yield break;
                                poco = factory(r,instance);
                            }
                            catch (Exception x)
                            {
                                OnException(x);
                                    throw;
                            }

                            yield return poco;
                        }
                    }
                }
            }
            finally
            {
                CloseSharedConnectionInternal();
            }
        }

        public int ExecuteSP(string sql, params object[] args)
        {
            try
            {
                OpenSharedConnectionInternal();
                using (var cmd = CreateSPCommand(_sharedConnection, sql, args))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    var retv = cmd.ExecuteNonQuery();
                    OnExecutedCommand(cmd);
                    return retv;
                }

            }
            catch (Exception x)
            {
                OnException(x);
                throw;
                
            }
            finally
            {
                CloseSharedConnectionInternal();
            }
        }

        /// <summary>
        /// Executes a non-query command
        /// </summary>
        //// <param name="sql">An SQL builder object representing the query and it's arguments</param>
        /// <returns>The number of rows affected</returns>
        public int ExecuteSP(Sql sql)
            {
            return Execute(sql.SQL, sql.Arguments);
        }

        public IDbCommand CreateSPCommand(IDbConnection connection, string sql, params object[] args)
        {

            // Create the command and add parameters
            IDbCommand cmd = connection.CreateCommand();
            cmd.Connection = connection;
            cmd.CommandText = sql;
            cmd.Transaction = _transaction;
            foreach (var item in args)
            {
                AddParameter(cmd, item);
            }

            // Call logging
            if (!String.IsNullOrEmpty(sql))
                DoPreExecute(cmd);

            return cmd;
        }

    }
}
`

**Comment by MB34** [comment]
We are actually calling a function vs. a procedure and after posting this, I found that I could do it like this to return the cursor by using an Out parameter:
`public List<DuesInfoResponse> GetDuesInfo(int PID, string Designation)
{
    List<DuesInfoResponse> ret = new List<DuesInfoResponse>();
    var result = new OracleParameter
    {
        ParameterName = "RESULT",
        Direction = System.Data.ParameterDirection.InputOutput,
        OracleDbType = OracleDbType.RefCursor
    };
    string sql = $@"DECLARE RESULT REGISTRATIONS_API_PKG.REF_CUR; BEGIN @0 := CIC3.F_PARTDUESINFO("+PID+", '"+Designation+"'); END;";
    var res = _db.db.Fetch<DuesInfoResponse>(sql, result);

    return res;
}

// definition of the Dues Response...
public class DuesInfoResponse
{
    public int ParticipantID { get; set; }
    public string Expiration { get; set; }
    public int Credit { get; set; }
    public int CanPay { get; set; }
    public int Amount { get; set; }
    public int Designated { get; set; }
    public int Pending { get; set; }
    public string Designation { get; set; }
}
.`
The same technique may also work on procedures. I just haven't tested it, yet. 
We had previously used this technique on one of our functions that returned a varchar2 result as it would not return the value otherwise.

**Comment by cjpit** [comment]
yep although its a fair bit of extra code each time you have to do it :/ all that sql is kinda hard to read.  With solution above, then it becomes something like var result  =  _db.RefCursorQuery<someobjecttype>("QC_GL_PKG.GET_GLB_BY_SYSCM", 1, "JRNL")

**Comment by MB34** [comment]
How did you include the above code in your PetaPoco source? When I add it to my PetaPoco.cs file I get all kinds of errors.

**Comment by MB34** [comment]
I finally got it working, however, your code creates a ReturnValue OUT parameter when the function that RETURNS a RefCursor actually doesn't have one and I get a "not all variables bound" error.
Would you mind posting the definition to your `QC_GL_PKG.GET_GLB_BY_SYSCM` function or procedure?

**Comment by MB34** [comment]
This is the function I'm calling:
```
CREATE OR REPLACE function CIC3.f_partduesinfo(pPartID number, pDesig varchar2)
    return registrations_api_pkg.ref_cur is
    v_partduesinfo registrations_api_pkg.ref_cur;
```
like this:
```
var res = _db.db.RefCursorQuery<DuesInfoResponse>("CIC3.F_PARTDUESINFO", 948604, "CISR");
return res.SingleOrDefault<DuesInfoResponse>();
```
