### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by hunguyen75** [CollaboratingPlatypus/PetaPoco#169]
I really enjoy using your ORM tool in building my applications. I am just curious if it can be extented to be used with Microsoft Access?

**Comment by pleb** [comment]
Access should support ODBC - I think. If it does, The feature would be adding support for ODBC connections. If you'd like ODBC support, please open another issue as a feature request. For more information please read https://guides.github.com/activities/contributing-to-open-source/
