### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by JobaDiniz** [CollaboratingPlatypus/PetaPoco#180]
So far, I loved PetaPoco, but is this library dead?
I'd like to see this library make an assembly instead of the class and break thing apart, folowing a more good design. More people could contribute to this project, which is a great tiny ORM project.
I don't want an EntityFramework, but some things could be improved to make queries even easier.
It's been 1 year since the last nuget release.

So, any news?

**Comment by pleb** [comment]
# PetaPoco is very much alive!!! 

It'll be a few weeks before the ball is really rolling. I'll be adding more information over the next few days

**Comment by pleb** [comment]
Just published update nuget packages. Proof that this project is alive. Looking for help #204

**Comment by dlwiii** [comment]
Thanks pleb!
