### ISSUE TITLE
No support for Mono.Data.Sqlite

### ISSUE THREAD

**Issue by AlekseyMartynov** [CollaboratingPlatypus/PetaPoco#182]
In `public static DatabaseType Resolve(string TypeName, string ProviderName)` there is the code `if (TypeName.StartsWith("SQLite")) `

Case-sensitive comparison makes PetaPoco not compatible with **Mono.Data.Sqlite**, which type names have "Sqlite" spelling. 

(I am using NuGet package 5.0.1)

**Comment by pleb** [comment]
I think we'll aim for CoreClr ASP 5 (Vnext) support to address cross-plat

**Comment by ancailliau** [comment]
You can use `Mono.Data.Sqlite` by using a custom db provider.

```
public class MonoSQLiteDatabaseProvider : PetaPoco.SQLiteDatabaseProvider
{
	public override DbProviderFactory GetFactory()
	{
		return GetFactory("Mono.Data.Sqlite.SqliteFactory, Mono.Data.Sqlite, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756\n");
	}

	public MonoSQLiteDatabaseProvider()
	{
	}
}

```
and

```
var db = DatabaseConfiguration.Build()
				  .UsingConnectionString(connectionString)
				  .UsingProvider(Singleton<MonoSQLiteDatabaseProvider>.Instance)
				  .Create();
```

**Comment by pleb** [comment]
Thanks @ancailliau. If you don't mind, I'll add the `MonoSQLiteDatabaseProvider` class you have there to PetaPoco

**Comment by ancailliau** [comment]
My code is yours. Feel free to use it as you wish. I'll be glad to remove my class from my code on a next update of the lib :-)
