### ISSUE TITLE
How to get latest PetaPOCO.cs for latest version 5.0.1?

### ISSUE THREAD

**Issue by jibhatt** [CollaboratingPlatypus/PetaPoco#183]
Hi,

I understand there is a latest version 5.0.1 availble. I am not able to find the PetaPOCO.cs file with version 5.0.1 (I could only locate 4.0.3 here https://github.com/toptensoftware/PetaPoco/blob/master/PetaPoco/PetaPoco.cs)

Please let me know from where to download PetaPOCO.cs 5.0.1

**Comment by pleb** [comment]
https://www.nuget.org/packages/PetaPoco.Core/
