### ISSUE TITLE
v5: Db.Update() fails with anonymous type

### ISSUE THREAD

**Issue by tomagnew** [CollaboratingPlatypus/PetaPoco#191]
This is a follow up to an older post which was never answered: https://github.com/toptensoftware/PetaPoco/issues/119

On the main TopTen Software documentation page for PetaPoco (http://www.toptensoftware.com/petapoco/), it states that one way to update partial fields in a poco is:
"Or you can pass an anonymous type to update a subset of fields. In this case only the article's title field will be updated."
<pre>db.Update("articles", "article_id", new { title="New title" }, 123);</pre>

This does not work in v5. However, as stated by the previous commentor, the work-around:

<pre>db.Update("articles", "article_id", new {article_id=anything, title="New title" }, 123);</pre>

works just fine. I LOVE PetaPoco and this method of partial record updating. Does anyone know why this hasn't been fixed this or the documentation updated?

**Comment by pleb** [comment]
The `article_id=anything` could be trouble if the anything is not the correct type.

**Comment by pleb** [comment]
Fixed. Will be in version > 5.1.62
