### ISSUE TITLE
Is bulk insert or batching supported

### ISSUE THREAD

**Issue by QuAzI** [CollaboratingPlatypus/PetaPoco#195]
Can I insert multiple rows as one query?

	public class article
	{
		public long article_id { get; set; }
		public string title { get; set; }
		public DateTime date_created { get; set; }
		public bool draft { get; set; }
		public string content { get; set; }
	}

	var array = new article[100];
	/* filling array */
	db.Insert(array);

Which must be equivalent to the next query

	INSERT INTO article (article_id, title , date_created, draft, content) 
	VALUES
	  (1, title , date_created, draft, content),
	  /* all records */
	  (100, title , date_created, draft, content);

**Comment by pleb** [comment]
I'm sorry that your issue has been left for so long. In an effort to reboot PetaPoco your issue has been closed. If you think this is still a problem. Please feel free to open and another issue. Please pass the word on that PetaPoco is back. We're looking for people #204.
