### ISSUE TITLE
Operand type clash: nvarchar is incompatible with image

### ISSUE THREAD

**Issue by fmccown** [CollaboratingPlatypus/PetaPoco#198]
When Petapoco is sent a byte array that is set to null, SQL Server will throw an exception (Operand type clash: nvarchar is incompatible with image) because the type of the SQL parameter cannot be derived from the null value provided. See http://stackoverflow.com/questions/2420708/operand-type-clash-nvarchar-is-incompatible-with-image for more information.

This can be fixed by adding the if statement below in PetaPoco.AddParam:

```c#
if (value == null && pi.PropertyType.Name == "Byte[]")
{
     p.DbType = DbType.Binary;
} 
```

**Comment by pleb** [comment]
@fmccown thanks for the contribute. 

I've added integration tests to confirm the bug and fixed the issue with basically the code you supplied. Cheers

**Comment by pleb** [comment]
Released
