### ISSUE TITLE
Documentation confusing on transactions and threads

### ISSUE THREAD

**Issue by petsuter** [CollaboratingPlatypus/PetaPoco#199]
Under [Transactions](http://www.toptensoftware.com/petapoco/#transactions) the documentation states:
> Note: for transactions to work, all operations need to use the same instance of the PetaPoco database object. 

This is quite confusing, as apparently what is meant is "...all operations OF ONE TRANSACTION need to use the same instance...". (But not operations of different transactions!)

In fact operations (of different transactions) must use a different instance if they are on a different thread. (It follows that all operations of one transaction must run on the same thread.) Correct?

Please clarify that section of the documentation, many thanks!

**Comment by pleb** [comment]
A wiki is planned
