### ISSUE TITLE
PetaPoco casts all my Arguments to integer

### ISSUE THREAD

**Issue by phryneas** [CollaboratingPlatypus/PetaPoco#200]
I have code like this:

    FW fw = db.Single<FW>(
        PetaPoco.Sql.Builder
            .Select("*")
            .From(FW.TABLE)
            .Where("AX = @0", "E6F5CCA"));

and my Database ConncetionString looks like

    <add name="DB"
       connectionString="Driver={PostgreSQL ANSI};Server=192.168.33.2;Port=5432;Database=db;Uid=user;Pwd=pw;" 
       providerName="System.Data.Odbc"
    />

Now, executing this I get the error message

> System.Data.Odbc.OdbcException (0x80131937): ERROR [42883] ERROR: operator does not exist: character varying = integer;

When I output 

    db.LastCommand
I get this:

    SELECT *
    FROM schema.myDB
    WHERE (AX = @0)
         -> @0 [String] = "E6F5CCA"

So theoretically it should be doing everything correctly, but apparently PetaPoco passes my string "E6F5CCA" as integer, for whatever reason. I also tried other strings like "test", with the same result.

Am I doing something blatantly wrong or is this a bug?

**Comment by pleb** [comment]
Doesn't seem like PP is at fault here. If it's still happening, please PR an integration to show the issue
