### ISSUE TITLE
OUTPUT inserted.[primaryKeyName] with enabled Triggers

### ISSUE THREAD

**Issue by Curlack** [CollaboratingPlatypus/PetaPoco#201]
I'm running an insert statement using PetaPoco v5.0.1 (available via NuGet) and got the following error: <b>The target table of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.</b>
I did the following to get around it:

<ul><li>Modify PetaPoco.Database.Insert method where the command text is set: </br>
<i></br>string commandText = string.Format("{3}INSERT INTO {0} ({1}){4} VALUES ({2}){5}",
  _dbType.EscapeTableName(tableName),
  string.Join(",", names.ToArray()),
  string.Join(",", values.ToArray()),
  "{0}","{1}","{2}" //Placeholders for the adapt method below
);
</br></br>
if (autoIncrement) {</br>
  commandText = _dbType.AdaptInsertStatementToReturnNewID(primaryKeyName, </br>commandText);</br>
}
</br></br>
cmd.CommandText = commandText;</i></li>
<li>Rename PetaPoco.DatabaseType.GetInsertOutputClause method name to ...</br><i>AdaptInsertStatementToReturnNewID and also pass the prepared insert statement e.g. {0} INSERT INTO [table] ([column1],...,[columnn]) {1} VALUES (@0,...,@n) {2} and return the insertStatement by default</i></li>
<li>Changed the SqlServer DatabaseType implementation of the AdaptInsertStatementToReturnNewID method to the following:</br>
<i>if (insertStatement.Contains("{0}") && insertStatement.Contains("{1}") && insertStatement.Contains("{2}")) {</br>
  var tempTableClause = "DECLARE @NewID TABLE ([NewID] uniqueidentifier); ";</br>
  var insertOutputClause = String.Format(" OUTPUT INSERTED.[{0}] INTO @NewID", primaryKeyName);</br>
  var returnSelectStatement = "; SELECT NewID FROM @NewID;";</br>
  return String.Format(insertStatement, tempTableClause, insertOutputClause, returnSelectStatement);</br>
}</br></br>

return insertStatement;</i></li>
</ul>

**Comment by cmwong** [comment]
Another way to fixed it.    
    public class SqlServerDatabaseProvider : DatabaseProvider
    {
        public override object ExecuteInsert(Database db, System.Data.IDbCommand cmd, string primaryKeyName)
        {
            // 20160523 to fixed the OUTPUT clause When trigger in on
            cmd.CommandText += ";\nSELECT SCOPE_IDENTITY()";
            return db.ExecuteScalarHelper(cmd);
        }
        // 20160523 to fixed the OUTPUT clause When trigger in on
        //public override string GetInsertOutputClause(string primaryKeyName)
        //{
        //    return String.Format(" OUTPUT INSERTED.[{0}]", primaryKeyName);
        //}
    }

**Comment by Curlack** [comment]
I had to keep the declare..select parts, but modifying the statement during the ExecuteInsert in a custom provider worked . Thanks for the advice. Your solution is way more elegant.
