### ISSUE TITLE
PetaPoco has new maintainers. Here's what's on our to-do list 

### ISSUE THREAD

**Issue by pleb** [CollaboratingPlatypus/PetaPoco#202]
<https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Roadmap>

**Comment by poke** [comment]
Hey pleb, wow, who would have thought that PetaPoco would ever become alive again—that’s some great news!

Unfortunately, I have been out of the loop far too long, so I probably won’t be able to help out. But what you have planned there sounds really great, so I just want to say thank you for picking it up and I wish all the best for PetaPoco :)

**Comment by pleb** [comment]
@poke super excite to reboot PetaPoco too. I'll be putting a call soon for new members to join the PetaTeam, as we're looking for people to triage new issues, maintain documentation, conduct code reviews, and etc. Keep an eye out, because you never know there maybe something that interests you :smiley:

**Comment by pleb** [comment]
Ok positions are up #204

**Comment by njy** [comment]
@pleb :+1: 
I'm glad to hear this. Regarding the < 4.5 thing: everybody I know is on 4.5 or greater, so there's that as a stat for you.
What about NPoco https://github.com/schotime/NPoco , the fork from @schotime ? It has a lot of fixes and new features, and I was wondering if you were planning to start from there.
Basically forking back the fork, something like the nodejs -> iojs -> nodejs thing :)

**Comment by pleb** [comment]
@nij I've emailed both @schotime and @tmenier asking if they want to join the effort. I wouldn't feel comfortable taking their work without permission. Ideally, I would like them to come over to PetaPoco and join the maintainers team (I would probably make a new team for them, as I see them as fulling a n Admin/Lead roll). However, they both have popular forks I can understand if they do not want to join PetaPoco and continue with their own gig.

**Comment by pleb** [comment]
Hey everyone, the roadmap has been posted. <https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Roadmap>
