### ISSUE TITLE
Support for SQLite .NET and Firebird .NET

### ISSUE THREAD

**Issue by high1** [CollaboratingPlatypus/PetaPoco#21]
Have you considered or tested support for SQLite and Firebird databases? I think that these are common among .NET developers, and have active developed and supported providers.

**Comment by pleb** [comment]
#210 Firebird DB

I'm sorry that your issue has been left for so long. In an effort to reboot PetaPoco your issue has been closed. If you think this is still a problem. Please feel free to open and another issue. Please pass the word on that PetaPoco is back. We're looking for people #204.
