### ISSUE TITLE
Pick a logo

### ISSUE THREAD

**Issue by pleb** [CollaboratingPlatypus/PetaPoco#212]
Contenders: 

Logo 1 | Logo 2
----------| --------
|![Logo1](https://raw.githubusercontent.com/CollaboratingPlatypus/PetaPoco/development/Media/Logo1/PetaPocoLogo1CropSmall.png)|![Logo1](https://raw.githubusercontent.com/CollaboratingPlatypus/PetaPoco/development/Media/Logo2/PetaPocoLogo2Small.png)|

**Comment by pleb** [comment]
Logo 2 + 1

**Comment by eldiosyeldiablo** [comment]
Logo 2

**Comment by dlwiii** [comment]
I like the kookaburra

**Comment by jezza323** [comment]
Logo 2, with the distinctive brown band around the eyes added for correctness pls

**Comment by davispauljohn** [comment]
Yep, Logo2

**Comment by pleb** [comment]
Looks like Logo2 is the winner!
