### ISSUE TITLE
Issues with Visual Studio 2013

### ISSUE THREAD

**Issue by john-susco** [CollaboratingPlatypus/PetaPoco#219]
I am able to install the Nuget package for 5.0.1, and the templates properly generate models etc.

Attempting to install simply using Install-Package PetaPoco (which installs 5.1.84) results in:

Compiling transformation: The name 'isnullable' does not exist in the current context	{path}PetaPoco.Core.ttinclude	1214	

With the new direction of PetaPoco, is compatibility with Visual Studio 2013 currently supported?

**Comment by pleb** [comment]
Hi @john-susco, there shouldn't be a problem with using VS 2013. Sounds like a bug. 

Could you try changing line 1233 on PetaPoco.Core.ttinclude to 

`col.IsNullable = "YES".Equals(rdr["isnullable"].ToString()) || "Y".Equals(rdr["isnullable"].ToString());`

**Comment by pleb** [comment]
Hi @john-susco I've fixed this bug. Sorry about that. I'm going to add to the roadmap integration testing for the T4 templates. The fix will be in version > 5.1.84 (about twenty minutes after this post)
