### ISSUE TITLE
Documentation QC

### ISSUE THREAD

**Issue by pleb** [CollaboratingPlatypus/PetaPoco#220]
Hey @ch00nz 

Can you please review the following doc pages

**Repo pages**
[Read me - dev version](https://github.com/CollaboratingPlatypus/PetaPoco/blob/development/README.markdown)
[Contributing - dev vesrion]
(https://github.com/CollaboratingPlatypus/PetaPoco/blob/development/contributing.md)

**Wiki pages**
[Home](https://github.com/CollaboratingPlatypus/PetaPoco/wiki)
[Roadmap](https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Roadmap)
[Quick start](https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Quick-Start)
and the shared footer

Cheers

**Comment by joshka** [comment]
Hey,
Just a quick one, the link to the Quick Start page from the Home page is missing a hyphen.

**Comment by pleb** [comment]
Thanks @joshka. Fixed it ;)

**Comment by ch00nz** [comment]
on the Read me page
- under the "Contributing" section, "From" is spelt wrong in 'PetaPoco welcomes input form the community.'
on the Contributing page
- "PetaPoco has a coding standards and guidelines." should be "PetaPoco has coding standards and guidelines."
- if you are running with "All bug fixes should include a unit test(s). " then you shoudl be consistent in "All features must include unit test(s) and integration test(s)." ie: "All features must include a unit test(s) and an integration test(s)."

**Comment by pleb** [comment]
Cheers @ch00nz. Fixes all listed items
