### ISSUE TITLE
Faster PostgreSQL Exists query suggestion

### ISSUE THREAD

**Issue by havotto** [CollaboratingPlatypus/PetaPoco#223]
Hi,

This is my first post here. Great project!

I would like to suggest a faster Postgres exists query.

Now this is used by PetaPoco: SELECT COUNT(\*) FROM {0} WHERE {1}
Postgres is not too efficient with count(\*), it has to scan all the matching records.
Here are some other queries that are faster because they stop, when a matching record is found: 

This one converts bool to int with CASE:
SELECT CASE WHEN EXISTS(SELECT 1 FROM {0} WHERE {1}) THEN 1 ELSE 0 END
This one converts with Postgres-specific cast operator:
SELECT EXISTS(SELECT 1 FROM {0} WHERE {1}) :: integer

And this one counts a limited resultset:
SELECT COUNT(\*) FROM (SELECT 1 FROM {0} WHERE {1} LIMIT 1) AS t

All of them work with supported versions of Postgres.
I suggest the one with CASE because it is intuitive and standard SQL.

**Comment by pleb** [comment]
Thanks @havotto for the contribute

**Comment by pleb** [comment]
@havotto it'll be in the next release. Thanks again!

**Comment by pleb** [comment]
Released
