### ISSUE TITLE
Mapping Entities - Doc review

### ISSUE THREAD

**Issue by pleb** [CollaboratingPlatypus/PetaPoco#232]
Doc review request - [Mapping Pocos](https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Mapping-Pocos)

@CollaboratingPlatypus/petapoco-documentation

Community input welcome!

**Comment by davispauljohn** [comment]
If models/pocos/entities are interchangeable, maybe just use "pocos" for consistency

**Comment by pleb** [comment]
Good point @davispauljohn
