### ISSUE TITLE
Exists calls broken for autogenerated POCOs in schemas on SQL server.

### ISSUE THREAD

**Issue by BrendanLally** [CollaboratingPlatypus/PetaPoco#242]
This commit: 
https://github.com/CollaboratingPlatypus/PetaPoco/commit/1523975ff25f4dbbb67a28db1c05386f008e81c7 

breaks 'Exists' calls against POCOs which are generated with schemas.

So if I have the schema 'foo', which contains a table 'bars' and use the T4 template against the schema it, the auto-generated poco bar gets [TableName("foo.bars")] annotated to it.

When trying to do a db.Exists<Bar>(... the sql generated is 
IF EXISTS (SELECT [foo.bars] FROM [{0}] WHERE ...
which is not a valid table name (it is looking for dbo.[foo.bars] rather than [foo].[bar] and throws an SQL exception.

This is true for the SQL server provider, I haven't tested with the other providers touched by that commit.

**Comment by pleb** [comment]
Thanks for the report. I'll investigate this asap

**Comment by pleb** [comment]
Hi @BrendanLally, I've added integration tests for this, but I couldn't reproduce. Can you check out the tests and let me know how they differ?

https://github.com/CollaboratingPlatypus/PetaPoco/commit/45de1c91b02b56443057703354d3d00a1cb21364

**Comment by BrendanLally** [comment]
You can close this issue as obsolete.

My behaviour was present in nuget version 5.1.114 (which is the one I had upgraded to), Running your integration tests against the sqlprovider as was released in that version does fail as expected, but this commit: https://github.com/CollaboratingPlatypus/PetaPoco/commit/baa3bf78df57b5b2d5e637e7a1192ceceaba0e46 resolved the problem, and the master branch and nuget version 5.1.121 both work correctly.

Guess I should have pulled from master before reporting; sorry about that.

**Comment by pleb** [comment]
Good to hear. Keep reporting, as I want PP stable and trusted!
