### ISSUE TITLE
System.Security.VerificationException thrown while querying into a dynamic

### ISSUE THREAD

**Issue by JonathanHalper** [CollaboratingPlatypus/PetaPoco#243]
I have been using PetaPoco for a few years now, and recently noticed that the project was being updated again (thanks, btw!).  I updated to Nuget PetaPoco core version 5.1.121, and after running regression tests found that some queries were breaking with a System.Security.VerificationException thrown from within PetaPoco.  I tried both the compiled and standalone file variants of PetaPoco Core with the same result.

After researching System.Security.VerificationException, I tried retargeting the project from .NET 4.5 to a newer version and building using x64 and neither of those fixed the problem.  I also found a Microsoft Microsoft update for .NET 4.5 (https://support.microsoft.com/en-us/kb/2748645) , but  x86 or x64 installers said my system was not eligible for the update.

It's still possible that the problem is localized to my solution / dev machine, however what's interesting is that this problem appears to only be happening for queries that use 'dynamic'.  I replaced use of dynamic with a POCO, and the problem went away.   

Sample query that fails:
```
dynamic dynamicQueryRow = db.SingleOrDefault<dynamic>("SELECT Email, Phone, Street1, Street2, City, State, Zip FROM MyTable where TrackingId = @0", trackingId);
```
A sample  stack trace:
at petapoco_factory_0(IDataReader )
at PetaPoco.Database.<Query>d__14`1.MoveNext() in {Our Project Path}\Models\PetaPoco.cs:line 988
at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
at PetaPoco.Database.SingleOrDefault[T](String sql, Object[] args) in {Our Project Path}\Models\PetaPoco.cs:line 1106

**Comment by pleb** [comment]
@JonathanHalper it's on my list for this week ;)

**Comment by pleb** [comment]
@JonathanHalper you'll want PetaPoco 5.1.126 or later ;)

**Comment by JonathanHalper** [comment]
Thanks, that fixed it!
