### ISSUE TITLE
Many Warnings in the build output with PetaPoco.cs (Core)

### ISSUE THREAD

**Issue by MamadouSy** [CollaboratingPlatypus/PetaPoco#245]
Hi, 

I've a little request.
I'm using PetaPoco Core install from Nugets in Visual Studio 2013 (so the single file Models/PetaPoco.cs).

I'm generating the `XML Documentation file` with my project (Project Properties > Build > Output > XML Documentation file)

Once it's activated, I have a bunch of Warnings in the build output.
Below some of them (repeated several times):

    Models\PetaPoco.cs(2500,93,2500,99): warning CS1066: The default value specified for parameter 'onFail' will have no effect because it applies to a member that is used in contexts that do not allow optional arguments
    Models\PetaPoco.cs(3296,22,3296,28): warning CS1591: Missing XML comment for publicly visible type or member 'PetaPoco.IQuery'
    Models\PetaPoco.cs(5709,9,5709,108): warning CS1570: XML comment on 'PetaPoco.Sql.Select(params object[])' has badly formed XML -- 'End tag 'member' does not match the start tag 'param'.'
    Models\PetaPoco.cs(4627,69,4627,81): warning CS1573: Parameter 'allowDefault' has no matching param tag in the XML comment for 'PetaPoco.DatabaseProvider.Resolve(string, bool)' (but other parameters do)

I know that the PetaPoco.cs file is auto-generated, so I guess you can't fix all of the XML comments and little annoying warnings.

My suggestion, to bypass the issue, is to simply disable some warnings for the PetaPoco.cs file.

Below an MSDN article which describe how to disable warnings for a given file: 
https://msdn.microsoft.com/fr-fr/library/441722ys.aspx

I've already test that in my PetaPoco.cs and that drops all warnings for PetaPoco.cs

Only add this line of code before the namespace PetaPoco

    #pragma warning disable 1066,1570,1573,1591

I hope my explanation is clear.
Tell me if you need more details or an example.

Cheers,

Mamadou

**Comment by pleb** [comment]
@MamadouSy not a problem. I'll add this in next release

**Comment by MamadouSy** [comment]
Cool thanks a lot.

**Comment by pleb** [comment]
It's in the latest release

**Comment by MamadouSy** [comment]
Thanks a lot.
Works like a charm!
