### ISSUE TITLE
Internal Properties aren't mapped

### ISSUE THREAD

**Issue by hobnob** [CollaboratingPlatypus/PetaPoco#261]
Hi,

I'm creating a library that uses certain database fields but doesn't expose them to outside assemblies. To achieve this I'm using the `internal` keyword on certain properties. This used to work fine until I upgraded PetaPoco.Core to 5.1.140 (from 5.0.1) via Nuget, but now my internal properties aren't being set from the database.

For example, given the following object a `Fetch` or `Query` won't populate the `PhoneNumber` property:

```c#
[PetaPoco.TableName("tbl_Author")]
[PetaPoco.PrimaryKey("Id")]
public class Author
{
    public int Id { get; set; }
    public string Name { get; set; }
    internal string PhoneNumber { get; set; }
}
```

Any help you can provide on this would be great

**Comment by pleb** [comment]
@hobnob I add two integration tests to confirm the fix. I'll be releasing this shortly. Thanks for the contribute

**Comment by hobnob** [comment]
@pleb  Cool, thanks :-)
