### ISSUE TITLE
ASP.NET 5 Support?

### ISSUE THREAD

**Issue by tikaPahadi** [CollaboratingPlatypus/PetaPoco#267]
Does PetaPoco have support for ASP.NET 5? I am not getting to it.

**Comment by pleb** [comment]
See [roadmap](https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Roadmap) for planned support.

That said, you can use PetaPoco now with RC1, but you'll need to target the full framework (.net 4.6) as it won't work with lesser complete corefx. Lastly, you'll need to use PetaPoco compiled as the single file deploy versions don't work with the newer project layouts.

With fundamental changes on the way between RC1 and RC2, we're not going to start work on .NET Core 1.0 until after the release of RC2. Don't forget that your DB provider of choice will need to support  .NET Core 1.0.

Also see http://stackoverflow.com/questions/35343435/using-petapoco-in-asp-net-core-mvc-6
