### ISSUE TITLE
Problem when using bracket on order by clause

### ISSUE THREAD

**Issue by diegodfsd** [CollaboratingPlatypus/PetaPoco#268]
I have a column named like user in my table and I need using it in my order by clause, but user in sql server is a reserve word, so I need use brackets in my sql query. 

My query looks like that:

```SELECT [Level], [Description], [CreatedAt], [User]
   FROM MyTable  
 ORDER BY [User]```

When I try execute a query like the above query in the PetaPoco I get a exception because I'm using brackets in my order by clause and whether I trying execute without brackets the result is not like expected.

**Comment by twheelmaker** [comment]
until fixed, maybe just use a non-reserved alias like SELECT [Level], [Description], [CreatedAt], [User] as MyUser FROM MyTable ORDER BY MyUser

**Comment by pleb** [comment]
Added integration test. Confirms this has already been fixed
