### ISSUE TITLE
.NET  4.6+ does not add T4 Template Poco Builder

### ISSUE THREAD

**Issue by rendall** [CollaboratingPlatypus/PetaPoco#271]
Nuget no longer installs T4 Template Poco Builder (Database.tt, etc) neither in /Models nor anywhere from .NET framework 4.6 on.

**Comment by rendall** [comment]
To replicate, add a new MVC project using .NET Framework 4.6 or above. Use NuGet to install PetaPoco into the project. Note that there are no new files added in /Models.

**Comment by JohnMarsing** [comment]
If I want to upgrade my project to .Net Framework 4.6, is there a good work around for this?

**Comment by pleb** [comment]
@rendall @JohnMarsing the work around for now is to copy/paste these files manually. You can download them from the master branch or extract the nuget package (packages are zip files).

**Comment by pleb** [comment]
It worked for me. I'm using VS2013 Update 3 and the latest PetaPoco

![image](https://cloud.githubusercontent.com/assets/595869/17267436/a974a14c-564c-11e6-85e0-8ca592903b2e.png)

**Comment by rendall** [comment]
Let's close this :)
