### ISSUE TITLE
Didn't get correct value from some table 

### ISSUE THREAD

**Issue by kmlxk** [CollaboratingPlatypus/PetaPoco#275]
PetaPoco is the best ORM lib that I've used in C#.
But these days I met this strangy problem. 
I queried some rows as usual, and code like this: 

> var result = db.Query<Models.SPC_History>( 
>                     "select top 3 * from SPC_History ORDER BY CreateTime DESC");
>             foreach (var item in result) // result.Items)
>             {
>                 Console.WriteLine(item.ToString());
>             }

But I got an object that all the fields are default value.

`ID:0, Mat_Code:, Item_Code:, MES_LotCode:, Lot_Code:, Lot_Year:, CPD_Code:, GYCS
_Code:, StandardMaxValue:0, StandardMinValue:0, StandardTLValue:0, AverageValue:
0, MaxValue:0, MinValue:0, STD_Deviation1:0, STD_Deviation2:0, CPKValue1:0, CPKV
alue2:0, HisSample:0, MaxCount:0, MinCount:0, PassPate:0, LevelValue:0, CreateTi
me:0001-01-01 0:00:00, CPKHeadTimes:0, CPKTailTimes:0, StopCount:0, STARTTIME:00
01-01-01 0:00:00, ENDTIME:0001-01-01 0:00:00, Rule_ver:,`

Then I followed the debugger into PetaPoco.cs, I found  IDataReader r has the correct values

> var factory = pd.GetFactory
> poco = factory(r); << IDataReader r has the correct values

But I was unable to step into the factory(r), and I don't knowlege in IL code.
So I really need your help . 

PetaPoco Version: release v4.0.3 
SQLServer Version: Microsoft SQL Server 2014 - 12.0.2000.8 (X64) 

The sample table and data is as follows:

`

CREATE TABLE [dbo].[SPC_History] (
[ID] bigint NOT NULL ,
[Mat_Code] varchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[Item_Code] varchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[MES_LotCode] varchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[Lot_Code] varchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[Lot_Year] varchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[CPD_Code] varchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[GYCS_Code] varchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[StandardMaxValue] float(53) NULL ,
[StandardMinValue] float(53) NULL ,
[StandardTLValue] float(53) NULL ,
[AverageValue] float(53) NULL ,
[MaxValue] float(53) NULL ,
[MinValue] float(53) NULL ,
[STD_Deviation1] float(53) NULL ,
[STD_Deviation2] float(53) NULL ,
[CPKValue1] float(53) NULL ,
[CPKValue2] float(53) NULL ,
[HisSample] float(53) NULL ,
[MaxCount] float(53) NULL ,
[MinCount] float(53) NULL ,
[PassPate] float(53) NULL ,
[LevelValue] float(53) NULL ,
[CreateTime] datetime NULL ,
[CPKHeadTimes] float(53) NULL ,
[CPKTailTimes] float(53) NULL ,
[StopCount] int NOT NULL ,
[STARTTIME] datetime NULL ,
[ENDTIME] datetime NULL ,
[Rule_ver] varchar(50) COLLATE Chinese_PRC_CI_AS NULL 
)
ON [PRIMARY]
GO

CREATE INDEX [index_SPC_History] ON [dbo].[SPC_History]
([CreateTime] ASC) 
ON [PRIMARY]
GO

INSERT INTO [SPC_History] ([ID], [Mat_Code], [Item_Code], [MES_LotCode], [Lot_Code], [Lot_Year], [CPD_Code], [GYCS_Code], [StandardMaxValue], [StandardMinValue], [StandardTLValue], [AverageValue], [MaxValue], [MinValue], [STD_Deviation1], [STD_Deviation2], [CPKValue1], [CPKValue2], [HisSample], [MaxCount], [MinCount], [PassPate], [LevelValue], [CreateTime], [CPKHeadTimes], [CPKTailTimes], [StopCount], [STARTTIME], [ENDTIME], [Rule_ver]) VALUES (2014336, '5', 'BC_11102047', 'MES_2016_5_211', '211', '2016', 'CPD_CX_CGZ', 'GYCS_0090', '138', '132', '135', '138.939575195313', '141.192520141602', '136.399703979492', '0', '1.07575178146362', '0', '-0.291137546300888', '602', '479', '0', '19.2000007629395', '0', '2016-1-18 16:42:58', '180', '-180', 0, '2016-1-18 15:03:52', '2016-1-18 16:09:58', '1.0');
GO

`

**Comment by kmlxk** [comment]
Stupid me. I defined the Model in the wrong way...

>     public class SPC_History
>     {
>         public Int64 ID;
>         public string Mat_Code;

change to this:

>     public class SPC_History
>     {
>         public Int64 ID { get; set; }
>         public string Mat_Code { get; set; }

**Comment by picasso566** [comment]
You also forgot to include the definition of the database table:

CREATE TABLE [dbo].SPC_History
ON [PRIMARY]
GO

Should be 

CREATE TABLE [dbo].SPC_History (SPC_HistoryId Int, ... )
ON [PRIMARY]
GO

**Comment by picasso566** [comment]
Also, can you try a fetch and tell me the result?

List<SPC_History> result = db.Query(
"select top 3 * from SPC_History ORDER BY CreateTime DESC");
foreach (SPC_History item in result) )
{
Console.WriteLine(item.ToString());
}

**Comment by kmlxk** [comment]
Thank you picasso566
The result is like this:

> , ID:2109563, Mat_Code:109, Item_Code:BC_11102072, MES_LotCode:MES_2016_109_2, L
> ot_Code:5002, Lot_Year:2016, CPD_Code:CPD_AX_AGZB, GYCS_Code:GYCS_SPC014, Standa
> rdMaxValue:99999, StandardMinValue:-999, StandardTLValue:99999, AverageValue:6.8
> 66625, MaxValue:7.6389, MinValue:6.2066, STD_Deviation1:0, STD_Deviation2:0.2075
> 875, CPKValue1:0, CPKValue2:0, HisSample:1034, MaxCount:0, MinCount:0, PassPate:
> 9999, LevelValue:0, CreateTime:2016-03-25 9:09:13, CPKHeadTimes:180, CPKTailTime
> s:-180, StopCount:0, STARTTIME:2016-03-15 11:12:25, ENDTIME:2016-03-15 13:01:43,
>  Rule_ver:

Because I want to dump the fields so I used ObjectExtensions.cs in this page: https://gist.github.com/baba-s/9285116

---------------------------------------------------

May I ask nother question:
I created a table that defined primary key as uniqueidentifier(in c# is GUID), but when I use db.Insert petapoco throw an type convertion exception from DBNull to Guid. 
It seemed that "SELECT SCOPE_IDENTITY() AS NewID" is not supported where primary key is GUID. 
I currently modified the code and ignored fetch back the guid... but I wonder if is it possible to fetch back the GUID ? Thank you.

> public object Insert(string tableName, string primaryKeyName, bool autoIncrement, object poco)
> 		{
> ...
> case DBType.SqlServer:
> 								cmd.CommandText += ";\nSELECT SCOPE_IDENTITY() AS NewID;";
> 
> 						// Assign the ID back to the primary key property
>                         if (primaryKeyName != null && !id.GetType().Equals(typeof(DBNull)))
> 						{
> 							PocoColumn pc;
> 							if (pd.Columns.TryGetValue(primaryKeyName, out pc))
> 							{
> 								pc.SetValue(poco, pc.ChangeType(id)); //// Exception throws 
> 							}
> 						}

**Comment by picasso566** [comment]
For your second question (I would put it in a new thread):

Insert a GUID in code before the insert. That's one of the main benefits of a GUID is being able to create an Id anywhere in the code and still have a low incident of collision.

**Comment by pleb** [comment]
Great work everyone!
