### ISSUE TITLE
dotnetcore

### ISSUE THREAD

**Issue by JCKodel** [CollaboratingPlatypus/PetaPoco#277]
I have a working version (252 unit test passing) of PetaPoco (+ my contributions that never made to the main branch + Multi-Set results) running in DotNetCore50.

How can we merge that? =)

**Comment by pleb** [comment]
You would need to issue a PR so that I can see the changes. 

We also need PetaPoco to continue to work for the full framework, so keep that in mind.

Until RC2 is released I hadn't planned looking into this too much, so please keep in mind that changes may not make it.
