### ISSUE TITLE
VarBinary support for SQL Server

### ISSUE THREAD

**Issue by toptensoftware** [CollaboratingPlatypus/PetaPoco#28]
Trying to insert byte[] value to a SQL Server VarBinary(MAX) column fails with the following exception:

"implicit conversion from data type nvarchar to varbinary(max) is not allowed"

Tried setting parameter.DbType to DbType.Binary and size to -1, the size of the byte array, hard coded 4000 but no luck... .always the same error.

**Comment by ryios** [comment]
There is another way you can get around this by writing your queries a different way:

`DECLARE @@fixedBinaryAnswer VARBINARY(MAX) = CONVERT(VARBINARY(MAX), @BinaryAnswer)
INSERT INTO [polling].[pollQuestionAnswer] 
(pollId, pollQuestionId, pollQuestionChoiceId, userId, intAnswer, longAnswer, dateAnswer, textAnswer, floatAnswer, binaryAnswer, created, createdBy, updated, updatedBy)
VALUES (@PollId, @QuestionId, @QuestionChoiceId, @UserId, @IntAnswer, @LongAnswer, @DateAnswer, @TextAnswer, @FloatAnswer, @@fixedBinaryAnswer, @Created, @CreatedBy, @Updated, @UpdatedBy)
INSERT INTO [polling].[pollUserAnswerMap] (pollId, userId, created, createdby, updated, updatedBy) VALUES(@PollId, @UserId, @Created, @CreatedBy, @Updated, @UpdatedBy)`

This fix will convert the incorrect NVARCHAR null into a VARBINARY Null at the query level in SQL and if it comes in as a VARBINARY already it'll just convert to itself (do nothing basically) and it just works for both setting null and setting a value.

This allows you to pass your pocos to the Sql class so you don't have to manually break out your parameters...... Which get's tedious after a while.....
