### ISSUE TITLE
Attributes to support validation

### ISSUE THREAD

**Issue by waydec** [CollaboratingPlatypus/PetaPoco#29]
I use code generation to create FluentValidation (http://fluentvalidation.codeplex.com/) validator classes. 

I have made a few modifications to PetaPoco.cs and the T4 templates to support the code gen of these classes

If you agree i would love to see this included in the product.

_In PetaPoco.cs_

		// Property Attribute used to pass metadata to Validator class code generator
		// Marks property as nullable
		[AttributeUsage(AttributeTargets.Property)]
		public class NullableAttribute : Attribute
		{
		}

		// Property Attribute used to pass metadata to Validator class code generator
		// Marks string length
		[AttributeUsage(AttributeTargets.Property)]
		public class MaxLengthAttribute : Attribute
		{
			public MaxLengthAttribute() { }
			public MaxLengthAttribute(int maxLength) { MaxLength = maxLength; }
			public int MaxLength { get; set; }
		}

_In PetaPoco.Core.ttinclude_
Add a public field ("MaxLength") to the Column Class

	public class Column
	{
		public string Name;
		public string PropertyName;
		public string PropertyType;
		public bool IsPK;
		public bool IsNullable;

		// Change - Add the following Field
		public int MaxLength;	//Used by [MaxLength(MaxLength)] attribute and ultimately by EntityValidator Class
	}

_In PetaPoco.Generator.ttinclude_
In the column output section add the following code.  It adds padded attributes to the column property declarations

	foreach(Column col in from c in tbl.Columns where !c.Ignore select c)
	{
		// Column bindings
		string nullable = "          ";
		if(col.IsNullable==true)
			nullable = "[Nullable]";
		
		string maxLength = "";
		if(col.PropertyType=="string")
			maxLength = "[MaxLength(" + col.MaxLength.ToString() + ")]";
		maxLength = maxLength.PadRight(17);

		string propertyName = col.PropertyName;
		
		string propertyType = (col.PropertyType + CheckNullable(col));
		propertyType = propertyType.PadRight(12);
	}

I changed the template code to 

<# if (col.Name!=col.PropertyName) { #>
		[Column("<#=col.Name#>")] <#=nullable#> <#=maxLength#> public <#=propertyType#> <#=propertyName#> { get; set; }
<# } else { #>
		[Column] <#=nullable#> <#=maxLength#> public <#=propertyType#> <#=propertyName#> { get; set; }
<# } #>

**Comment by pleb** [comment]
My vote would be for System.ComponentModel.DataAnnotations. However, I know there's other popular ones out there. I guess what's needed is better extension hooks for adding {insert validation provider} support
