### ISSUE TITLE
execute sql error

### ISSUE THREAD

**Issue by newyhj** [CollaboratingPlatypus/PetaPoco#291]
PLATFORM:SQL SERVER 2008+NET 4.5
string sql =
                "select a.id,a.name,count(b.id) as coun from table_a as a left join table_b as b on a.id=b.cid group by a.id,a.name,count(b.id) having count(b.id) " 

var result =db.Page<Goods>(pageIndex, pageSize, sql);

**Comment by pleb** [comment]
What was the error you got?

Are you sure it's not a typo "coun" should be "count"?

**Comment by pleb** [comment]
How did you go @newyhj

**Comment by pleb** [comment]
Closing due to no response for OP
