### ISSUE TITLE
Benchmarks on thousands of records?

### ISSUE THREAD

**Issue by Tdue21** [CollaboratingPlatypus/PetaPoco#292]
Hello, I am currently evaluating PetaPoco for potential use. I have a few questions., First of: 

1. Are there thorough documentation for joins? 
2. Are there any benchmarks for manipulating/joining on data with thousands of records? 

Specifically I have a bit of a problem with understanding how multi queries are supposed to work. Right now I execute my joins so I only return records from e.g. the child table, based on the selection in the parent table. But I have a feeling that this is no the intended/recommended method.

I fear though, that multi queries, as imperfectly as I understand them,  will result in unnecessary loading of records, which will result in excessively memory overhead and time.

Are someone able to clarify these issues for me?

**Comment by Tdue21** [comment]
I suppose that means "no"...

**Comment by pleb** [comment]
Hi @Tdue21, 

I tag the issue as 'community alert'. No community member took the time to reply to you, so I closed the issue. I believe I gave it fair time to be answered.

Maybe try StackOverflow?

Regards, Wade

**Comment by Tdue21** [comment]
It's ok.
