### ISSUE TITLE
Need ODBC support

### ISSUE THREAD

**Issue by masasih** [CollaboratingPlatypus/PetaPoco#294]
I did not find ODBC support, I'm using Sybase ODBC so it thrown an error, could you please add it in code:
```
  internal static IProvider Resolve(string providerName, bool allowDefault, string connectionString)
        {
            // Try again with provider name
            if (providerName.IndexOf("MySql", StringComparison.InvariantCultureIgnoreCase) >= 0)
                return Singleton<MySqlDatabaseProvider>.Instance;
            if (providerName.IndexOf("MariaDb", StringComparison.InvariantCultureIgnoreCase) >= 0)
                return Singleton<MariaDbDatabaseProvider>.Instance;
            if (providerName.IndexOf("SqlServerCe", StringComparison.InvariantCultureIgnoreCase) >= 0 ||
                providerName.IndexOf("SqlCeConnection", StringComparison.InvariantCultureIgnoreCase) >= 0)
                return Singleton<SqlServerCEDatabaseProviders>.Instance;
            if (providerName.IndexOf("Npgsql", StringComparison.InvariantCultureIgnoreCase) >= 0
                || providerName.IndexOf("pgsql", StringComparison.InvariantCultureIgnoreCase) >= 0)
                return Singleton<PostgreSQLDatabaseProvider>.Instance;
            if (providerName.IndexOf("Oracle", StringComparison.InvariantCultureIgnoreCase) >= 0)
                return Singleton<OracleDatabaseProvider>.Instance;
            if (providerName.IndexOf("SQLite", StringComparison.InvariantCultureIgnoreCase) >= 0)
                return Singleton<SQLiteDatabaseProvider>.Instance;
            if (providerName.IndexOf("Oracle", StringComparison.InvariantCultureIgnoreCase) >= 0)
                return Singleton<OracleDatabaseProvider>.Instance;
            if (providerName.IndexOf("Firebird", StringComparison.InvariantCultureIgnoreCase) >= 0 ||
                providerName.IndexOf("FbConnection", StringComparison.InvariantCultureIgnoreCase) >= 0)
                return Singleton<FirebirdDbDatabaseProvider>.Instance;
            if (providerName.IndexOf("OleDb", StringComparison.InvariantCultureIgnoreCase) >= 0
                && (connectionString.IndexOf("Jet.OLEDB", StringComparison.InvariantCultureIgnoreCase) > 0 || connectionString.IndexOf("ACE.OLEDB", StringComparison.InvariantCultureIgnoreCase) > 0))
            {
                return Singleton<MsAccessDbDatabaseProvider>.Instance;
            }
            if (providerName.IndexOf("SqlServer", StringComparison.InvariantCultureIgnoreCase) >= 0 ||
                providerName.IndexOf("System.Data.SqlClient", StringComparison.InvariantCultureIgnoreCase) >= 0)
                return Singleton<SqlServerDatabaseProvider>.Instance;

            if (!allowDefault)
                throw new ArgumentException("Could not match `" + providerName + "` to a provider.", "providerName");

            // Assume SQL Server
            return Singleton<SqlServerDatabaseProvider>.Instance;
        } 

```

**Comment by pleb** [comment]
@masasih there's more, much much more, when adding support for a DB. I'm sorry, but I'm not I'm not going to be adding support for this myself. However, I'll happily accept a PR if the code is of good quality, there's appropriate unit/integration tests, and no regression.

**Comment by matthewsheeran** [comment]
I am about to add this for myself (slicing PetaPoco in to replace my own code) starting by copying the PetaPoco SqlServerDatabaseProvider and renaming to OdbcDatabaseProvider for now (using "System.Data.Odbc.OdbcFactory, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"). :-)
I need to add GetSchema(...) support already to filter lists of tables, databases etc and in any case one needs to handle say DataSourceProductName from MetaDataCollections since many different types of databases can actually be connected to over ODBC and hence their differing behaviours need to be catered for in the OdbcDatabaseProvider code above.  ;-)
I am SQL Server Odbc only for now so the minimal changes I made should be golden for that already. :-)
We will see..
If you need help it is available for a fee until it ever gets checked in.
I came to PetaPoco from Umbraco and its code too is forked and included in its own codebase too.
But one day if I get good vibes here I can contribute it back to the community..
Regards,
Matthew

**Comment by matthewsheeran** [comment]
As you now it is actually more complicated than that - and proably why @masasih got short shrift - as you need to have an open connection to do the GetSchemas - but as I have the PetaPoco.cs source and settled up it afetr much research and reflection (pardon the pun - one can always override the OdbcDatabaseProvider for different databases at connection time even if one had to use reflection to do so (but i think one can avoid that).
OdbcPetaPoco anyone? (I know there are NPoco and AsyncPoco forks (and yet another reason for my choice along with the single source file)).
If i ever check in i will insist on tweaking all the existing source to meet my defacto code standards of best attempt to meet all StyleCop Rules however trivial wherever possible (so i could be a useful guy to let in hehe).
Kindest Regards,
Matthew

**Comment by matthewsheeran** [comment]
Its happening man its happening: it trusn out there are two IProvider Resolve(...)'s additions required.
If I use new Database(this.Connection) then I have to do a this.Connection.Open()/Close()'s before the OpenSharedConnection()/CloseSharedConnection()'s but if i use new Database(this.ConnectionString, this.InvariantName) then I only need to use the latters.
I can start replacing the code in my exiting DbLayer an turn it into a shell for now by using this.Database = new Database(this.ConnectionString, this.InvariantName)!

**Comment by matthewsheeran** [comment]
I hit this (the Parameter Substitution Problem): https://github.com/CollaboratingPlatypus/PetaPoco/pull/166 
So any tips would be apreciated..

**Comment by pleb** [comment]
@matthewsheeran you sound like an interesting fellow. I like it. When you have it working, sounds like you will get there, let's talk PRs ;)
