### ISSUE TITLE
MySql.Data.MySqlClient Provider Cannot found

### ISSUE THREAD

**Issue by LambertW** [CollaboratingPlatypus/PetaPoco#297]
I want to used T4 template to generate models, and use `nuget` to install **MySql.Data**，but it didn't work as expected. It cause exception in follow function `LoadTables`:
``` C#
DbProviderFactory _factory;
	try
	{
		_factory = DbProviderFactories.GetFactory(ProviderName);
	}
	catch (Exception x)
	{
		var error=x.Message.Replace("\r\n", "\n").Replace("\n", " ");
		Warning(string.Format("Failed to load provider `{0}` - {1}", ProviderName, error));
		WriteLine("");
		WriteLine("// -----------------------------------------------------------------------------------------");
		WriteLine("// Failed to load provider `{0}` - {1}", ProviderName, error);
		WriteLine("// -----------------------------------------------------------------------------------------");
		WriteLine("");
		return new Tables();
	}
````
It seems that **DbProviderFactories.GetFactory(ProviderName)** cause the exceptions like:
`"Failed to load provider MySql.Data.MySqlClient - 找不到请求的 .Net Framework Data Provider。可能没有安装。“`

I alse make sure that in `app.setting`/`web.setting`，while use nuget to install mysql.data.dll，it generate xml node like follow:
```xml
<system.data>
    <DbProviderFactories>
      <remove invariant="MySql.Data.MySqlClient" />
      <add name="MySQL Data Provider" invariant="MySql.Data.MySqlClient" description=".Net Framework Data Provider for MySQL" type="MySql.Data.MySqlClient.MySqlClientFactory, MySql.Data, Version=6.9.9.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d" />
    </DbProviderFactories>
  </system.data>
```
And if I try to use `DbProviderFactories.GetFactory` in the main function, it works well.

By the way, i install Petapoco v`5.1.179`, because of **v`5.1.187`** could not work exactly.

**Comment by LambertW** [comment]
After I restart the computer, and open the t4 project, It can work now.
But i still don't know which steps fixed it.(Restart Computer or Restart Solution or install the mysql .net connector from the mysql website).

**Comment by pleb** [comment]
Sounds like some sort of misconfiguration between DbProviderFactories and Connection strings. By installing MySQL you've probably fixed this at the machine level config. Good luck with PetaPoco now that it's working for you :smile:

**Comment by MHaendel** [comment]
Got the same issue.
