### ISSUE TITLE
Object tracking

### ISSUE THREAD

**Issue by ehsaanwelcome** [CollaboratingPlatypus/PetaPoco#307]
I have seen one of the example in documentation
var a=db.SingleOrDefault<article>("SELECT * FROM articles WHERE article_id=@0", 123);
a.content="PetaPoco was here again";
db.Update("articles", "article_id", a);

I think, It is tracking objects. Is there a way to disable tracking in order to improve performance?

**Comment by pleb** [comment]
Hi @ehsaanwelcome. PetaPoco has no object tracking ;)
