### ISSUE TITLE
Reuse EntityFramework Connection

### ISSUE THREAD

**Issue by ehsaanwelcome** [CollaboratingPlatypus/PetaPoco#308]
Is there any way to use EF connection with PetaPoco.
Actually, i want to use both EF and PetPoco thus want to use same sql connection.
Can you point out if it is in documentation as i am unable to find out? otherwise can you please add this thing as feature?
I have a plan to use PetaPoco for future Sql call but keep using EF for existing Sql calls. i hope, there will be other users who want same thing to do.

**Comment by pleb** [comment]
Yes you can. Open a connection via EF and pass it in the constructor to PetaPoco

**Comment by pleb** [comment]
@ehsaanwelcome see the docs [here](https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Ways-to-instantiate-PetaPoco#public-databaseidbconnection-connection)

**Comment by ehsaanwelcome** [comment]
worked, really appreciate your quick reply.
Thanks.
