### ISSUE TITLE
Page method doesn't work when ORDER BY column name is in square brackets e.g. [columnName]

### ISSUE THREAD

**Issue by aburok** [CollaboratingPlatypus/PetaPoco#309]
When the column name in Order By statement is wrapped with square brackets, then the Page method on Database is not working.
It throws following exception:
Column "<columnName>" is invalid in the ORDER BY clause because it is not contained in either an aggregate function or the GROUP BY clause.

**Comment by pleb** [comment]
@aburok interesting. Is the new (as in since release #.#.#) or do you think it's always been?

**Comment by aburok** [comment]
@pleb it was on version 5.1.105. But I didn't test that in newer one.

**Comment by pleb** [comment]
I'll add an integration test to confirm. It may be a few days before I get around to this.

**Comment by aburok** [comment]
Great :) thanks for quick response.
You don't have to hurry, I've found a work around but it would bo good to fix that.

**Comment by pleb** [comment]
Added integration test. Confirms this has already been fixed
