### ISSUE TITLE
Problem with tt template

### ISSUE THREAD

**Issue by Paul-Dolphin** [CollaboratingPlatypus/PetaPoco#310]
When compiling the tt template a number of errors are generated, the first of which is 
Compiling transformation: Invalid token 'this' in class, struct, or interface member declaration 
This is caused by trailing spaces in the template file, see 
[http://stackoverflow.com/questions/23281434/t4-reports-compiling-transformation-invalid-token-this-in-class-struct](url)

**Comment by pleb** [comment]
Hi @Paul-Dolphin, 

I believe I addressed this issue in commit [7de7e031052fd869acc2feddef421e5e03d238ab](https://github.com/CollaboratingPlatypus/PetaPoco/commit/7de7e031052fd869acc2feddef421e5e03d238ab).

Are you using the latest version?

**Comment by Paul-Dolphin** [comment]
I just grab the latest stable release from NuGet – the last project I created used 5.1.206 and the templates still had trailing spaces.


Paul Dolphin
AXA Technology Services, Middle Europe & Japan (MEJ)
Workplace Delivery
12, Claymoor Park
Marlow
SL7 3DL
UK
Mobile: +44 (0)7977 917774 (int: 611 7774)
Home: +44 (0)1494 523574
Email: paul.dolphin@axa-tech.com<mailto:paul.dolphin@axa-tech.com>

**Comment by pleb** [comment]
@Paul-Dolphin Sorry about that. Version 5.1.211 (the latest) does not have trailing spaces

**Comment by Paul-Dolphin** [comment]
Great, thanks

Paul Dolphin
AXA Technology Services, Middle Europe & Japan (MEJ)
Workplace Delivery
12, Claymoor Park
Marlow
SL7 3DL
UK
Mobile: +44 (0)7977 917774 (int: 611 7774)
Home: +44 (0)1494 523574
Email: paul.dolphin@axa-tech.com<mailto:paul.dolphin@axa-tech.com>
