### ISSUE TITLE
Missing XML Documentation Comments

### ISSUE THREAD

**Issue by 0ndrej** [CollaboratingPlatypus/PetaPoco#311]
PetaPoco.Core.Compiled library is completely missing XML Documentation Comments so there are no descriptions in Object Browser and IntelliSense. It is against your guidelines for contributing (_All public APIs should include XML doc comments._).

**Comment by pleb** [comment]
@0ndrej thanks for pointing it out. I've updated the nuget package to include the XML for the compiled version of PetaPoco

**Comment by hasali19** [comment]
The documentation is missing again, probably since the project moved to the new csproj format.
