### ISSUE TITLE
Adding Attributes to Columns with the T4 template

### ISSUE THREAD

**Issue by dimitritron** [CollaboratingPlatypus/PetaPoco#313]
I was wondering if it is possible to add my own attributes to the properties (columns) generated by the T4 template. 

In this particular case I want to add a [JsonIgnore]-attribute to an Id-property. This doesn't seem to be possible at the moment.

For now I just ignore th particular table and mannualy craft the POCO but that means I have to manually maintain it if the db changes. 

Not sure if this is against the whole philosophy, but it just seems like something handy.

**Comment by pleb** [comment]
It's currently not possible. You could edit the template to do it though. It wouldn't be that hard ;)

**Comment by dimitritron** [comment]
I tried a few secnarios with sublclasses and etc. but in the end I did as you suggested and edited the template. 
I don't kknow if anyone else might be interested in this, but here is how I did it:
In  PetaPoco.Core.ttinclude I edited the Column class to include an Attributes string
```
public class Column
{
    public string Name;
    public string PropertyName;
    public string PropertyType;
	public string Attributes;
    public bool IsPK;
    public bool IsNullable;
	public bool IsAutoIncrement;
	public bool Ignore;
}
```
Toward the end of PetaPoco.Generator.ttinclude I changed the template in three places to include the Attributes property like so:

```
<#
foreach(Column col in from c in tbl.Columns where !c.Ignore select c)
{
		// Column bindings
#>
<# if (TrackModifiedColumns) { #>
<# if (col.Name!=col.PropertyName) { #>
        [Column("<#=col.Name#>")] 
<# } else { #>
<# if (ExplicitColumns) { #>
        [Column] 
<# } #>
<# } #>

<#=col.Attributes ?? ""#>

		public <#=col.PropertyType #><#=CheckNullable(col)#> <#=col.PropertyName #> 
		{ 
			get
			{
				return _<#=col.PropertyName #>;
			}
			set
			{
				_<#=col.PropertyName #> = value;
				MarkColumnModified("<#=col.Name#>");
			}
		}
		<#=col.PropertyType #><#=CheckNullable(col)#> _<#=col.PropertyName #>;

<# } else { #>
<# if (col.Name!=col.PropertyName) { #>
		[Column("<#=col.Name#>")] <#=col.Attributes ?? ""#> public <#=col.PropertyType #><#=CheckNullable(col)#> <#=col.PropertyName #> { get; set; }
<# } else { #>
		<# if (ExplicitColumns) { #>[Column] <# } #> <#=col.Attributes ?? ""#> public <#=col.PropertyType #><#=CheckNullable(col)#> <#=col.PropertyName #> { get; set; }
<# } #>
<# } #>
<# } #>

```

So now you can add attributes  to any column like this (in Database.tt): 
`tables["SomeTable"]["Id"].Attributes= "[Newtonsoft.Json.JsonIgnore]";`

Note that the attribute needs to be fully qualified. Adding multiple attributes is possible simply by seperating them with a , (which of course is a .NET feature). For example: 
`tables["SomeTable"]["FullName"].Attributes= "[System.ComponentModel.DataAnnotations.Required, Newtonsoft.Json.JsonProperty(\"name\")]"`
