### ISSUE TITLE
Provider Error When Using MS Access 2010

### ISSUE THREAD

**Issue by t4thfavor** [CollaboratingPlatypus/PetaPoco#324]
I'm receiving an error when using this connection string.
Provider=Microsoft.ACE.OLEDB.12.0;Data Source=F:\Projects\FoodTracker\Foods.accdb;Persist Security Info=False;

I didn't find any doc on how to formulate the connection string, and the initialization of the DB appears to be OK, but the error is thrown when I initiate the first query to the DB. (I'm assuming that's the first time the database is connected)

Is MS Access support limited to system ODBC DSN or something similar?

Is there a different format for the connection string I should be using, or is this an issue?

My current PetaPoco version is 5.1.223

**Comment by pleb** [comment]
You can checkout the connection string we use for [integration testing](https://github.com/CollaboratingPlatypus/PetaPoco/blob/development/PetaPoco.Tests.Integration.x86/app.config)

**Comment by t4thfavor** [comment]
Changing mine to closely match yours worked along with changing runtime to x64 since I don't believe I have x86 runtimes installed. 
<add name="access" connectionString="Provider=Microsoft.ACE.OLEDB.12.0;Data Source=F:\Projects\FoodTracker\Foods.accdb" providerName="OleDb"/>

I believe it was the providerName that actually makes the difference even though the original one was a valid connection string.

Thanks,
Chance

**Comment by pleb** [comment]
@t4thfavor good to hear mate. thanks for writing back with how you went :smile:
