### ISSUE TITLE
Sql.Builder is not accepting parameters

### ISSUE THREAD

**Issue by 0ndrej** [CollaboratingPlatypus/PetaPoco#326]
I am trying to create simple query with parameters in VB.NET:
`Dim query = Sql.Builder.Select("*").From("Projects.Tasks").Append("WHERE Code LIKE @0", 13)`

But after this, query.Sql have value
```
SELECT *
FROM Projects.Tasks
WHERE Code LIKE @0
```
which means that parameter 13 was not inserted to SQL.

**Comment by pleb** [comment]
@0ndrej this is the correct behaviour. The SQL and parameters are passed to the DB Command to prevent injection based attacks. The connected DB will put the SQL and parameters together in a safe manner

More detailed information can been found by reading the[unit test] (https://github.com/CollaboratingPlatypus/PetaPoco/blob/development/PetaPoco.Tests.Unit/Core/SqlTests.cs) code.

**Comment by 0ndrej** [comment]
Then HOW i pass parameter values to query? I thought that value 13 will be inserted to @0 placeholder.

**Comment by pleb** [comment]
> The connected DB will put the SQL and parameters together in a safe manner

Suggest you read [this](https://support.microsoft.com/EN-US/kb/306636) and jump to `https://support.microsoft.com/EN-US/kb/306636`

**Comment by 0ndrej** [comment]
It works with = operator, but not with LIKE operator.

**Comment by pleb** [comment]
Can you show how you went about using the LIKE operator?

**Comment by 0ndrej** [comment]
This does not work, nothing was selected from database:
```
Dim db As New Database("ProjectManagerDevelopment")
Dim query = Sql.Builder.Select("*").From("Projects.Tasks").Append("WHERE Code LIKE '@0%'", 13)
Dim tasks = db.Query(Of Task)(query)
Dim index = 0
For Each task In tasks
  index += 1
  task.Order = index
  db.Update(task)
Next
```

This works, 6 records selected from database:
```
Dim db As New Database("ProjectManagerDevelopment")
Dim query = Sql.Builder.Select("*").From("Projects.Tasks").Append("WHERE Code LIKE '13%'")
Dim tasks = db.Query(Of Task)(query)
Dim index = 0
For Each task In tasks
  index += 1
  task.Order = index
  db.Update(task)
Next
```

**Comment by pleb** [comment]
I spotted a common mistake when using parameters. 

Change this `Append("WHERE Code LIKE '@0%'", 13)` to this `Append("WHERE Code LIKE @0", "13%")`

Parameters protect against the behaviour you're trying to execute, which is why they're consider best practice

**Comment by 0ndrej** [comment]
LOL it works this way! Thanks.

**Comment by pleb** [comment]
Yeah no worries. just remember parameters get replace by the parameter value and that value won't form valid sql. So `"@0"` value `"test"` is actually `"\"test\""`

**Comment by 0ndrej** [comment]
I have another issue with parameters.
```
Public Function SelectEmployeePermissions(Optional id As Integer? = Nothing, Optional employeeId As Integer? = Nothing, Optional permissionId As Integer? = Nothing) As IList(Of EmployeePermission) Implements IRepository.SelectEmployeePermissions
  Dim query = Sql.Builder.Select("*").From("Security.EmployeePermissions").Where("Id IS NOT NULL")
  If id.HasValue Then query.Append("AND Id = @0", id.Value)
  If employeeId.HasValue Then query.Append("AND EmployeeId = @0", employeeId.Value)
  If permissionId.HasValue Then query.Append("AND PermissionId = @0", permissionId.Value)
  Return _db.Fetch(Of EmployeePermission)(query)
End Function
```
If I call `SelectEmployeePermissions(employeeId:=1)`, resulting SQL is ```
SELECT *
FROM Security.EmployeePermissions
WHERE (Id IS NOT NULL)
AND EmployeeId = @0
``` which means, that **parameter value is not included**.

**Comment by pleb** [comment]
You don't get to see the parameter values. These are sent along with the sql to the server. The server puts it together
