### ISSUE TITLE
Publish/share Transaction to outside of PetaPoco

### ISSUE THREAD

**Issue by Kenstea** [CollaboratingPlatypus/PetaPoco#328]
I'm going to create a new functionality (BulkCopy) that will share connection/transaction with PetaPoco. However, there is no way to use the shared connection in PetaPoco. So, i'm think of publishing the property IDbTransaction from it (it is a private property). Should it be good or not? I have not made an evaluation on this but just share the idea.

**Comment by pleb** [comment]
var db = new PetaPoco();
    using(var transcation = db.GetTransaction())
    {
        var connection = db.Connection; // this is the connection
    }

**Comment by Kenstea** [comment]
Thanks pleb. Much appreciated. It appears that is a simple way if we use Database. In point of my view, I would prefer to use PetaPocoRepository rather than Database to avoid exposing too much to outside. So, I'm seeking to publish the private IDBTransaction _transaction to:

protected IDBTransaction Transaction
{
   get
    {
        return _transaction;
    }
}

**Comment by pleb** [comment]
Accessing the `IDBTransaction` would be a bad idea because of how PetaPoco controls transactions. I would recommend using the PetaPoco transaction functionality as is. Is there a specific reason why you would need reference to the `IDBTransaction` transaction instance?

Maybe this is more what you're after

    var db = new PetaPoco(); 
    db.OpenSharedConnection();
    var connection = db.Connection; // this is the connection
    using(var transaction = connection.BeginTransaction())
    {
        transaction.Commit();
    }
    db.CloseSharedConnection():

**Comment by Kenstea** [comment]
The reason is i'd want to create a method  using the public Transaction out of Database. Something like:
    var repo = PetaPocoRepository.GetInstance();
     using(var outerTransaction = repo.BeginTransaction())                 
     {
              //Do bulk copy
               var sqlCnn = (SqlConnection)repo.Connection;
                var sqlTrans = (SqlTransaction)repo.Transaction; //using a public transaction out of Database.
                using(var bulkCopy = new SqlBulkCopy(sqlCnn, SqlBulkCopyOptions.Default, sqlTrans))
                {...}
               
              // Do other stuff like insert, update here...
               outerTransaction.Complete();
So that, it may use the shared connection, transaction with upper or subsequent queries within a context. 

Your code looks pretty straightforward. However, it appears to create a nested transaction, then commit within that transaction that I'm not sure if it should be used in this situation.

**Comment by pleb** [comment]
My suggestion would be to not to use a repository for your bulk copy interaction, as using a repository here is not was a repository was built for. I think your trouble is with trying to force the repository to do something it's not designed for. Maybe create a wrapper/proxy for SqlBulkCopy and use it in combination with a PetaPoco instance. Or simply use ado.net without PetaPoco for SqlBulkCopy

**Comment by Kenstea** [comment]
Appreciated your following. You are right, Wade. I may not need to use the Repository. However, it still needs to use Transaction. So, there is something like:
```
            using (var transaction = db.GetTransaction())
            {
                var sqlCnn = (SqlConnection)db.Connection;
                // My original idea is to publish the private IDBTransaction _transaction inside Database 
               // in order to use outside of it.
               // Currently, it is private IDbTransaction _transaction. 
               // I suggest to add a readonly protected property:
              //  proctected IDbTransaction Transaction (get{return _transaction;})
               var sqlTrans = (SqlTransaction) db.Transaction; // use Transaction here. 
                var bulkCopy = new SqlBulkCopy(sqlCnn, SqlBulkCopyOptions.Default, sqlTrans);
                 //...
                transaction.Complete();
            }
```
Would it be not a bad idea?

**Comment by pleb** [comment]
@Kenstea 

if the latest beta build you can

    var transaction = ((ITransactionAccessor)db).Transaction;

**Comment by Kenstea** [comment]
You did great. Thank you Wade. I should try the latest and see.
