### ISSUE TITLE
"ErrorGeneratingOutput" when compiling Database.tt

### ISSUE THREAD

**Issue by miyagisan85** [CollaboratingPlatypus/PetaPoco#331]
In the latest version, 5.1.223, when attempting to save Database.tt, the error message "ErrorGeneratingContent" is saved to Database.cs.  I was able to install an older version (5.1.211), and have this work correctly.  I also tried the beta versions, which threw the same error.

I had a dig through your issues and can't see this as a known issue, so thought I should raise this here.

Let me know if you need any further info.

**Comment by arnorhaux** [comment]
+1   Windows 64bit, Visual studio 2015

**Comment by su8898** [comment]
+1 Win10 64bit, VS 2015. PostgresSQL

**Comment by ngbrown** [comment]
It's an errant newline at the end of `PetaPoco.Core.ttinclude`.  The file should end at the end of the `#>`, not on the next line.  Delete that and you should be good.

**Comment by pleb** [comment]
Sorry everyone. An extra line break at the end of a file seems to get included every time I accept a PR for any TT file changes. The main issue I have is that I haven't figured out a way to integration test the TT files yet, and I don't really have time to manually test each PR. 

Again. Sorry

**Comment by pleb** [comment]
@miyagisan85 @arnorhaux @su8898  @ngbrown this should be fixed in the latest release (which is building now so give it a few minutes). If you guys could try it and report whether it's been resolved or not? That would be appreciated very much :smile:

**Comment by miyagisan85** [comment]
@pleb Success!  Thanks for fixing that, it's working beautifully now.

**Comment by pleb** [comment]
@miyagisan85 Awesome!

**Comment by ramseur** [comment]
this is still broken in 4.5.2 .net

**Comment by jchurchley** [comment]
@ramseur have you tried deleting the whitespace at the end of PetaPoco.Core.ttinclude?

**Comment by cakasuma** [comment]
working!! thx
