### ISSUE TITLE
Oracle Globalization Settings

### ISSUE THREAD

**Issue by kont61** [CollaboratingPlatypus/PetaPoco#334]
While Connecting to oracle, I need to change Comparison  and Sort parameters. I changed OnConnectionOpened metod like below. And It is worked.

```
  public virtual IDbConnection OnConnectionOpened(IDbConnection conn)
        {
           // if connection type is oracle, set globalization
            if (conn is OracleConnection)
            {
                OracleGlobalization info = ((OracleConnection)conn).GetSessionInfo();
                info.DateFormat = "YYYY-MM-DD";
                info.Comparison = "LINGUISTIC";
                info.Sort = "TURKISH_AI";
                ((OracleConnection)conn).SetSessionInfo(info);
            }
            return conn;
        }
```

Is there any other way to change Comparison  and Sort parameters without any changing petapoco.cs

Thanks.

**Comment by pleb** [comment]
Hi @kont61, 

This is the correct way to do it. We've got on the roadmap `More hooks (events)` which will add other options for how you hook into PetaPoco. 

Wade
