### ISSUE TITLE
Save without primary key

### ISSUE THREAD

**Issue by mantoshelis** [CollaboratingPlatypus/PetaPoco#335]
It is possible to save objects into mysql table which does not have primary key?

**Comment by pleb** [comment]
Using the `Save` API no. Using the `Insert` and `Update` API yes

**Comment by revenz** [comment]
I just tried with an Update, and it created a where sql statement "WHERE [] = @5".  if i remove that where clause (which is invalid) it works.  Trying to update an item in a single entry table.
Code
bool success = db.Update(Model) > 0;
What am I doing wrong?
