### ISSUE TITLE
The class name created is different of database table name.

### ISSUE THREAD

**Issue by stanleyipc** [CollaboratingPlatypus/PetaPoco#342]
Hi guys,

I have inspected entire the internet searching the solution, but nothing of answers. My problem is the change of class name. I'll explain, look below:

_This is my table_
![tablename](https://cloud.githubusercontent.com/assets/20667839/18888036/11b3cf04-84cd-11e6-9f4a-3d0c7ed9084b.jpg)

When I run "Database.tt" is create this:
![classpoco](https://cloud.githubusercontent.com/assets/20667839/18888078/36ed9944-84cd-11e6-8f07-78bbdef0f7de.png)

See the name of class, the poco create a "admservicos" with "s" in the last of class name, why? How can I fix it and stay with same table name.

Other exemple:
![classpoco2](https://cloud.githubusercontent.com/assets/20667839/18888249/dee726ba-84cd-11e6-9bd6-978ee587bb93.png)

In this case the class name was changed to "admcategorium" instead of stay with "admcategoria".

English isn’t my first language, so please excuse any mistakes :)

Thanks for your attention

**Comment by pleb** [comment]
You could try

1. Edit the PetaPoco.Core.ttinclude file
2. Update the MySqlSchemaReader class (approx line 1053)
2.1 Change a line in this class `tbl.ClassName=Inflector.MakeSingular(tbl.CleanName);` to be tbl.ClassName=tbl.CleanName;`
3. The rerune the TT file

**Comment by stanleyipc** [comment]
@pleb Thanks my friend. Your reply solved the problem. :+1: 

Maybe, change the project for include a option for this.

Something like this:

_PetaPoco.Core.ttinclude file:_
![petasolu2](https://cloud.githubusercontent.com/assets/20667839/18918905/9f18962c-8572-11e6-960e-4dbeb6bcfe9b.png)
In all method "ReadSchema" a condition
![petasolu1](https://cloud.githubusercontent.com/assets/20667839/18918916/a81778b0-8572-11e6-8550-def3196ef19d.png)

So the developer can set this option.
_DataBase.tt file_
![petasolu3](https://cloud.githubusercontent.com/assets/20667839/18918960/c87fbbbc-8572-11e6-992c-7b02c0421688.png)

Just a sugest.
