### ISSUE TITLE
PetaPoco can running .net core?

### ISSUE THREAD

**Issue by xLabel** [CollaboratingPlatypus/PetaPoco#346]
.NET CORE is cross-platform Framework . Is   PetaPoco  will support this ?

**Comment by pleb** [comment]
Support for .net core would be awesome. However, it requires somebody to put the time and effort into porting it. Unfortunately, I do personally don't have the time at the moment.

**Comment by xLabel** [comment]
thx reply!

**Comment by mika76** [comment]
If it doesn't work on core then how come there is a core nuget for it?

**Comment by pleb** [comment]
There shouldn't be a nuget. Do you have a link?

**Comment by mika76** [comment]
I wrongly assumed the petapoco.core meant.net core :-)

**Comment by stanac** [comment]
there is a nuget for some .net core fork https://www.nuget.org/packages/PetaPoco.NetCore/ but readme is half-written in kanji https://github.com/qingask/PetaPoco.NetCore

**Comment by picasso566** [comment]
Has there been any progress on this? I keep thinking I would work on the templates when I had some free time, which has not happened. 

Also, Is there a port already in progress I could help with?

**Comment by agatlin** [comment]
@picasso566 Someone else already created a package for this which I have been using. https://www.nuget.org/packages/PetaPoco.NetCore/ or on gitbub at https://github.com/qingask/PetaPoco.NetCore

**Comment by soeleman** [comment]
On .NET Standard 2.0 project, we could enable support for .NETCoreApp 2.0 and .NETFramework.
The project it self on VS2017(begin VS2017.3) can have multiple targets.

The issue is on .NETCoreApp we do not have System.Configuration.ConfigurationManager, not all drivers database ready and cross-platform on some driver. Both issue will need to rethinking the we way this library configure.

Anyway, for minimum change to do it by make compile define for distinct between to .NET as fork in [github.com/soeleman/PetaPoco](https://github.com/soeleman/PetaPoco) .

should make PR on this?

**Comment by pleb** [comment]
@soeleman a PR would be great!

**Comment by soeleman** [comment]
@pleb done.
Seem the CI a bit confuse with dual solutions. thx

**Comment by pleb** [comment]
@soeleman, yeah I dare say the CI scripts will need updating. I've been meaning to switch over to Cake

**Comment by soeleman** [comment]
@pleb what do you suggest or direction on this matter?

**Comment by pleb** [comment]
@soeleman hmmmmm... 

Do we need two solution files? Could we roll with one? I guess, at a minimum, we only need to produce a .net 4.6, .net 4.7, net std 2?

**Comment by soeleman** [comment]
@pleb the idea is VS2015 still can open the solution with current setting. I will check if the VS2017 stil can open by VS2015.

**Comment by pleb** [comment]
@soeleman don't worry about 2015. Not a biggie if the only vs 2017 is supported

**Comment by soeleman** [comment]
@pleb i think the PR will took sometime to pass since we must tweak the appveyor.yml for vs2017.

**Comment by pleb** [comment]
@soeleman. yeah I think the `/tv:14.0` will need updating in the appveyor script. I'll have a play around with it soon

**Comment by soeleman** [comment]
@pleb looking forward on the script and thanks for support.

**Comment by asherber** [comment]
PetaPoco supports .NET Standard 2.0 as of v6

https://www.nuget.org/packages/PetaPoco.Compiled
