### ISSUE TITLE
How to set field as nullable?

### ISSUE THREAD

**Issue by ruant** [CollaboratingPlatypus/PetaPoco#352]
I'm having issues with setting some fields to allow null.
Maybe my google foo has withered and died because I can't find any information how to do this.

My setup is:
```
[TableName("ChangeRequest")]
[PrimaryKey("Id", autoIncrement = true)]
public class ChangeRequest
{
    [PrimaryKeyColumn(AutoIncrement = true)]
    public int Id { get; set; }

    public int What { get; set; }

    public DateTime Created { get; set; }

    public int CreatedBy { get; set; }

    public DateTime Updated { get; set; }

    public int UpdatedBy { get; set; }

    [SpecialDbType(SpecialDbTypes.NTEXT)]
    public string Data { get; set; }

    public DateTime? Rejected { get; set; }

    public int? RejectedBy { get; set; }

    public DateTime? Approved { get; set; }

    public int? ApprovedBy { get; set; }

    public int Status { get; set; }

    public bool? Hidden { get; set; }
}
```

Database created:
```
Id (PK, int, not null)
What (int, not null)
Created (datetime, not null)
CreatedBy (int, not null)
Updated (datetime, not null)
UpdatedBy (int, not null)
Date (ntext, not null)
Rejected (datetime, not null)
RejectedBy (int, not null)
Approved (datetime, not null)
ApprovedBy (int, not null)
Status (int, not null)
Hidden (bit, not null)
```

**Comment by pleb** [comment]
Setting DB column values to null is supported. There are integration tests for this. You'll need to provide more info or for a quicker answer hit up SO.

**Comment by ruant** [comment]
Ok.
I tried a few different things but I was never able to get it to create it exactly how I wanted it to be.

Since the project is being built ontop of Umbraco I ended up creating the table through the Umbraco migrations instead, that way I can handcraft the table and have a exact record of the changes as well.

Thanks for replying tho 👍

**Comment by cheeseytoastie** [comment]
For Umbraco decorate the attribute with
[NullSetting(NullSetting = NullSettings.Null)]

HTH someone else - I'm sure I've had to do Google adventures a few times for this
