### ISSUE TITLE
When I write data using multithreading, can appear the following questions.

### ISSUE THREAD

**Issue by garmiter** [CollaboratingPlatypus/PetaPoco#357]
Hello everyone.I met a problem how to solve? Is invoked when the lock?
When I write data using multithreading, can appear the following questions:
1, the connection timeout.
2, open the database connection did not shut down.
An error code is as follows:
`public int Execute(string sql, params object[] args)
        {
            try
            {
                OpenSharedConnection();
                try
                {
                    using (var cmd = CreateCommand(_sharedConnection, sql, args))
                    {
                        var retv = cmd.ExecuteNonQuery();
                        OnExecutedCommand(cmd);
                        return retv;
                    }
                }
                finally
                {
                    CloseSharedConnection();
                }
            }
            catch (Exception x)
            {
                OnException(x);
                throw;
            }
        }`

**Comment by pleb** [comment]
Make sure you're using a new instance per thread. 

Make sure you're not trying to execute an additional call while iterating a query (open reader) result. Instead, use fetch (results are fetched from the reader and reader is closed).

**Comment by garmiter** [comment]
Multiple threads at the same table writing data, before I call the method that it added a lock, no problem.

**Comment by pleb** [comment]
@garmiter you want to use an instance per thread
