### ISSUE TITLE
Business Layer in Petapoco

### ISSUE THREAD

**Issue by FabioParigi** [CollaboratingPlatypus/PetaPoco#360]
Hi Dears
I think to start develop a new web app and use Petapoco for the Data Layer and a part of Business Layer can you suggest me if there are best practice for structure Data, Business and Service Layer?

thanks a lot
Fabio

**Comment by pleb** [comment]
Hi @FabioParigi, I'm sure this has been asked a million times on the net. Maybe try SO.

**Comment by FabioParigi** [comment]
@pleb 
Thanks for your reply... I google a lot looking for best practice and support docs for create a Data layer structure based on Petapoco but I don't find nothing...
Fabio

**Comment by picasso566** [comment]
Using PetaPoco in the data layer is the same as using any other ORM tool in the data layer. If you understand any other library, such as Entity Framework, it's the same thing. Just create a DAL Project in your solution (Petapoco will need it's own connection string in that project to generate the POCOs) and run the templates. The BLL and Main project will have a dependency on the DAL project and all your POCOs are available. 

I think every ORM tool I have ever used works this way.
