### ISSUE TITLE
T4 template doesn't work if transformed using the TextTransform Utility

### ISSUE THREAD

**Issue by MhmmdAb** [CollaboratingPlatypus/PetaPoco#362]
I have a project where I would like to have the T4 template automatically regenerate on each build. The best, most hassle-free solution I could find was [Clarius.TransformOnBuild](https://www.nuget.org/packages/Clarius.TransformOnBuild/) NuGet package.

But I was unable to use it with PetaPoco because the T4 template depend on the presence of the `EndDTE.Project` objects during transformation, which is only available if the transform is done using Visual Studio, and not through the [TextTransform utility](https://msdn.microsoft.com/en-us/library/bb126245.aspx), which `Clarius.TransformOnBuild` uses under the covers.

I already have a fix that uses simple directory traversal if `EndDTE.Project` is null. But I was wondering if this is something that would be worth merging into the main repo. If it is then I would be happy to send a pull request.

By the way, thank you for PetaPoco!

**Comment by pleb** [comment]
Hi @MhmmdAb, yeah I'm not sure. Open and PR if you think it's worth it ;)

**Comment by MhmmdAb** [comment]
> Open and PR if you think it's worth it ;)

Done!
