### ISSUE TITLE
Is there a way to disable "dynamic"/"expando" types to make PetaPoco .NET 3.5 retrocompatible at compile time?

### ISSUE THREAD

**Issue by cezarlamann** [CollaboratingPlatypus/PetaPoco#363]
Hi all.

I want to use PetaPoco on a "non-upgradeable" (stakeholder restriction)  .NET 3.5 project. I won't use dynamic/expando types, so the question: Is there a way to disable "dynamic"/"expando" types to make PetaPoco .NET 3.5 compatible at compile time?

If not, which is the latest version where this kind of "workaround" is possible?

Thank you in advance.

**Comment by pleb** [comment]
I would suggest you get the single file version. Add it to the legacy project and cut out the bits which you can't use

**Comment by cezarlamann** [comment]
Ok, I'm trying to do that. I solved the tuple issue, but two things are remaining in my little "downgrading journey":

On `GetFactory(string sql, string connectionString, int firstColumn, int countColumns, IDataReader reader, IMapper defaultMapper)` method we have this code excerpt:

```
                ...
                if (Type == typeof(object))
                {
                    // var poco=new T()
                    il.Emit(OpCodes.Newobj, typeof(System.Dynamic.ExpandoObject).GetConstructor(Type.EmptyTypes)); 
                ...
                }
```

How could I change this dependency of `System.Dynamic.ExpandoObject` in this method?

Thank you in advance.

**Comment by cezarlamann** [comment]
I found in [this](https://github.com/CollaboratingPlatypus/PetaPoco/commit/cb6a8258c69fb82a5141193a75d3cf0705dd97f3) commit, where the code I asked about is circled with `#if !PETAPOCO_NO_DYNAMIC`. If I remove this "if" member, will PetaPoco still capable of working with typed (non-dynamic) properties even if they are non-primitive types?
