### ISSUE TITLE
Is Medium Trust Fully Supported?

### ISSUE THREAD

**Issue by mikemike396** [CollaboratingPlatypus/PetaPoco#364]
I see this PR (https://github.com/CollaboratingPlatypus/PetaPoco/pull/149). That was 1 year ago. Does the library currently run in medium trust? We are looking to move from EntityFramework in our shared sever that is medium trust forced. 

Thanks

**Comment by pleb** [comment]
Hi @mikemike396, No, sorry medium trust is not supported.
