### ISSUE TITLE
Operation could destabilize the runtime

### ISSUE THREAD

**Issue by Feijo** [CollaboratingPlatypus/PetaPoco#367]
I am trying to use Petapoco's multi-poco query with PostgreSQL.

The code works fine on my local machine running .NET 4.6.1 but throws System.Security.VerificationException when deployed to the hosting I am using which is running .NET 4.5.

```
public Person MapRow(Person person, Category category, Country country) {
    return person; // Not mapping nothing for the sake of the argument
}
```

```
db.Query<Person>(
   new[] { typeof(Person), typeof(Category), typeof(Country) },
   new PersonRelator().MapRow, // Method above
   sql
);
```

Exception is being thrown at [Database.cs:2253](https://github.com/CollaboratingPlatypus/PetaPoco/blob/development/PetaPoco/Database.cs)

Originally posted [here](http://stackoverflow.com/questions/41735678/petapoco-operation-could-destabilize-the-runtime).

**Comment by pleb** [comment]
Is the hosting environment set to medium trust?
