### ISSUE TITLE
Can't query multiple joins to the same type

### ISSUE THREAD

**Issue by arielcon** [CollaboratingPlatypus/PetaPoco#369]
I have exactly this problem: (http://stackoverflow.com/questions/11416019/multiple-joins-to-the-same-type-in-petapoco)

Bug seems to be here : [MultiPocoFactory.cs line 53](https://github.com/CollaboratingPlatypus/PetaPoco/blob/23a34d49b0c0ab74d04286174d8da9a1e1dc26b1/PetaPoco/Core/MultiPocoFactory.cs#L53)

As the code says, feature it's not supported yet. Any suggestion or workaround ?
Thanks

**Comment by pleb** [comment]
@arielcon sorry. I'm not too sure of the inner works on MultiPoco. I don't use it myself and haven't had to dive in deep from a dev perspective.
