### ISSUE TITLE
Incorrect internal on ExecuteScalarHelper(IDbCommand cmd) for Custom DatabaseProvider's external to source

### ISSUE THREAD

**Issue by matthewsheeran** [CollaboratingPlatypus/PetaPoco#373]
What is the chance of getting the "internal" scope of ExecuteScalarHelper(IDbCommand cmd) changed to a "public" for re-use by a Custom DatabaseProvider's (I just copied and renamed SqlServerDatabaseProvider as a template to start) using the PetaPoco.Core.Compiled binary rather than of PetaPoco.Core PetaPoco.cs source.

I think it would be nice to be able to have and use Custom DatabaseProvider's against the external dll without needing to include and compile and link against the source internally to get around the internal(s) or am I asking too much of this?  Since I am sure that there are potentially many other internal members that may be used by a DatabaseProvider.  An alternative might be "protected virtual" since I inherit my DbLayer from Database I might be able to do a cast and call an override wrapper member that then calls the base to get at what I want but "internal" here is definatively a no go..

I know one can do it with reflection but that both yucky and slow (in both coding as well as in use) so I guess I will have just have to go back to compiling the source anyway for now..

Regards,
Matthew

BTW: if you let me in I will both fix it and contribute.

**Comment by pleb** [comment]
Are you extending? Happy for those internals to become protected virtual

**Comment by matthewsheeran** [comment]
Extending with a custom ODBC Provider is the idea though I can't quite make up my mind whether to subclass or not but that is a requirement for the above.  

When SqlServerDatabaseProvider as my template for  SQL Server overr ODBC - or as is more likely another database like Postgres - doesn't work I will get back to it.  The only other Db right now is SQLite (actually SpatiaLite) using System.Data.SQLite.  

I and no one else will ever bother with ODBC for this one though it might be a good choce for debugging my new ODBC Provider and PetaPoco which will need switches or a table of Delegates for all of the different "DataSourceProductName" values from GetSchema "DataSourceInformation" that I have already as the source for use in deteremining which database you are actually talking to over ODBC.

I like ODBC and some Geospatial data software platforms use it and DSNs particularly FILEDSNs along with the ODBC Data Source Administrator (ODSA) x84 and x64 make establishing connections to databases much easier e.g. I tried to copy a SQL Server FILE DSN today for PostgreSQL then went to try in it ODSA and bobs your uncle! Try to do that with a regular connection string or heaven forbid JDBC.

I suspect Native Client perfomance has been overrated compared to ODBC too: remember before there were Native Clients there was really only ODBC (with the possible exception of Oracle).  And what do you have on Linux and *nix!? Again ODBC mostly as far as I am aware. Microsoft have deprecated OLEDB and gone back to recommending ODBC so its alreday been there and is most definately here to stay for a very long time indeed absent NoSQL and RESTful access including to a convetional DBMS e.g. Postgres HSTORE store but note what this highly efficient JSON enabled Key-Value in SQL has agian under its hood: nothing but ODBC baby all the way: tried tested performant and true.

So I hope I have convinced you how useful and important it would be to have an Universal ODBC Provider for PetaPoco!
Regards.
