### ISSUE TITLE
group by sqlcount

### ISSUE THREAD

**Issue by zhuangke** [CollaboratingPlatypus/PetaPoco#377]
`Sql sql = new Sql("select IndexArr,Days,Max(CreatedDate) as CreatedDate from CombineIndexStatistics(nolock)");

 sql.GroupBy("IndexArr", "Days");
sql.OrderBy("Max(CreatedDate) desc");

var pageList = BigData_PetaPOCO.GetInstance().Page<CombineIndexStatistic>(pageIndex, 100, sql);`

The SqlCount is 
`select COUNT(*) from CombineIndexStatistics(nolock) GROUP BY IndexArr, Days`

but it's wrong
I want to get 
`select count(1) from (select COUNT(*) as t from CombineIndexStatistics(nolock) GROUP BY IndexArr, Days)tt`

**Comment by pleb** [comment]
The logic to turn a select into a count query doesn't always get it right. My advice would be to use one of the overloads which allows you to pass the count query in.

`Page<T> Page<T>(long page, long itemsPerPage, string sqlCount, object[] countArgs, string sqlPage, object[] pageArgs);`

or 

`Page<T> Page<T>(long page, long itemsPerPage, Sql sqlCount, Sql sqlPage);`
