### ISSUE TITLE
Any tips on how to go about changing @0.. Parameters to ? for ODBC support

### ISSUE THREAD

**Issue by matthewsheeran** [CollaboratingPlatypus/PetaPoco#378]
Any tips on how to go about changing @0.. Parameters to ? for ODBC support.
I doubt however that the requisite members are public so will have to hack my PetaPoco.cs.
I have just hacked my Exists and have to do the same and replace Update and Insert with ExecuteUpdate and ExecuteInserts with custom coded and pre string formatted where clauses or in this case update and insert queries.

Fortunately I only have a few table datatypes to worry about as my application is mostly for generic spatial data table access hence the need and desireability for ODBC support as most or at least many GIS Desktop Applications use ODBC.. typically there are many different databases to connect to through DSNs rather than hard coded app.config or other connection strings.

PetaPoco was the most suitable and flexible in this regard for me.

Presumably if the Parameter processing can be generified the custom replacement routines could then be provider through the custom ODBC and DatabaseProvider Interface..

Any thoughts ideas suggestions!?

Regards,
Matthew

**Comment by pleb** [comment]
@matthewsheeran off the top of my head, the easiest way would be to roll your own `DatabaseProvider`. You would then need to override `GetParameterPrefix(string connectionString)` and simply return `return "?";`

**Comment by matthewsheeran** [comment]
Ok I will definatlet look into it shortly as I definately need to progress this one over the medium term.
For now: for my one and only first data table type class I am juts adding UpdateSql and InsertSql in addiiton to my CreateTableSql for the tabelname and data table type class using Execute(..Sql(tablename)) then I will be looking into this further..

PetaPoco was the only micro-ORM that even remotely filled my needs for flexibility and I will be sticking with it and pursuing it.  Down the track when my Application is up and running I will be able to test it along with my PetaPoco changes against multiple ODBC Databases which should prove useful in delivering the said PetaPoco ODBC (Multi-) Database Provider with unit tests and testability back into the PetaPoco code base proper so just keep those tips coming pleb..

(I have a bunch of GetSchema MetaDataCollections related code for this already and using this stuff for Database Metadata the ODBC DatabaseProvider then becomes a multi or meta driver for Databases and will need more code probably than all the exisitng builtin PetaPoco DatabaseProviders put together..
Theer is a lot in all of this as you well know and why I started with your codebase which I am finding very useful to be able to look at. Thankyou.)

Many thanks in advance..

**Comment by matthewsheeran** [comment]
Baby steps OK:
1. Did the:
  "@"s => "?"s
2 . Then found EnableNamedParams which when set to false changes the:
  "@name"s.. => "?0".."?n"s
Now I need to get rid of the numbers since ODBC only accepts ?'s plus parameters in order though I am guessing and hoping that the correct ordering is likely to be the case in most of the PetaPoco code anyway.
3. It looks like from searches for matches like:
  using (var cmd = CreateCommand(_sharedConnection, ""))
That I might only need to change and drop the index++ from:
  sb.AppendFormat(i.Value.UpdateTemplate ?? "{0} = {1}{2}", _provider.EscapeSqlIdentifier(i.Key), _paramPrefix, index++);
For:
  ExecuteUpdate
ExecuteInsert
And perhaps in one or two other places..
That should be easy and straight forward: we will find out!...

**Comment by matthewsheeran** [comment]
I have it working for ODBC "?" but have issues with using a TEXT - the WHERE PKName=PKValue doesnt wok with SQL Server - or actually a VARCHAR(n) PK column with Save() which should then be PKName='PKValue' as I have working in my own code from when I hit the "@name"|"@0.." vs "?" ODBC difference.  I have to look further and confirm..
0. I could use INT ID columns and existing Save() but prefer not and to modify Save() aside from this choice I have several others:
1. Keep my breaking changes in PetaPoco.cs.
2: Subclass everything from PetaPoco:: PetaPoco.cs in say a PetaPoco2:: PetaPoco2.cs or ODBCPetaPoco.
3. An experimental OBDC fork in your Master PetaPoco Tree.
4. Do 3 with NPoco.
5. Do 4 with AsyncPoco.
I can incorporate individual source files and changes into a project here rather than the combined PetaPocoX.cs sources above then I can run your unit tests before committing.
Let me know how you wish to proceed as I have, and there are, a lot of options above and now is the time to put this into place - as this is but one very small component but very important dependency of a very much larger project I am building here!?  I will inevitably move onto these other things and will not be back for years I am sure as once this is working with my DbLayer wrapper layer as I will have no reason to return or revisit the PetaPoco.cs changes for the forseeable future.
So if you want this you had better get it now: I am sure as a developer you understand what I mean pleb and I am sure you area across many projects as much as I am across many components even on the one!?
I.E. If I don't do 3, 4 or 5 NOW then my code will inevitabley fork away from PetaPoco and into my own code base (just like Umbraco which is where I came here from) whether I use a single source file or not..
I too am equally happy to maintain my own code for the identical reason of not having to deal with other developers potentially breaking changes so a decision needs to be made and the offer above accpeted or rejected.
Kindest Regards,
Matthew

**Comment by matthewsheeran** [comment]
I verified and fixed the singles quotes around PK string values so the above is accurate. Exists doesn't work but my replacement does.  But what puzzles me are dynamic Fetch() and Update() which works just fine but Insert() throws a custom Exception of unsupported: when I can't see why if you can Update() that you shouldn't also be able to Insert() ExpandoObjects too?
I guess I have dig deep enough to starting finding the warts but I do like my own Save() that queries the database with my Exists() and decide upon an Insert() or Update() for VARCHAR PKs with no IDENTITY INT ID PK required :-)
So I just wish it would work with dynamics after all of the above and going to the trouble of testing the latter whilst I was at it also before moving on..

**Comment by matthewsheeran** [comment]
I have it done tested now for SqlServer and ODBC connections to same using a new EnableNumberedParams = true (default) along with the original EnableNamedParams = true (default) (along with the two tweaks in ExecuteUpdate for:
if (primaryKeyValue.GetType() != typeof(string))
            use "UPDATE {0} SET {1} WHERE {2} = {3}{4}" 
            else "UPDATE {0} SET {1} WHERE {2} = '{3}{4}'"
I just have to explicitly set them both to false for now after every ODBC Database instantiation:
            if (this.Db.Provider.GetType() == typeof(OdbcDatabaseProvider))
            {
                this.Db.EnableNumberedParams = this.Db.EnableNamedParams = false;
            }
Let me know if you would like the code: at a minimum I can send you the New PetaPoco.ODBC.cs along with the original PetaPoco.original.cs to diff all the changes that are also prefixed with //MJS.
You would be welcome to them. :-)
Regards,
MJS

**Comment by matthewsheeran** [comment]
I'll leave you to close the ticket pleb/Wade as the good news is that my task is done for now: if had chosen any other micro ORM or indeed ORM platform I have no absolutely doubt whatsoever that I would indeed still be working on it!
Cheers,
Matthew
