### ISSUE TITLE
PetaPoco no longer recognizes class attributes.

### ISSUE THREAD

**Issue by cacciatc** [CollaboratingPlatypus/PetaPoco#381]
Specifically the table name. This was formerly working with the same code, so perhaps it is a configuration issue? I have multiple projects in a solution which all use PetaPoco.

Here is an example of the one of the classes, but PetaPoco still uses **RelevanceScore** as the table name.
```
    [PetaPoco.PrimaryKey("Id")]
    [PetaPoco.TableName("fb.relevance_scores")]
    public class RelevanceScore
    {
        public long Id { get; set; }

        [JsonProperty("score")]
        public int Score { get; set; }

        [JsonProperty("positive_feedback")]
        public string PositiveFeedback { get; set; }

        [JsonProperty("negative_feedback")]
        public string NegativeFeedback { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        /// <summary>
        /// Created timestamp.
        /// </summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Updated timestamp.
        /// </summary>
        public DateTime UpdatedAt { get; set; }
    }
```

**Comment by cacciatc** [comment]
I do believe that is is due to having multiple projects all using PetaPoco in the same solution ala:
http://stackoverflow.com/questions/11510703/unable-to-get-attributes-back-from-getcustomattributes

If I includes the files from the various projects into just one project, then the following finds the correct attribute:
https://github.com/CollaboratingPlatypus/PetaPoco/blob/23a34d49b0c0ab74d04286174d8da9a1e1dc26b1/PetaPoco/Core/ConventionMapper.cs#L109

**Comment by pleb** [comment]
Maybe `Complied` would suit you better - https://www.nuget.org/packages/PetaPoco.Core.Compiled

If you're using the T4 templates, you could make a copy of them, delete the single file PP, and use the compiled
