### ISSUE TITLE
Using PetaPoco for logging

### ISSUE THREAD

**Issue by QuAzI** [CollaboratingPlatypus/PetaPoco#384]
I use PetaPoco for write logs into database.

```
[PetaPoco.PrimaryKey("id")]
public class LogTasks
{
    public int id { get; set; }
    public int task_id { get; set; }
    public LogEntry.MessageCostEnum level { get; set; }
    public DateTime datetime { get; set; }
    public string message { get; set; }
}

Db.Insert(logItem);
```
Sometimes MySQL raise exception
`Authentication to host '127.0.0.1' for user 'root' using method 'mysql_native_password' failed with message: Reading from the stream has failed.`

![2017-04-16_19-58-32_f1ah7mbh](https://cloud.githubusercontent.com/assets/1897605/25073259/819b26d4-22eb-11e7-9403-019ae7c70ec9.png)

Now I try to optimise logging. How can I prevent `SELECT @@IDENTITY AS NewID;` after any insert and how can I use INSERT DELAYED ? Or maybe other optimisations can be used?

**Comment by pleb** [comment]
1) MySQL connection bug

That looks to be related to the MySQL ado component and not PP. I would suggest seeing if this bug is reported, fixed, or etc.

2) Insert `SELECT @@IDENTITY`

If you don't ever query for this entity, simply drop the PrimaryKey and PetaPoco will behave as you want it to. 

Otherwise, you could try a two entity approach

```
[PetaPoco.PrimaryKey("id")]
public class LogTasks
{
    public int id { get; set; }
    public int task_id { get; set; }
    public LogEntry.MessageCostEnum level { get; set; }
    public DateTime datetime { get; set; }
    public string message { get; set; }
}

public class FastLogTasks
{
    public int task_id { get; set; }
    public LogEntry.MessageCostEnum level { get; set; }
    public DateTime datetime { get; set; }
    public string message { get; set; }
}

Db.Insert(fastLogItem);

var log = Db.Single<LogTasks>(1 /* some log id */);
```
