### ISSUE TITLE
Use PetaPoco with HTTP tunnel

### ISSUE THREAD

**Issue by QuAzI** [CollaboratingPlatypus/PetaPoco#385]
In some projects we use HTTP tunnel (PHP script) to use DB in LAMP.
Is any workaround exist for use PetaPoco in this case? Custom database provider sample exist or maybe we can take prepared SQL query without execution for use later like in next sample
```cs
string query = db.GetPreparedQuery().Save(rec)
httpTunnel.Send(query);
```

**Comment by pleb** [comment]
@QuAzI I can't really help you with this. Maybe try SO
