### ISSUE TITLE
petapoco is making hops of the id in insert.

### ISSUE THREAD

**Issue by lucho07** [CollaboratingPlatypus/PetaPoco#389]
have you fixed the bug when inserting with autonumeric identities?? In some random cases petapoco is making hops of the id.
for example... from id 99 to 1001
The version i use is 5.0.1.

My code:

public bool Agregar(bancos o)
        {
            try
            {
                o.activo = true;
                o.ts = DateTime.Now;
                _oDb.Insert("bancos", "id", true, o);
                return o.id != 0;
            }
            catch (Exception ex)
            {
                ex.EscribirLog(_empresa);
                throw;
            }
        }

![id](https://cloud.githubusercontent.com/assets/6563648/25809623/f2b9329e-33e3-11e7-8351-258f57b494d3.JPG)

**Comment by pleb** [comment]
@lucho07 this is not an issue with PetaPoco. It's an issue with the DB server. See http://stackoverflow.com/questions/14146148/identity-increment-is-jumping-in-sql-server-database

FYI, if you google around, there's a way to disable it.
