### ISSUE TITLE
Feature suggestion: multiple result set support

### ISSUE THREAD

**Issue by litera** [CollaboratingPlatypus/PetaPoco#39]
> *I'm sorry if I write feature suggestion as an issue but I don't know of a better place to post a suggestion.*

It would be nice for PetaPoco to support multi result-set queries (at least in terms of stored procedures). This is the best way to avoid the **N+1** problem. Related properties (as One- or Multi- relations) could as well be automatically resolved either by using some sort of *relator* lambda expressions or POCO attributes. The latter being favoured so we don't have to repeat our code every time we'd like to auto-relate entities.

**Comment by pleb** [comment]
Closing as @LankyPaddy has added this feature
