### ISSUE TITLE
Strongname Assembly

### ISSUE THREAD

**Issue by rufio620** [CollaboratingPlatypus/PetaPoco#393]
Is it possible to release the assembly strong named? Thanks.

**Comment by pleb** [comment]
Maybe in the future, but not at the moment. You try https://github.com/brutaldev/StrongNameSigner

**Comment by rufio620** [comment]
Attempted it something is broken in the build integration. Basically the tool does not work for projects with more than a couple assemblies for some reason. [Strong Name Signer Issue 27](https://github.com/brutaldev/StrongNameSigner/issues/27)

**Comment by pleb** [comment]
You could also try https://www.nuget.org/packages/Nivot.StrongNaming

**Comment by rufio620** [comment]
I was able to get the strong name signer to work by integrating a custom script action. 

Just curios is there a specific reason you have not strong named this assembly or is it just a time issue?
