### ISSUE TITLE
Query error in Database.Single with EnableAutoSelect = False

### ISSUE THREAD

**Issue by MohanVijayakumar** [CollaboratingPlatypus/PetaPoco#400]
It Seems when call the DB.Single<T>(primarykey)  with  EnableAutoSelect = false Petapoco only Generates Where Part.

**Comment by pleb** [comment]
@MohanVijayakumar what do you think the behaviour should be under this situation? Throw?

**Comment by MohanVijayakumar** [comment]
It would be great if it generates the full query
The same issue found in the petapoco fork of Npoco also
[https://github.com/schotime/NPoco/issues/183](url)
