### ISSUE TITLE
Querying LINQ Style - Update Wiki

### ISSUE THREAD

**Issue by DEllingsworth** [CollaboratingPlatypus/PetaPoco#402]
All the examples show a one based parameter 
`result = db.Exist<Person>("WHERE Id = @1", 12); // Same as above True or False`

Should be:
`result = db.Exist<Person>("WHERE Id = @0", 12); // Same as above True or False`

**Comment by pleb** [comment]
Thanks @DEllingsworth. I've fixed the docs.
