### ISSUE TITLE
SQLite not working

### ISSUE THREAD

**Issue by david-ju** [CollaboratingPlatypus/PetaPoco#416]
I can't get petapoco to work with SQLite. 
I've added the SQLite NuGet package: https://www.nuget.org/packages/System.Data.SQLite/
I've added the DBProviderFactory in my app.config:
`<system.data>
	<DbProviderFactories>
		<add name="SQLite Data Provider" invariant="System.Data.SQLite" description="Data Provider for SQLite" type="System.Data.SQLite.SQLiteFactory, System.Data.SQLite" />
	</DbProviderFactories>
</system.data>`
I've added my connection string:
`<add name="SomeSQLiteDatabase" providerName="System.Data.SQLite" connectionString="Data Source=C:\Temp\database.db;Version=3;" />`
And all I get in my database.cs is:
`Failed to load provider `System.Data.SQLite` - Exception has been thrown by the target of an invocation.`
I've tried adding System.Data.SQLite to the gac, adding the DBProviderFactory to my machine.config, still no joy.
Connecting to an SQLite database shouldn't be this hard. Or am I missing something?

Ok I've resolved this by installing the Visual Studio 2015 package available for download here: https://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki

New error: Failed to read database schema - SQL logic error or missing database no such table: INFORMATION_SCHEMA.TABLES
Looks like the generator is in Sql Server mode, I don't see any code specific for SQLite:
`if (_factory.GetType().Name == "MySqlClientFactory")
{
	// MySql
	reader=new MySqlSchemaReader();
}
else if (_factory.GetType().Name == "SqlCeProviderFactory")
{
	// SQL CE
	reader=new SqlServerCeSchemaReader();
}
else if (_factory.GetType().Name == "NpgsqlFactory")
{
	// PostgreSQL
	reader=new PostGreSqlSchemaReader();
}
else if (_factory.GetType().Name == "OracleClientFactory")
{
	// Oracle
	reader=new OracleSchemaReader();
}
else
{
	// Assume SQL Server
	reader=new SqlServerSchemaReader();
}`

**Comment by asherber** [comment]
I'm using PetaPoco with `System.Data.SQLite`, no problems. 

It looks like the T4 templates only work with certain providers, and SQLite is not one of them. I wrote my model classes by hand and create the `Database` object myself.
