### ISSUE TITLE
Errors after install with NuGet

### ISSUE THREAD

**Issue by TheTrigger** [CollaboratingPlatypus/PetaPoco#420]
I just installed PetaPoco for the first time via NuGet, but there are some errors..

Empty Windows console project, net 4.6.1

![image](https://user-images.githubusercontent.com/6072718/31795204-369afb92-b525-11e7-9ff0-020c152eed29.png)

Models\Generated\PetaPoco.Core.ttinclude

**Comment by TheTrigger** [comment]
Found the problem, there are \r\n at the end of PetaPoco.Core.ttinclude file, after #>

**Comment by larsbuch** [comment]
Version 5.1.259 has the same error as the older version. A simple unit test could be to read the file from the end to see characters after "#>" and fail if there are some. A T4 syntax validator would be the best but is also a large task.

**Comment by kymowang** [comment]
I want to to say something but nothing. It took me over one hour to search the issue. JUST ONE LINE!

**Comment by pleb** [comment]
Does anyone want to submit a PR with a test to ensure this doesn't happen again?

**Comment by pleb** [comment]
Fixed. Sorry, I've never found a way to unit/integration test the templates
