### ISSUE TITLE
Feature request - IgnoreOnInsert and IgnoreOnUpdate properties

### ISSUE THREAD

**Issue by Andrei-** [CollaboratingPlatypus/PetaPoco#421]
I often have the scenario where I have a table column like CreatedDate or UniqueGuid column which should be handled by the database only. So basically I never want to touch those columns when inserting or updating pocos, but I want the values when I query.
I couldn't solve this nicely with ResultColumn or Ignore attributes as they will not load the column. If there is an elegant solution and I missed the obvious, I would love to hear it..

What I ended up doing was having two classes for each table. For example on entities that need a CreatedDate, I have a class without that property for inserting and updating and a second class with that property for querying. The second class is just inheriting the first and adds the CreatedDate property.
Any chance of having these attributes added into Petapoco?

**Comment by asherber** [comment]
The docs are a little misleading wrt `ResultColumn`. They say:

> ResultColumn is an attribute which can decorate a Poco property as a result only column. A result only column is a column that is only populated in queries and is not used for updates or inserts operations.

The important thing that's missing here is that a `ResultColumn` is **not included in auto-generated SQL**. So if you do `var records = db.Fetch<MyClass>("")`, result columns will not be populated. But if you do `var records = db.Fetch<MyClass>("select * from myclass")`, result columns will be populated. 

NPoco adds a third attribute, `ComputedColumn`, which is kind of nice. Like `ResultColumn`, a computed column won't be included in an insert or update, but unlike `ResultColumn` it will be included in an auto-generated SELECT statement.

**Comment by Andrei-** [comment]
Coming from Petapoco, I didn't notice the new ComputedColumn feature. When researching npoco, I read that it adds a bunch of extra features, but could never find a detailed list of exactly what new features npoco adds over Petapoco. 
ComputedColumn seems to be the answer to my problem, so thanks a lot, I really appreciate you took the time to answer here.

**Comment by iadaz** [comment]
Could I request that at least the wiki is updated with Andrei's comment "ResultColumn is not included in auto-generated SQL". This tripped me up.

I worked around this by extending the ResultColumn attribute with an IncludeInAutoSelect flag as suggested here: https://stackoverflow.com/a/9939919/1499294

Ultimately this ends up modifying the QueryColumns collection in PocoData():

` QueryColumns = (from c in Columns where !c.Value.ResultColumn || c.Value.IncludeInAutoSelect select c.Key).ToArray();`

**Comment by pleb** [comment]
@iadaz I've sent an invite for collaboration. Feel free to accept and update the wiki if you like 😄

**Comment by iadaz** [comment]
Wiki updated.

What do we think about adding this IncludeInAutoSelect property via the ResultColumn attribute? I could put a PR for it. I am not sure my code pattern would be to everyone's liking. I added this overload to the ResultColumnAttribute ctor:

```
    [AttributeUsage(AttributeTargets.Property)]
    public class ResultColumnAttribute : ColumnAttribute
    {
        public bool IncludeColumnInAutoSelect;

        public ResultColumnAttribute() { }
        public ResultColumnAttribute(string name) : base(name) { }

        public ResultColumnAttribute(bool IncludeInAutoSelect) {
            IncludeColumnInAutoSelect=IncludeInAutoSelect;
        }
    }

```

I guess it probably ought to allow you to specify the name at the same time?

**Comment by Andrei-** [comment]
@iadaz If you use npoco (a more evolved version of petapoco), there is a ComputedColumn attribute and that one will include the column in auto selects. If I correctly remember.

**Comment by iadaz** [comment]
@Andrei- I will consider it but I think it would be the right thing to do to offer this improvement to the PetaPoco community. Perhaps they Npoco implementation should be the model though?

**Comment by asherber** [comment]
I don't think it's at all clear from the attribute names what the difference is between Result and Computed. So I would vote for a parameter on `ResultColumn`, as proposed. To allow the user to specify both Include and a name, maybe something like this:

```csharp
[AttributeUsage(AttributeTargets.Property)]
public class ResultColumnAttribute : ColumnAttribute
{
    public bool IncludeInAutoSelect { get; set; };
    
    public ResultColumnAttribute() { }
    
    public ResultColumnAttribute(bool includeInAutoSelect) : this(name:null, includeInAutoSelect) { }
    public ResultColumnAttribute(string name) : this(name, includeInAutoSelect:false) { }

    public ResultColumnAttribute(string name, bool includeInAutoSelect) : base(name) 
    {
        IncludeInAutoSelect = includeInAutoSelect;
    }
}
```

I'm also not crazy about the fact that if I do something like `[ResultColumn(false)]`, it's not clear from the code what that boolean does, without using Intellisense. So this could also be done using an enum instead of a bool (`IncludeInAutoSelect.No, IncludeInAutoSelect.Yes`), but then that starts looking a little fussy.

**Comment by pleb** [comment]
I'm happy with what the community decides. @iadaz more than happy for a PR ;) 

Additionally, if you feel the desire to add more documentation to the wiki..... go for it.

**Comment by asherber** [comment]
@iadaz Do you have time for this PR? Otherwise I will put it together.

**Comment by iadaz** [comment]
@asherber I might have time to do it next week but this week's a killer. I don't mind if you want to go for it.

**Comment by pleb** [comment]
I think I got the CI issue sorted. Fingers crossed
