### ISSUE TITLE
PetaPoco.Core.ttinclude not working

### ISSUE THREAD

**Issue by Paul-Dolphin** [CollaboratingPlatypus/PetaPoco#424]
An additional space line has appeared again on the end of petapoco.core.ttinclude which stops the T4 generator from working

**Comment by swhitf** [comment]
Wow this just saved me a lot of pain. I have the same issue that is resolved when removing the last white space line.

**Comment by pleb** [comment]
Fixed. Sorry, I never found a way to unit/integration test the templates.
