### ISSUE TITLE
can't Execute(List<PetaPoco.Sql>)

### ISSUE THREAD

**Issue by qxwei** [CollaboratingPlatypus/PetaPoco#427]
can't Execute(List<PetaPoco.Sql>)
PetaPoco suppoet this ?

**Comment by picasso566** [comment]
I'm sorry, but can you phrase the question a little better?

You need to use PetaPoco like the documentation says. 

If you have an object like:

public class potato {
  string name {get; set;}
  int age {get;set;}
}

You can use PetaPoco like this:
int potatoType = 2;
var potatoes = List<potato>("FROM potato WHERE type = @0", potatoType );

**Comment by qxwei** [comment]
I see demo below,but I can make it pass,the demo is wrong?have the function Execute(List<PetaPoco.Sql>) :
`IList<Sql> sqls = new List<Sql>();  
     
   foreach(string name in names)  
   {  
     sqls.Add(Sql.Builder.Append(" insert  into student (name,address,age)values (@name,@address,@age)", name,address,age))  
   }  
     
   int affectCount = Database.Execute(sqls);  `

**Comment by pleb** [comment]
> can't Execute(List<PetaPoco.Sql>)

Yes, that's right. It can't. You would loop and execute each statement individually. There are likely better ways to do it, however, that's better asked on SO or via Google/Bing

> Sql.Builder.Append(" insert into student (name,address,age)values (@name,@address,@Age)", name,address,age)

That doesn't look right. This unit test shows you how.

        [Fact]
        public void Append_GivenNameArguments_ShouldBeValid()
        {
            _sql.Append("arg @name @password", new { name = "n", password = "p" });

            _sql.SQL.ShouldBe("arg @0 @1");
            _sql.Arguments.Length.ShouldBe(2);
            _sql.Arguments[0].ShouldBe("n");
            _sql.Arguments[1].ShouldBe("p");
        }
