### ISSUE TITLE
Pagination with distinct

### ISSUE THREAD

**Issue by diegodfsd** [CollaboratingPlatypus/PetaPoco#435]
I'm using the latest version 5.1.283 and when I trying to execute a query like that 
`SELECT DISTINCT Id, Name, Email
  FROM [schema].[table]`
the things not happen like expected because PetaPoco engine generate a query like that:
`SELECT COUNT(DISTINCT Id, Name, Email) 
   FROM [schema].[table]`

I have already a solution to this problem and I'm using PetaPoco with this fix at this moment.

**Comment by asherber** [comment]
Can you please provide more information? What kind of database? Can you post a code snippet? What was your fix?

**Comment by diegodfsd** [comment]
Hi @asherber ,

I'm using sql server 2014. About the problem, when I trying to execute any query with distinct and multiples columns an exception is thrown. I have no more details because the problem happened more than 8 months ago, but as I told before I have a solution and I can create a PR. What do you think?

**Comment by asherber** [comment]
Sure, thanks, a PR would be helpful.
