### ISSUE TITLE
.net core compiler can't find PetaPoco namespace.

### ISSUE THREAD

**Issue by dcworldwide** [CollaboratingPlatypus/PetaPoco#436]
I've created a fresh asp.net mvc project (framework netcoreapp2.0). 

Added petapoco.

dotnet add package PetaPoco.Core --version 5.1.283
dotnet restore

Tried importing using either:

using PetaPoco; or;
using PetaPoco.core;

But dotnet build fails. 

error CS0246: The type or namespace name 'PetaPoco' could not be found (are you missing a using directive or an assembly reference?)

What am I doing wrong?

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
    <PackageReference Include="PetaPoco.Core" Version="5.1.283" />  
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>

</Project>

```

**Comment by pleb** [comment]
PetaPoco.Core came before dotnet core. The two are not related. 

There is no official dotnet core version of PetaPoco. 

There is, however, PR #432. But, I haven't had time to look at it yet. I'm fairly busy untill mid-year at this stage.
