### ISSUE TITLE
Missing constructor Database(IDbConnnection connection, IMapper mapper)

### ISSUE THREAD

**Issue by millimoose** [CollaboratingPlatypus/PetaPoco#439]
I want to use PetaPoco in a largeish existing codebase that does wrangles its own persistent connection to Postgres. Our app connects to a database server with one main schema per tenant - which schema this is may change while the app is still running. Some of the model types I intend to create may be found in more than one schema, so I don't want to just hard-code the schema name in the table name. I want to prepend the current schema name to the table name during mapping, and it seems like inflection should be able to handle this. Since I want to do this for (almost) all mapped tables, it seems like the default mapper is the place to do so.

Unfortunately the `Database` constructors that let me specify a default mapper are the ones that involve a connection string, which is not applicable for this app. Is there a particular reason why this combination isn't supported, or is it just a case of "time better spend implementing features useful to more people"?

**Comment by pleb** [comment]
Sorry, I forgot the tag the commit. Please see a93f99dd90e3478c619f9d2042834547cfeaf309

You can try it out in the dev nuget packages

**Comment by millimoose** [comment]
Thanks! I'm using the file include version of the library and just added literally the same code for now to see if it would work, but it's good that I don't have to worry about an update wiping it.
