### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by SDmorgan** [CollaboratingPlatypus/PetaPoco#443]
Some code cleanup for PetaPoco.cs

Lines 7960 and 7961
int paramIndex;
                if (int.TryParse(param, out paramIndex))

**Change to** 
              if (int.TryParse(param, out int paramIndex))

Lines 827, 828
string sqlCount, sqlPage;
            BuildPageQueries<T>((page - 1)*itemsPerPage, itemsPerPage, sql, ref args, out sqlCount, out sqlPage);

**Change to** 
string sqlCount, sqlPage;
            BuildPageQueries<T>((page - 1)*itemsPerPage, itemsPerPage, sql, ref args, out sting sqlCount, out string sqlPage);

Lines 927, 928
string sqlCount, sqlPage;
            BuildPageQueries<T>(skip, take, sql, ref args, out sqlCount, out sqlPage);
**Change to**
            BuildPageQueries<T>(skip, take, sql, ref args, out string sqlCount, out string sqlPage);

Lines 1347, 1348
                           PocoColumn pkColumn;
                            if (primaryKeyName != null && pd.Columns.TryGetValue(primaryKeyName, out pkColumn))
**Change to** 
if (primaryKeyName != null && pd.Columns.TryGetValue(primaryKeyName, out PocoColumn pkColumn))

Lines 1359, 1360
 PocoColumn pc;
                            if (pd.Columns.TryGetValue(primaryKeyName, out pc))
Change to 
                             if (pd.Columns.TryGetValue(primaryKeyName, out PocoColumn pc))

**Comment by pleb** [comment]
HI SDmorgan. Please submit PRs. This is not how you suggest changes.
