### ISSUE TITLE
Code streamlining

### ISSUE THREAD

**Issue by SDmorgan** [CollaboratingPlatypus/PetaPoco#444]
Lines 6037

var pc = new PocoColumn();
                pc.PropertyInfo = pi;
                pc.ColumnName = ci.ColumnName;
                pc.ResultColumn = ci.ResultColumn;
                pc.ForceToUtc = ci.ForceToUtc;
                pc.InsertTemplate = ci.InsertTemplate;
                pc.UpdateTemplate = ci.UpdateTemplate;

Change to
var pc = new PocoColumn
                {
                    PropertyInfo = pi,
                    ColumnName = ci.ColumnName,
                    ResultColumn = ci.ResultColumn,
                    ForceToUtc = ci.ForceToUtc,
                    InsertTemplate = ci.InsertTemplate,
                    UpdateTemplate = ci.UpdateTemplate
                };

**Comment by pleb** [comment]
HI SDmorgan. Please submit PRs. This is not how you suggest changes.
