### ISSUE TITLE
More code streamlining

### ISSUE THREAD

**Issue by SDmorgan** [CollaboratingPlatypus/PetaPoco#445]
Line 6060
var pd = new PocoData();
                pd.TableInfo = new TableInfo();
                pd.Columns = new Dictionary<string, PocoColumn>(StringComparer.OrdinalIgnoreCase);
               

Change to
var pd = new PocoData
                {
                    TableInfo = new TableInfo(),
                    Columns = new Dictionary<string, PocoColumn>(StringComparer.OrdinalIgnoreCase)
                };

**Comment by pleb** [comment]
HI SDmorgan. Please submit PRs. This is not how you suggest changes.
