### ISSUE TITLE
Registration for custom DatabaseProviders

### ISSUE THREAD

**Issue by asherber** [CollaboratingPlatypus/PetaPoco#447]
It would be nice to be able to register custom `DatabaseProviders` with PetaPoco so that we can use the `Database` constructor overloads that take either a connection string name, or a connection string and a provider name. The current issue is that those overloads make use of `DatabaseProvider.Resolve()`, which only knows about the built-in providers.

I'm imagining something like this:

```csharp
DatabaseProvider.RegisterCustomProvider("MyProviderName", typeof(My.Provider));
// or 
DatabaseProvider.RegisterCustomProvider<My.Provider>("MyProviderName");
```

This method would add the registration to an `Dictionary<string, IProvider>` in `DatabaseProvider`, and the internal `Resolve()` methods could check that dictionary either before or after looking at the built-in types.

If this is acceptable, I'm happy to work on some code and submit a PR.

**Comment by pleb** [comment]
I'll let the beta run for a few days. If there are no issues, I'll merge this into the master branch. 

Thanks for the contribution.

**Comment by asherber** [comment]
I'd like to also contribute a brief wiki page on custom providers. What's the best way of getting that to you? Should I just open a new ticket and put the text there?

**Comment by pleb** [comment]
I've invited you to project :)

This should give you write access to the wiki pages. Let me know if there are any issues.

Also, feel free to document and help out
