### ISSUE TITLE
Can not use Transaction with MS Access DB

### ISSUE THREAD

**Issue by hpposch** [CollaboratingPlatypus/PetaPoco#454]
I have a MS Access database and i use PetaPoco with the OleDb to read and write data to that database.
Read-Write works perfectly, but when i try to use a transaction to write nested data (Header entry with multiple child entries) i get the following error:
The OleDB transaction has been completed, it is not longer usable

This happens always when i call Complete or CompleteTransaction.
I tried all differnet examples from here: https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Transactions

I hope someone has got an idea how to solve this issue.

Thanks in advance :)

**Comment by pleb** [comment]
Create a simple code example and confirm if it works or not. If it works, look at how it could be going wrong with your codebase. In the case you can replicate a bug, post the code here ;)

**Comment by asherber** [comment]
The following basic use of a transaction with Access works for me. If you have a small reproducible example of a transaction not working, please post it. Please include the table structure if that seems to be part of the issue.

```csharp
var config = DatabaseConfiguration.Build()
    .UsingConnectionString(@"...")
    .UsingProvider<MsAccessDbDatabaseProvider>();
    
using (var db = new Database(config))
using (var trans = db.GetTransaction())
{
    var poco = new Table1() { Field1 = "Thing2" };
    db.Insert(poco);
    trans.Complete();
}
```
