### ISSUE TITLE
Missing LINQish overloads

### ISSUE THREAD

**Issue by asherber** [CollaboratingPlatypus/PetaPoco#458]
https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Querying-LINQ-Style indicates that the LINQish methods have overloads that can take just the primary key of the POCO, but those overloads don't seem to exist in the code. Is it planned to add those overloads? Should the docs be updated in the meantime to remove them?

**Comment by pleb** [comment]
I see find them. Look at the [BaseQueryLinqTest.cs](https://github.com/CollaboratingPlatypus/PetaPoco/blob/development/PetaPoco.Tests.Integration/Databases/BaseQueryLinqTests.cs) class

**Comment by asherber** [comment]
Sorry, user error.

**Comment by pleb** [comment]
No worries. Happens to the best of us ;)
