### ISSUE TITLE
this is a bug

### ISSUE THREAD

**Issue by samchenws** [CollaboratingPlatypus/PetaPoco#464]
ExecuteReader requires an open and available Connection. The connection's current state is connecting.
my code:

![image](https://user-images.githubusercontent.com/37535153/40869086-98a82a5c-6647-11e8-833d-9dd56f55a592.png)

![image](https://user-images.githubusercontent.com/37535153/40869147-4a6ec480-6648-11e8-872e-1bf86c6a1956.png)
 
DbContext is DataBase，I Just rename;

```csharp
public DbContext(string connectionString, string providerName = null)
{
    if (string.IsNullOrEmpty(connectionString))
        throw new ArgumentException("Connection string cannot be null or empty", "connectionString");

    _connectionString = connectionString;
    Initialise(DatabaseProvider.Resolve(providerName, true, _connectionString), null);
}
```
the process：
I have a class AdminGrantAttribute；

```csharp
protected override bool IsAuthorized(HttpActionContext actionContext)
{
   unitOfWork = new UnitOfWork(new DbStringImpl("basicDataBase"),false);
   authorizeService = new AuthorizeServiceImpl(unitOfWork);
}
```
the AuthorizeServiceImpl code:
```csharp
private readonly IDbRepository<Permission_Authorize> authorizeRepository = null;
public AuthorizeServiceImpl(IUnitOfWork unitOfWork)
{
    authorizeRepository = unitOfWork.Repository<Permission_Authorize>();
}
````
the  unitOfWork Repository code
```csharp
public IDbRepository<T> Repository<T>(string connectionName = null)
{
    var poolItem = dataBasePool.DefaultPoolItem();

    return new DbRepository<T>(new DbContext(poolItem.ConnectionString, poolItem.ProviderName));
}
```
**ExecuteReader requires Connection that has been opened and available. The current state of the connection is being connected**
This is not a problem that has always appeared.

**Comment by samchenws** [comment]
the petapoco version is 5.1.289

**Comment by pleb** [comment]
Check to make sure you're not leaking references to PP across threads. So for the web, multiple requests. If this doesn't happen consistently, you're most likely have a threading bug.

**Comment by samchenws** [comment]
@pleb Thank you，I will check my code again.

**Comment by samchenws** [comment]
@pleb I'm sorry,I found the problem.It has nothing to do with PetaPoco.I love  PetaPoco,Because it's very light and convenient.Thanks to all the PetaPoco developers.

**Comment by pleb** [comment]
No worries mate. Happy you found it 😃
