### ISSUE TITLE
IsNew method doesn't consider Decimal field.

### ISSUE THREAD

**Issue by sg6782151** [CollaboratingPlatypus/PetaPoco#466]
When Save is called on POCO, it calls IsNew method to check if the PrimaryKey field contains default value of the datatype. IsNew method though considers every other possible datatypes for the column, but has no reference to DECIMAL datatype. If the PrimaryKey field in SQL Server is of type Numeric, it causes PetaPOCO to not properly identify if the record is new or not & thus calls UPDATE instead of INSERT.

**Comment by pleb** [comment]
To get around this, you can extend PP and override the IsNew method. PRs are also welcome ;)

**Comment by asherber** [comment]
I'm curious: What kind of table would have a primary key of type Numeric?
