### ISSUE TITLE
Non PK Identity Columns

### ISSUE THREAD

**Issue by CommanderAlchemy** [CollaboratingPlatypus/PetaPoco#469]
Hi, 

Searched for this for a while but cannot find anything regarding this. 
From my understanding PetaPoco does not support identity columns that are not primary key?

**Comment by picasso566** [comment]
All you need to do is treat the column as a calculated field so it will not be updated. You can use the [ignore] attribute.

**Comment by CommanderAlchemy** [comment]
@picasso566  But won't that also ignore to populate the field when getting the field data into an object?

**Comment by picasso566** [comment]
I'm sorry you're right.

How about ResultColumn ?

**Comment by CommanderAlchemy** [comment]
@picasso566 

Hehe, yeah was trying that just before you mentioned it, however for some reason the save happens using save(this); and it does not throw anything and returns ID's etc but nothing is actually saved in the database....

**Comment by pleb** [comment]
@CommanderAlchemy any chance of a small code snippet so that I can reproduce the error?

**Comment by CommanderAlchemy** [comment]
@pleb all I do is save(this), Let me see if I can get a small testcase going.
