### ISSUE TITLE
A way to process property before insert and after read

### ISSUE THREAD

**Issue by revenz** [CollaboratingPlatypus/PetaPoco#473]
I had a custom version of petapoco a few years ago and I hacked it so I could modify properties as there were being written/read.
This allowed me to decorate a property with [Encrypted].
So when my code saw a property with the attribute [Encrypted[, it would automatically decrypt when fetching data, and when insert/updating, it would check if the new value was not encrypted, and automatically encrypt it before sending it to the database.

I'm starting a new project, and my version is so custom now to the another project, I'm wanting to just use the nuget.  Is there a way to easily do this now?  Something that I can just decorate a property and thats it?  I'm going to be doing this in a few places, so wanting to keep it very simple and not much code.

Thanks.

**Comment by pleb** [comment]
Check out the SQLite test provider (https://github.com/CollaboratingPlatypus/PetaPoco/blob/development/PetaPoco.Tests.Integration/Databases/Sqlite/SqliteDBTestProvider.cs)

I'm pretty sure could do what you want.

**Comment by pleb** [comment]
Update. 

Although in that provider I'm messing with dates. You could intercept in the same manner and encrypt/decrypt.
