### ISSUE TITLE
Version 6.1 - Add Async support

### ISSUE THREAD

**Issue by pleb** [CollaboratingPlatypus/PetaPoco#485]
The recent work by @asherber has motivated me to devote a little more time to PetaPoco. Thanks, @asherber for chipping in a doing such a great job!

Over the next month or so I'm going to tackle Async support. I'm assuming, like .net standard, this is a feature that people would "just expect" to be there when they open the box. 

I plan to follow the MS guidance -> [Task-based Asynchronous Pattern (TAP)](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap).

At this stage, I'll be applying the [configure await false pattern](https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f) for library code. 

Any feedback is welcome.

**Comment by tomekjaworski** [comment]
Great news! 😃

**Comment by asherber** [comment]
See #141; maybe work with @tmenier or build on what he's done with [AsyncPoco](https://github.com/tmenier/AsyncPoco)?

**Comment by samchenws** [comment]
Great news! And thanks for your awesome contribution 😃

**Comment by tmenier** [comment]
You're bumping into all the pain points I had one upon a time. :)

**Comment by asherber** [comment]
1. AsyncPoco and NPoco have both implemented `QueryAsync()` -- is there something that can be gleaned from their approaches?

2. This feels funny to me -- it doesn't seem like the way that sync/async code is usually implemented. I haven't looked at it in detail, but I would vote for keeping the implementations separate. Yes, there would be some duplicated code, but I don't think there would be much; seems like you'd mostly need two copies of `ExecuteReader()` and its brethren.

**Comment by pleb** [comment]
Re point 1. There are ways around the issue. However, it will cause a differences between the async verse sync API. The workarounds end up being not as clean. For example, with AsyncPoco, the workaround is a callback the caller passes in. I haven't looked at NPoco, but I assume it'll be the same. I'd rather wait for c# 8 before async is added for this particular API. 

Re point 2. The issue is that async and sync code paths are not compatible. In c# the compiler writes out a statemachine for any await/task usage. So the choice is either duplicate code or favour async. I'll keep an eye out, but I haven't seen any nice solutions to date for this problem.

**Comment by asherber** [comment]
Unfortunately, it looks like `IEnumerableAsync` in C# 8 will be tied to .NET Standard 2.1 -- which will be implemented by .NET Core 3.0 but not by any framework version (including the upcoming 4.8). Given that, I would prefer to have an async API for PetaPoco that works on current framework and .NET Standard versions, even if the signature and usage are different from the sync API.

**Comment by asherber** [comment]
Looks like NPoco handles `QueryAsync()` by calling `cmd.ExecuteReaderAsync()` to get the `DbDataReader` but then doing synchronous `r.Read()` to get each individual record rather than `r.ReadAsync()` -- the assumption being (I guess) that it's the query execution that benefits the most from being async, whereas there's no big advantage when it comes to reading individual records. This lets NPoco avoid requiring a callback as a parameter.

I'd be interested in @tmenier 's thoughts on this compromise -- whether he found that `ReadAsync()` had tangible benefits in certain scenarios, or whether he just wanted to be async all the way down.

**Comment by tmenier** [comment]
@asherber The benefit of using `ReadAsync()` instead of `Read()` is that it's non-blocking. Same as any other async I/O. Unless I'm not understanding the question?

**Comment by asherber** [comment]
@tmenier  Sorry, I guess I wasn't being clear (or I might be misunderstanding the issue). When you send a command to the db, I can see the benefits of using `ExecuteReaderAsync()`, so that you don't block while you're waiting for a potentially long-running query to execute on the db. 

But it seems to me that in most cases, asking for the next record is a fairly cheap operation -- unless you're pulling back really big records. So for the majority of cases, my guess is that there's no practical advantage to `ReadAsync()` over `Read()`, because the potential for significant blocking is low. NPoco seems to have looked at this calculus and decided that the small chance of a blocking impact from large records was worth it to keep the semantics of `QueryAsync()` the same as `Query()`. I was curious whether you had weighed things and come to the opposite conclusion, or whether you didn't want to mix sync and async calls on principle.

**Comment by tmenier** [comment]
The benefits of `ReadAsync` would be greater the larger the result set, especially if it exceeds the size of the network buffer, in which case it would need to make multiple round-trips to the database. The advantage might be negligible or it might be significant, depending on the scenario. But asking whether I weighed the benefits sort of misses the point. As a library developer I don't believe it's up to me to make that determination. I think it's up to me to make sure the method behaves as expected, and I think the user would most likely expect `QueryAsync` to do non-blocking reads. I can't speak to why @schotime did it the way he did in NPoco.

**Comment by asherber** [comment]
Sure, thanks, that makes sense. 

(It's an interesting side question whether an `XxxAsync()` method implies to the user that everything that happens inside that method that can be async actually is, or whether it just implies that at least something in the method is async. I've never thought about that before.)

**Comment by wiraman** [comment]
any update for petapoco to support async?

**Comment by bjammin** [comment]
Have been following this thread eagerly awaiting the async feature.

Thanks for all your good work.  Any update on the ETA?

**Comment by pleb** [comment]
Sorry. Working on this now. It's been a busy end of the year, which also pushed into the new year.

**Comment by pleb** [comment]
I'll be pushing the work to https://github.com/pleb/PetaPoco/tree/async-support I think GH now support WIP PRs, which I'll try use too.

**Comment by bjammin** [comment]
> Sorry. Working on this now. It's been a busy end of the year, which also pushed into the new year.

No need to apoligize :)

> I'll be pushing the work to https://github.com/pleb/PetaPoco/tree/async-support

Is that going to confuse things, pushing to a forked repo?

Either way, post here when there is something to test and I'd be happy to help with that.

**Comment by pleb** [comment]
WIP PR has been made. Ref #507 to track progress

**Comment by pleb** [comment]
@asherber I'm thinking about dropping support for .net 4, as it doesn't support async. And, having to do a heap of preprocessor directives is annoying me. May I ask what your thoughts for this are? Also, anyone else is welcome to comment ;)

**Comment by asherber** [comment]
I don't know how many people are still targeting .NET 4, but it does seem a bit of a shame to leave them out of future improvements just because they can't leverage async. Is there some way of using partial classes to keep the async stuff (mostly) in one file? It does seem that longer-lived libraries are hesitant to drop .NET 4, and directives is the price one pays!

**Comment by pleb** [comment]
A little discussion regarding usage.

**Background**

The query API of PP, streams the results from the server using IEnumerable and yield. This is a pretty neat way of handling large data sets. The fetch API populates a List and returns it. So, consumers can use either method depending on their use case. A side note. the IEnumerable and yield catches a lot of people out when they first start using PP.

Currently, you can't use await and yield, as the lang doesn't support it. Support will be added in v-next, but it'll be a while before widespread adoption. And, I'm not sure if it's backwards compatible, as in compiler magic, runtime magic or a little of both. 

**Solution**

Some libraries get around this by requesting a callback. This is ok-ish, but somewhat ugly IMO. 

    // Example interface
    Task QueryAsync<T>(Action<T> receivePocoCallback);

    // Example usage
    await db.QueryAsync<Customer>(c => doSomethingWIthCustomer(c));

Another idea I came up with is to use a little adapter/helper

    // Example interface
    Task<IEnumerableAsyncAdapter<T>> QueryAsync<T>();

    // Example usage
    using(var asyncAdapter = await db.QueryAsync<Customer>())
        while(asyncAdapter.HasRecords)
            var customer = await asyncAdapter.Pull();

The second solution allows for a more natural flow when writting code. I personally like this one.

I'm thinking of supplying both styles, but I do have a concern with the second one. My concern is that down the track, when it comes time to properly support the c# 8 async streams, it will be a breaking change, as the API QueryAsync will need to change from returning an IEnumerableAsyncAdapter to a IAsyncEnumerable - due to no overloading based on return type.

So, one path forward is to say - to hell with v-next, we're rolling with IEnumerableAsyncAdapter as we can do it now. 

Another path is to add a slight different method name, such as, QueryAsyncAdapter so that when the time comes to support async streams, there's no breaking change. (This is the current one I'm using is my branch).

I would love to hear other peopels thoughts.

**Comment by asherber** [comment]
Personally, the callback syntax seems more straightforward to me, and I say that as someone who has **not** used other libraries with that pattern.

If you're going with the second syntax, my instinct is to say that a name like QueryAsyncAdapter, which is nothing like the planned language additions, is less likely to cause confusion.

I also wonder if it would be possible to use a different kind of syntax, something more like an `IDataReader`:

```csharp
using (var adapter = await db.QueryAsync<Customer>())
{
    while (await adapter.ReadAsync()
    {
        // do something with adapter.Record or adapter.Object or....
    }
}

**Comment by asherber** [comment]
If the second syntax is workable, maybe call it `AsyncQueryReader` or something like that, to emphasize the `IDataReader` pattern?

**Comment by pleb** [comment]
@asherber just in the insight I needed. 

The callback can stay, it's baked. I'd still like to pursue the latter though. PP has many ways to do the same thing, so I don't think that providing both will be all that foreign.

**Comment by pleb** [comment]
Much nicer.

So we have

            var results = new List<Order>();
            await DB.QueryAsync<Order>(p => results.Add(p), sql, OrderStatus.Pending);
            results.Count.ShouldBe(3);

and

            var results = new List<Order>();
            using(var asyncReader = await DB.QueryAsyncAdapted<Order>(sql, OrderStatus.Pending))
                while (await asyncReader.ReadAsync())
                    results.Add(asyncReader.Poco);

**Comment by pleb** [comment]
The rest of the async should flow much quicker, as essentially all other methods call Query and now QueryAsync

**Comment by asherber** [comment]
Love the syntax! Would you consider `QueryReaderAsync()` instead of `QueryAsyncAdapted()`? I think it's usual to have the `Async` at the end of the method name, and having `Reader` in there makes the pattern more clear.

**Comment by pleb** [comment]
@asherber Yep, absolutely, I missed it. I was concentrating on other things. My plan is to simply have `Query` and `QueryAsync`, as the callback means I can use overloading to sperate the APIs.

**Comment by pleb** [comment]
Quick update.

The latest version of PP v6 beta has async support for all query related methods (minus multi-poco).

Next on my list is the mutating methods, such as insert, update, delete and etc.

Hopefully, not long now before it's all done.

**Comment by pleb** [comment]
@bjammin you may start testing if you like 😄

**Comment by bjammin** [comment]
> @bjammin you may start testing if you like 😄

That's great, thanks for all the hard work on this!  I've been watching the discussions but didn't really have a firm enough opinion to contribute.  Looking forward to checking it out.

**Comment by pleb** [comment]
beta build now has full async support for query/mutate

![yay](https://media.tenor.com/images/f4c8059e75d21aa301174d4374ec4680/tenor.gif)

**Comment by pleb** [comment]
[PetaPoco.Compiled 6.0.391-beta](https://www.nuget.org/packages/PetaPoco.Compiled/6.0.391-beta) for reference

**Comment by pleb** [comment]
This has now been released.

**Comment by bjammin** [comment]
Hi guys, my apologies for totally dropping out of this thread.  I finally had some time to put this in (now that all the hard work has been done) and so far it's all worked perfectly!

I had previously implemented AsyncPoco in a few key places where I needed async, and was running it alongside PetaPoco (this was a bit of a pain and a bit scary really!)

I just uninstalled AsyncPoco package, updated PetaPoco and updated my references and everything worked perfectly without changing any code.  Whether by design or happy accident, every async method name you implemented is exactly the same is in AsyncPoco.

Will be doing some more testing, but so far so good.

+1 thank you so much
