### ISSUE TITLE
Ad Hoc querying with table valued parameters?

### ISSUE THREAD

**Issue by strangepholker** [CollaboratingPlatypus/PetaPoco#488]
We've got a need to perform queries that include long lists of ids...potentially thousands of ids.  Our initial implementation was a simple where IN (@0) implementation and the list of ids was passed in as an argument.  

e.g.
.Where($"Id IN (@0)", itemIdBatchParameter)

However, this approach has a couple of problems.  First, with a sufficiently large list of items it's possible to exceed SQL server's 2100 maximum parameter count.  We've dealt with that by creating batches of ids and making multiple queries and then concatenating the resulting collections of POCOs.  However, we also suspect this use of the IN with a highly variable number of parameters is causing problems with the SQL Server query optimizer as a separate query plan is generated for each permutation in the parameter count.  

Ideally, I'd like to join to a table valued parameter.  The raw SQL for doing this is provided below. 

```
-- Declare User-Defined Table type.
-- This would be defined outside of the scope of a given query
Create Type [medical].GuidList as Table
(
	Id uniqueidentifier primary key
)

-- User Defined Table type is populated with 'id' values from a previous query
Declare @VersionIds medical.GuidList
Insert into @VersionIds values ('FE3D8792-4D86-4AB6-9023-0ED321C79B24')
Insert into @VersionIds values ('9DAC2440-3ACB-4FCA-9AC4-6AFF73ABDF9F')
Insert into @VersionIds values ('BB2E7C00-7BA6-487E-8F02-C0A20C082851')

-- Filtering is performed by joining to the table valued parameter
-- rather than using WHERE DocumentVersionId IN ('FE3D8792-4D86-4AB6-9023-0ED321C79B24', '9DAC2440-3ACB-4FCA-9AC4-6AFF73ABDF9F', 'BB2E7C00-7BA6-487E-8F02-C0A20C082851', ...)
select * from medical.[DocumentSetEntry] setEntry
inner join @VersionIds versions
ON setEntry.[DocumentVersionId] = versions.Id

```

I'm able to declare the SqlParameter in c# like this:

```
protected SqlParameter CreateIdListParameter(IEnumerable<Guid> ids, string parameterName)
{
	const string columnName = "Id";
	var table = new DataTable();
	table.Columns.Add(columnName, typeof(Guid));

	foreach (var guid in ids)
	{
		var row = table.NewRow();
		row[columnName] = guid;
		table.Rows.Add(row);
	}

	var sqlParameter = new SqlParameter(parameterName, SqlDbType.Structured);
	sqlParameter.TypeName = "[medical].GuidList";
	sqlParameter.Value = table;

	return sqlParameter;
}
```

However, I'm not able to get the parameter recognized as an argument in the resulting Sql.  I believe that the argument I'm supplying as part of the On call is being ignored since there's no @ in the first string parameter.  Really, I would want to be able to have an overload of the various Join methods that allows you to pass in an argument though.  

```
var versionIdsTableParameter = CreateIdListParameter(itemVersionIds, "@VersionIds");
	
setEntryQuery.Select("*")
	.From("[medical].[DocumentSetEntry] setEntry ")
	.InnerJoin("@@VersionIds versions")
	.On("setEntry.[DocumentVersionId] = versions.Id", versionIdsTableParameter);
setEntries = db.Query<TSetEntry>(setEntryQuery).ToList();
```

Has anyone ever looked into adding support for table valued variables?  Do you have suggestions for alternative ways to craft this query using PetaPoco?  I would very much like to avoid creating stored procedures for querying each table.

**Comment by picasso566** [comment]
I've run into a similar issue but I handled it completely differently.

I used a bulk insert (or a class to do a bulk insert) into a temporary
table and the do queries against that. Just an idea completely separate
from Peta Poco

**Comment by strangepholker** [comment]
Thanks for the suggestion.  Unfortunately, I don't think managing temp
tables is a viable option for us as each query instance would need to
maintain its own table and ensure that table was cleaned up after
retrieving the results.  The list of ids will be highly variable based on
user input rather than being populated from some presumably static (or
semi-static) source.

**Comment by asherber** [comment]
It's not pretty, but perhaps you could hook `Database.OnExecutingCommand()` to add the parameter to the `SqlCommand` directly.

As discussed in #472, and as noted in the [old documentation](https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Old-Documentation), the query builder in PetaPoco has always been pretty basic, by design. I can't speak for @pleb, but it seems unlikely that this kind of advanced functionality would be added (although if you want to work on a PR...)

As also noted in #472, I put together a package that lets you use [SqlKata](https://sqlkata.com) to write your queries. That's a more advanced SQL builder, but I don't think the kind of thing you want is supported there either.

**Comment by asherber** [comment]
So this sort of thing did work for me. As I said, it's not the prettiest.

```csharp
public class MyDb: Database
{
    // Need to provide appropriate constructors for this class

    public SqlParameter TableParam { get; set; }
    
    public override void OnExecutingCommand(IDbCommand cmd)
    {
        if (TableParam != null)
            cmd.Parameters.Add(TableParam);      
    }
}

void Main()
{
    using (var db = new MyDb())
    {
        db.TableParameter = CreateIdListParameter(itemVersionIds, "@VersionIds");
        var q = Sql.Builder.Select("*")
            .From("[medical].[DocumentSetEntry] setEntry ")
            .InnerJoin("@@VersionIds versions")
            .On("setEntry.[DocumentVersionId] = versions.Id");

        var setEntries = db.Query<TSetEntry>(setEntryQuery).ToList();         
    }
}
```
OTOH, there is another way to get what you want:

```csharp
setEntryQuery.Select("*")
	.From("[medical].[DocumentSetEntry] setEntry ")
        .Append("INNER JOIN @0 versions ON setEntry.[DocumentVersionId] = versions.Id", 
                versionIdsTableParameter);
```

And having thought about this all some more, while I still think the idea of a `Join()` overload that lets you pass in an argument is too specialized a case, it might be useful to add a `Sql.AddParameter(IDbDataParameter)` method.  This would let you do:

```csharp
setEntryQuery.Select("*")
	.From("[medical].[DocumentSetEntry] setEntry ")
	.InnerJoin("@@VersionIds versions")
	.On("setEntry.[DocumentVersionId] = versions.Id")
        .AddParameter(versionIdsTableParameter);
```

**Comment by pleb** [comment]
One more option on the table is building in clause yourself and not using parameters. Obviously, this opens the doors to a sql injection attack. Still, though, it's there.

**Comment by strangepholker** [comment]
Thanks for the feedback @asherber!  I'm not a huge fan of the Database descendant and OnExecutingCommand forcefully adding the table parameter.  Maybe I should give Append another shot though I've had issues chaining Where after Append previously.  I do like the idea of a `Sql.AddParameter(IDbDataParameter) ` implementation.  

In the short term I came to pretty much the same conclusion as @pleb and simply string concatenated my Ids (guids) and used STRING_SPLIT in an extension method.  It should be safe from Sql injection in my case because I'm only allowing the operation on guids.  

```
public static class PetaPocoSqlExtensions
{
	/// <summary>
	/// Appends a WHERE IN clause the PetaPoco Sql query using the specified column name and Ids
	/// </summary>
	/// <param name="query">The query to apply the WHERE IN clause to</param>
	/// <param name="columnName">The name of the column the filter applies to</param>
	/// <param name="ids">The collection of Ids to be searched</param>
	/// <param name="delimiter">The delimiter to be used between Ids when concatenating them</param>
	/// <returns>The modified query</returns>
	public static Sql WhereIdsIn(this Sql query, string columnName, IEnumerable<Guid> ids, string delimiter = ",")
	{
		var concatenatedIds = string.Join(delimiter, ids);
		query.Where($"{columnName} IN (SELECT VALUE FROM STRING_SPLIT(@0, '{delimiter}'))", concatenatedIds);
		return query;
	}
}
```

The resulting usage looks like this:

```
var setEntryQuery = Sql.Builder;

// SELECT *
// FROM [medical].[DocumentSetEntry]
// WHERE [DocumentVersionId] IN (@0, @1, ...)
setEntryQuery.Select("*")
    .From("[medical].[DocumentSetEntry]") // e.g. From [medical].[DocumentSetEntry]
	.WhereIdsIn("[DocumentVersionId]", itemVersionIdBatch);

db.Query<DocumentSetEntry>(setEntryQuery).ToList();
```

**Comment by asherber** [comment]
@strangepholker  I took a whack at `AddParameter()`. It wasn't difficult to get the `SqlParameter` onto the `Sql` object, but it turned out to be very convoluted to get it to flow through the rest of the plumbing all the way to the `IDbCommand` object. 

By the way, the latest beta exposes the `OnXxx()` methods as events, so instead of having to write your own descendant to override the methods, you can do something like this:

```csharp
using (var db = new Database())
{
    db.CommandExecuting += (s, e) => e.Command.Parameters.Add(CreateIdListParameter(itemVersionIds, "@VersionIds"));
    
    var q = Sql.Builder.Select("*")
        .From("[medical].[DocumentSetEntry] setEntry ")
        .InnerJoin("@@VersionIds versions")
        .On("setEntry.[DocumentVersionId] = versions.Id");

    var setEntries = db.Query<TSetEntry>(setEntryQuery).ToList();         
}
```
