### ISSUE TITLE
Table or name with @ in it breaks CreateCommand

### ISSUE THREAD

**Issue by NichUK** [CollaboratingPlatypus/PetaPoco#494]
A table or name containing an @ breaks CreateCommand, which assumes that it is a parameter.

For SQL Server it's perfectly acceptable to create a table called mytable@something by enclosing it in [ ], however this breaks CreateCommand.

By changing the CreateCommand regex from `@"(?<!@)@\w+"` to `@"(?<!@)(?<!\[)@\w+(?![\w\s]*[\]])"` it will ignore @ which are contained inside [ ] so the following will work as a Db.Execute(sql).

            var sql =
                "CREATE TABLE [table@thing] (" +
                "  [Id] int IDENTITY (1,1) NOT NULL " +
                "  CONSTRAINT [table@thing] PRIMARY KEY ([Id])" +
                ")";

Apologies for not providing a PR and Unit Test, I'll come back to it if I can if you guys don't have it sorted by then. My first time using PetaPoco - it's absolutely rocking it for a particular project use we have. 

Thank you!

**Comment by iadaz** [comment]
Convention is to escape an @ sign with another, e.g. `select from table@@thing`

See also: https://github.com/CollaboratingPlatypus/PetaPoco/issues/59

I'll let one of the admins comment on the suitability of your amendment.

**Comment by asherber** [comment]
@NichUK Can you confirm that escaping the `@` works for you? I just ran through a unit test, and it works for me.
