### ISSUE TITLE
Assembly has wrong version info

### ISSUE THREAD

**Issue by asherber** [CollaboratingPlatypus/PetaPoco#495]
The v6 assemblies for PetaPoco.Compiled are getting built with a version number of 1.0.0.0.

From ILSpy of NuGet package 6.0.348-beta:

```
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyVersion("1.0.0.0")]
```

I think whatever versioning scheme was used in v5 got dropped in the move to v6. I'm a big fan of [Nerdbank.GitVersioning](https://github.com/aarnott/Nerdbank.GitVersioning) and can put in a PR to switch to that if you like. It'll make sure that the assembly and the NuGet package get the same numbering automatically when they're built.

**Comment by asherber** [comment]
Thanks, @pleb  -- latest package does have version info set. But I would suggest that the `AssemblyVersion` attribute should be set to `6.0.0.0` rather than `6.0.350.0`;  [this article](https://codingforsmarties.wordpress.com/2016/01/21/how-to-version-assemblies-destined-for-nuget/) has a good discussion. There appear to be two schools of thought as to whether the `AssemblyVersion` should then stay at `6.0.0.0` for all `6.x` releases, or whether the minor version should be incremented in sync with the other version numbers. 

(Nerdbank.GitVersioning would take care of all of this for you. I think you'd just need to remove lines 16-20 in `appveyor.yml` and delete `-p:Version=$packVersion` in line 22. If you'd rather do it by hand, I think you need to set the `AssemblyVersion` property explicitly, in addition to `Version`. )

**Comment by pleb** [comment]
@asherber about to head off for holidays 😄, so I thought I'd just get the version info working. I didn't read the article, but I will try too soon. The only reason I can think of for tagging version changes, even minor/build, is so that Devs can narrow in on problematic releases easier. Of course, nothing should break for a minor change, but the real world is cruel.

I'll also check out the Nerdbank.GitVersioning package too. The only thing we need to keep in mind is ensuring pre-release builds, those which build off dev, are tagged as such.

**Comment by pleb** [comment]
Re leaving the assembly version alone, one word. Interesting... There was [this, from the reactive peeps,](https://github.com/dotnet/reactive/issues/205) which was posted in the comments. I'll going to read through that too, as I would like to hear their arguments for not leaving it alone. 

Still working my way through this. Next will be Nerdbank.GitVersioning.

**Comment by asherber** [comment]
As you've seen from the article, the scheme keeps relatively constant only the version number that MSBuild uses for linking; the one that Windows reports and the one that NuGet uses are incremented as usual. The idea is to make things easier for (some) libraries and apps that consume your library. I like this scheme and use it myself, but I don't feel strongly enough about it to evangelize. 

(It looks like the reactive thread is proposing different patch values depending on the target platform, which I don't like at all.)

NBGV has a couple of different ways of handling prerelease builds in the various version numbers. As with the above, I find it a very useful tool and use it in my projects, but if what you've got works for you, I'm not going to argue against it.

In any case, enjoy your holiday! I'll close this issue, since it's fixed; if you're interested in a branch with either of the above ideas, we can do that later in a different thread.

**Comment by pleb** [comment]
I'm happy with both :)
