### ISSUE TITLE
PetaPoco Random Errors

### ISSUE THREAD

**Issue by tuckersdev7** [CollaboratingPlatypus/PetaPoco#504]
![image](https://user-images.githubusercontent.com/47522123/52556601-18fcfc80-2e13-11e9-96c9-bb6c5c2394ce.png)

I have integrated Elmah with my project and some times it genrate random errors as displayed on above image. but if i start server again it start working normally.

**Comment by asherber** [comment]
At a glance, at least some of these look like problems with your code, rather than internal PetaPoco errors. For example, "Sequence contains more than one element" implies that you've called `db.Single()` or `db.SingleOrDefault()`, but the query found more than one matching record. 

Have you tried debugging your application and stepping through to see what's causing these errors? If you think that some of these are bugs in PetaPoco, or if you'd like some help troubleshooting your usage, can you post some of the code that's responsible?

**Comment by pleb** [comment]
@tuckersdev7 in addition to what @asherber has said. 

First, it's somewhat hard to tell from what you posted. if I were to guess, it would be leaking an instance of PP to other requests. So, basically, sharing a PP instance rather than each request having its own

**Comment by tuckersdev7** [comment]
> At a glance, at least some of these look like problems with your code, rather than internal PetaPoco errors. For example, "Sequence contains more than one element" implies that you've called `db.Single()` or `db.SingleOrDefault()`, but the query found more than one matching record.
> 
> Have you tried debugging your application and stepping through to see what's causing these errors? If you think that some of these are bugs in PetaPoco, or if you'd like some help troubleshooting your usage, can you post some of the code that's responsible?

Yes, I tried debugging my application but it does not occur every time. it happens randomly once in a day or once in two days.

**Comment by tuckersdev7** [comment]
> ![image](https://user-images.githubusercontent.com/47522123/52556601-18fcfc80-2e13-11e9-96c9-bb6c5c2394ce.png)
> 
> I have integrated Elmah with my project and some times it genrate random errors as displayed on above image. but if i start server again it start working normally.

I have one data provider class which is using petapoco object.
![image](https://user-images.githubusercontent.com/47522123/52616038-2ec6fc00-2ebd-11e9-917f-a573bcd93dc4.png)

It hase also one method which returns multiple result set which is shown in below image:
![image](https://user-images.githubusercontent.com/47522123/52616109-5b7b1380-2ebd-11e9-8b19-23a32b3356b4.png)

**Comment by pleb** [comment]
@tuckersdev7 how are you handling the PP instance per request? Are you using an IOC/Container?

**Comment by 6pac** [comment]
This would be a great thing to demonstrate in the proposed sample projects.
