### ISSUE TITLE
Explain file merge process

### ISSUE THREAD

**Issue by Razenpok** [CollaboratingPlatypus/PetaPoco#510]
Hi. I'm working on a project https://github.com/Razenpok/Tween.cs which I want to ship  as a single file. It actually is a single file already, but I want to split it into multiple to simplify development. Could you please explain the process behind code merging of `PetaPoco.cs`?

**Comment by pleb** [comment]
Hi @Razenpok,

We don't ship a single file version anymore, as it became a pain in the butt to do so with nuget and .netcore. 

That said, when we did do it, we used a little magic and hackery.

See the project file [here](https://github.com/CollaboratingPlatypus/PetaPoco/blob/2e0475928c8173271837cc01c8625aa970b3cacc/PetaPoco/PetaPoco.csproj#L125)
And see the project [here](https://github.com/CollaboratingPlatypus/PetaPoco/tree/development-v5/PetaPoco.Cs.Joiner)

**Comment by Razenpok** [comment]
Thank you @pleb, very cool 👍
