### ISSUE TITLE
Stored Procedure does not use parameters

### ISSUE THREAD

**Issue by hpposch** [CollaboratingPlatypus/PetaPoco#514]
Hello,

i call a stored procedure with the new implemented function FetchProc
for example i use: 
FetchProc<object>("dbo.Eval_PiecesPerHour", new { Starttime="10.04.2018 00:00" }, new { Endtime="11.04.2018 23:00" });
But i get the following error:
System.Data.SqlClient.SqlException: "Procedure or function 'Eval_PiecesPerHour' expects parameter '@Starttime', which was not supplied."

What am i doing wrong?
Thanks in advance for your help

**Comment by asherber** [comment]
@hpposch  Can you post the first part of your stored proc? It doesn't need to include the body, just want to see how the proc is defined.

**Comment by hpposch** [comment]
`USE [PCS.ProdData01]
GO
/****** Object:  StoredProcedure [dbo].[Eval_PiecesPerHour]    Script Date: 10.04.2019 18:03:16 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
-- =============================================
-- Author:		PCS Core development
-- Create date: 13.03.2019
-- Description:	Auswertung Teile pro Stunde.
-- =============================================
ALTER PROCEDURE [dbo].[Eval_PiecesPerHour]
	@Starttime Datetime,
	@Endtime Datetime
AS
BEGIN

	select WorkArea, getdate() as Timerstamp,  DATEPART(hour,ChangeTimeStamp) as Hour, productid, SUM(CASE When PartState=1 Then PartState Else 0 End ) as OkParts,SUM(CASE When PartState=2 Then PartState Else 0 End ) as NokParts,SUM(CASE When PartState=3 or PartState=4 Then PartState Else 0 End ) as ReworkParts, (case when SUM(PartState)<> 0 then 3600/SUM(PartState) else 0 end) as Takt  from DataHeaderHistory
	where ChangeTimeStamp between @Starttime and @Endtime 
	group by  ProductId,WorkArea,DATEPART(hour,ChangeTimeStamp)  --ProductId, die Gruppierung für die Productid vorerst mal entfernt.....


END`

**Comment by asherber** [comment]
Thanks, let me set up a test to reproduce.

**Comment by hpposch** [comment]
thank you :)

**Comment by asherber** [comment]
I'm not able to reproduce this.  Here's my test stored proc:

```sql
CREATE PROCEDURE ParamTest 
    @StartTime DateTime, 
    @EndTime DateTime
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 'Start="' + convert(varchar, @StartTime,20) + '", End="' 
        + convert(varchar, @EndTime,20) + '"'
END
GO
```
And here's my code:

```csharp
using (var db = new Database(myConnStringName))
{
    var result = db.FetchProc<string>("ParamTest",
        new { StartTime = "10.04.2018 00:00" }, new { EndTime = "11.04.2018 23:00" });
    result.Dump();  // Start="2018-10-04 00:00:00", End="2018-11-04 23:00:00"
}
```

Are you able to reproduce the issue using my procedure and code?

**Comment by hpposch** [comment]
Thank you for testing.
I will try your code as soon as i am back ob my pc.

I also wanted to let you know that i had succesy when i called the stored procedure the old way.. like:
db.Fetch<object>(“Eval_PicesPerHour @0, @1“, new {Starttime = “10.04.2018 00:00“}, new {Endtime = “10.04.2018 23:00“});

This returna the exact same result as i would get from sql management studio.
So for the worst case i have a workaround ;)

**Comment by asherber** [comment]
@hpposch  Anything further on this?

**Comment by hpposch** [comment]
@asherber No thank you :)
For me everything is fine.
Thanks for your help.
