### ISSUE TITLE
Constructor change is breaking

### ISSUE THREAD

**Issue by asherber** [CollaboratingPlatypus/PetaPoco#521]
The `Database` constructor which used to take an `IDbConnection` now takes a `DbConnection`. This is a breaking change -- I'm creating databases from helper functions that return an `IDbConnection`.

I understand that the async functions need a `DbConnection` for `OpenAsync()`. Could the constructor be changed back to `IDbConnection`, and then the async functions have a guard condition to cast the connection to `DbConnection` and check for null?

**Comment by pleb** [comment]
Sorry, a mistake. The async methods cast IDbCon to DbCon for async, and fallback to non-async where the cast can't be made. My bad. I'll commit a fix
