### ISSUE TITLE
Object reference not set to an instance of an object on MoveNext

### ISSUE THREAD

**Issue by lpbinhitlab** [CollaboratingPlatypus/PetaPoco#525]
Hello, some time i get Exception Object reference not set to an instance of an object, when meet this issue i restart my web application in IIS, my web application can read data again, but some time later it occur again, may be one day, or after some day. 
Below is some exception i get:
'System.Web.HttpUnhandledException' was thrown. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PetaPoco.Database.CloseSharedConnection()
   at PetaPoco.Database.CloseSharedConnection()
   at PetaPoco.Database.<ExecuteReader>d__149`1.System.IDisposable.Dispose()
   at PetaPoco.Database.<ExecuteReader>d__149`1.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at ...

And some time get this exception
Object reference not set to an instance of an object.
   at PetaPoco.Database.CloseSharedConnection()
   at PetaPoco.Database.<ExecuteReader>d__149`1.System.IDisposable.Dispose()
   at PetaPoco.Database.<ExecuteReader>d__149`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)...

And some time get this exception.
Object reference not set to an instance of an object.
   at PetaPoco.Database.CreateCommand(IDbConnection connection, CommandType commandType, String sql, Object[] args)
   at PetaPoco.Database.<ExecuteReader>d__149`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ...
I used the latest version Version 6 - Netstandard 2.0+, 4.0, 4.5+
Does any one know how to fixed this issued?

**Comment by pleb** [comment]
First thoughts:

Seems like you sharing instances of PP between web requests. You could likely confirm this by conducting a little load testing.

I would run a load test single connection (this should pass)
I would run a load test multiple connections (this should fail)

**Comment by lpbinhitlab** [comment]
Yes I sharing instances between web requests. I have a BaseDAL class 
public class BaseDAL<T> where T : class, new()
    {
        public BaseDAL(string conn)
        {
            ConnectionString = conn;
            _db = new Database(ConnectionString);
        }

        public BaseDAL()
        {
            ConnectionString = "The SQL SERVER CONNECTION STRING";
        }

        public static string ConnectionString = "The SQL SERVER CONNECTION STRING";

        private static Database _db;
        public static Database db
        {
            get
            {
                if (_db == null)
                    //_db = new Database(ConnectionString) { IsolationLevel = System.Data.IsolationLevel.Chaos }; 
                    _db = new Database(ConnectionString) { IsolationLevel = System.Data.IsolationLevel.ReadCommitted }; 
                return _db;
            }
        }

        public static T GetById(object id)
        {
            return db.SingleOrDefault<T>(id);
        }

        public static void Create(T item)
        {
            db.Insert(item);
        }
...
}
}

My website have alot of requests, if we open connection and close for every requests i think it take more resource to request to SQL server. Is it true?

**Comment by pleb** [comment]
.net SQL server has a connection pool which solves this problem, so you don't need to worry about it usually. 

I would create an instance of PP at the start of each request and dispose of it at the end.

**Comment by lpbinhitlab** [comment]
One more problem is, it just occur this issue for some table, for example have 5 table A, B, C, D, E => When query on table A => Object reference not set to an instance of an object, then query on table C, D also Object reference. At that time i execute another page that query data on some another tables such as table D, E it OK.

**Comment by pleb** [comment]
When you share instances, you’re going to get weird errors. If the error is always reproducible, it’s very likely a race condition
