### ISSUE TITLE
does not have a strong name

### ISSUE THREAD

**Issue by ArgoZhang** [CollaboratingPlatypus/PetaPoco#529]
need add snk file for strong name
```
1>CSC : warning CS8002: Referenced assembly 'PetaPoco, Version=6.0.404.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```

**Comment by pleb** [comment]
I think this has come up before. Maybe search the history. 

A few notes. no, we’re not going to ship a signed version. There’s a package out there, which you can use to work-around packages, such as, PP which do not ship a signed version
