### ISSUE TITLE
Test crash "Construct_GivenConnectionStringAndProviderName_ShouldBeValid"

### ISSUE THREAD

**Issue by butulia** [CollaboratingPlatypus/PetaPoco#531]
With my @promatcloud partners we have observed the following:

Executing the test `Construct_GivenConnectionStringAndProviderName_ShouldBeValid()` for `SqlServerDatabaseProvider`, the `DB.Provider.GetFactory().CreateConnection().GetType().Name` returns `"SqlConnection"`, but this value is not contempled in `PetaPoco.Core.DatabaseProvider.Resolve` method. 

I think that a condition `providerName.IndexOf("SqlConnection", StringComparison.InvariantCultureIgnoreCase) >= 0` shold be added with `||` for `return Singleton<SqlServerDatabaseProvider>.Instance`

**Comment by asherber** [comment]
I think the code is written correctly, but the test is not. That overload of the `Database` constructor is supposed to take a connection string and a provider name, but instead it's passing in the name of the connection type. That is, it should be passing in `System.Data.SqlClient`, but instead it's passing in `SqlConnection`. 

The other interesting question is why that test doesn't get run if I run the `MsssqlDatabaseTests` from the Unit Test Explorer. I see 9 tests there, including this one, but only 8 get run. That's probably why this hasn't been noticed before.

**Comment by butulia** [comment]
It certainly seems that the data provided by the test is incorrect. 
I had looked at the test failure under the assumption that the test requirement was correct ... xD

**Comment by pleb** [comment]
> I see 9 tests there, including this one, but only 8 get run

Interesting

**Comment by asherber** [comment]
Yeah, I don't see any xUnit config files around that would cause this. I could try disabling DotCover to see if that has any effect.

I was looking at ways to get the right data into the test. I think the best way might be adding a string property on `DBTestProvider` that gets set in each db-specific descendant, and then making the `_provider` property in `BaseDatabase` protected so that descendants can access it.

**Comment by asherber** [comment]
On my other computer, also with VS2017 and DotCover, all 9 tests run and the test in question fails. I must have a bad cache somewhere.

**Comment by pleb** [comment]
I'll run the tests tonight. I've been using rider, and haven't had them fail. It would be interesting if the test was skipped too on my machine
