### ISSUE TITLE
IsNew always return false when PrimaryKey is typeof string and value is ""

### ISSUE THREAD

**Issue by ArgoZhang** [CollaboratingPlatypus/PetaPoco#538]
hi, I found that IsNew function always return false when the poco's PrimaryKey is System.String type and value is "".
in line 2532 will return. so line 2535 will be never work.
```
if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>) || !type.IsValueType)
    return pk == null;

if (type == typeof(string))
    return string.IsNullOrEmpty((string) pk);
```
it will work fine when the poco PrimaryId value is null.
is it by design? or a bug?

**Comment by ArgoZhang** [comment]
how about this? any question?

**Comment by ArgoZhang** [comment]
still busy? really hope resolve IsNew and Mapper.Register issues. So many string type Primary key in my project. i do not want to create a new class inherit Database and override IsNew function. any question please let me known. thanks

**Comment by pleb** [comment]
@ArgoZhang , this is now in dev. Use the latest beta nuget package to try it out

**Comment by ArgoZhang** [comment]
@pleb I've tested it. It's working very well.
