### ISSUE TITLE
Mapper.Register throws System.ArgumentException exception

### ISSUE THREAD

**Issue by ArgoZhang** [CollaboratingPlatypus/PetaPoco#540]
hi, PetaPoco.Mapper.Register throws exception in Multi-threading.
```
System.ArgumentException: An item with the same key has already been added. Key: Bootstrap.Security, Version=1.3.0.0, Culture=neutral, PublicKeyToken=c20f2177a7066899
  Module "System.ThrowHelper", in ThrowAddingDuplicateWithKeyArgumentException
  Module "System.Collections.Generic.Dictionary`2", in TryInsert
  Module "PetaPoco.Mappers", in RegisterInternal
  Module "Bootstrap.Security.DataAccess.DbHelper", in get_DbAccess
  Module "Bootstrap.Security.DataAccess.DbHelper", in RetrieveRolesByUserName
  File "C:\Users\Administrator\Desktop\kasenhoo-BootstrapAdmin-dev-Tabs\BootstrapAdmin\Bootstrap.DataAccess\Role.cs", line 190, col 88, in RetrieveRolesByUserName
    System.Collections.Generic.IEnumerable`1[System.String] RetrieveRolesByUserName(System.String)
```
how to avoid this exception?

**Comment by pleb** [comment]
@ArgoZhang what version of PP are you using?

**Comment by ArgoZhang** [comment]
PetaPoco | 6.0.415.0
get from Nuget

**Comment by ArgoZhang** [comment]
is bug right? or by design?

**Comment by pleb** [comment]
I’m thinking Bug. But, I can’t say for sure. Are you able to provide a small sample of code that reproduces it?

**Comment by ArgoZhang** [comment]
sure.
```  
public class MapperTest
{
    private class StringMapperTest : ConventionMapper
    {
        public StringMapperTest()
        {
            // for test
            Thread.Sleep(2000);
        }
    }

    [Fact]
    public void Register_Exception()
    {
        Assert.ThrowsAny<AggregateException>(() => ThrowExceptionMethod());
    }

    private void ThrowExceptionMethod()
    {
        var t1 = Task.Run(() => OrginalRegisterMethod());
        var t2 = Task.Run(() => OrginalRegisterMethod());
        Task.WaitAll(t1, t2);
    }

    private void OrginalRegisterMethod()
    {
        if (Mappers.GetMapper(typeof(string), null) == null) Mappers.Register(typeof(string), new StringMapperTest());
    }
}
```

**Comment by pleb** [comment]
@ArgoZhang, I'll get the PRs soon. Sorry, I'm a little snowed under at the moment. I just wanted to drop a message to say "Hey, I see the PRs. Thanks. But, it might be a little bit before I get to them"

**Comment by ArgoZhang** [comment]
fine! :)

**Comment by ArgoZhang** [comment]
hi, I have to release a new package(Longbow.PetaPoco) on nuget feeds. because my project have been blocked by the Mapper and IsNew issues. sorry for that. hope resolve the issues ASAP. thanks.

**Comment by asherber** [comment]
If this is something you need for your own use, for now, I would suggest not making the new package publicly available on nuget.org, because then it'll be there forever. You can use a local package source to host your private package, or you can create a free account on myget.org.

**Comment by ArgoZhang** [comment]
sound good. let me try myget.org

**Comment by asherber** [comment]
Hmm, looks like MyGet has been acquired by another company, and I don't see the free plan advertised anymore. Looks like gemfury.com has a free plan....although it only lets you host a single package!

**Comment by asherber** [comment]
It's possible that if you sign up for a trial at MyGet, it will revert to the old free plan once the trial ends. The free plan only supports public feeds, which usually isn't an issue because someone would still have to have your feed URL to get your package. This tweet suggests that free public feeds are still supported, though they don't say if that's just for existing accounts: https://twitter.com/MyGetTeam/status/1055884411818909696

**Comment by ArgoZhang** [comment]
@asherber thanks. unfortunately both twitter and myget can not be accessed in China

**Comment by asherber** [comment]
@ArgoZhang  You can also just use a local directory: https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds

**Comment by pleb** [comment]
Don’t forget GH is about to do packing hosting. Maybe there’s a beta you can sign up for.

**Comment by ArgoZhang** [comment]
@pleb thanks. i will reuse PetaPoco.Complied when resolved those issues. 😋 
what is GH? Fullname

**Comment by pleb** [comment]
GH = Github

**Comment by pleb** [comment]
Hey everyone, this is now in dev. Use the latest beta nuget package to try it out

**Comment by ArgoZhang** [comment]
@pleb its works.
