### ISSUE TITLE
Target table of DML statement cannot have any enable triggers

### ISSUE THREAD

**Issue by hpposch** [CollaboratingPlatypus/PetaPoco#543]
Hello together,

as the titel says i get the following error when i want to insert an entry into my table which has got a trigger enabled.
I already had a look at this post: https://github.com/CollaboratingPlatypus/PetaPoco/issues/201
But i do not really understand what needs to be done to solve the problem.

I tried to manually insert an entry and this worked fine for me, so the problem must be with petapoco.

Here is my trigger:

-- Trigger to execute the a stored procedure after a new workspace is inserted
```
CREATE TRIGGER TRIG_INSERT_WORKSPACE
on SiWorkspace
AFTER INSERT
AS
BEGIN
	DECLARE @oneid int
		DECLARE the_cursor_trig_workspace_insert CURSOR FAST_FORWARD
		FOR
		SELECT i.ID FROM inserted i

		OPEN the_cursor_trig_workspace_insert
		FETCH NEXT FROM the_cursor_trig_workspace_insert INTO @oneid

		WHILE @@FETCH_STATUS = 0
		BEGIN
			declare @Guid NVARCHAR(255), @Plugin NVARCHAR(255)
			select @Guid = Localization, @Plugin = Plugin from SiWorkspace where ID = @oneid
			EXECUTE CreateRightsForAllUser @Guid, @Plugin

			FETCH NEXT FROM the_cursor_trig_workspace_insert INTO @oneid
		END

		CLOSE the_cursor_trig_workspace_insert
		DEALLOCATE the_cursor_trig_workspace_insert
END
```

**Comment by hpposch** [comment]
What i just saw while debugging is that petapoco is generating this code to insert the new entry:
INSERT INTO [SiWorkspace] ([Name],[Parent],[Localization],[Control],[IsFolder],[Plugin],[Glyph]) OUTPUT INSERTED.[ID] VALUES (@0,@1,@2,@3,@4,@5,@6)

I guess there is the problem.

It happens in DatabaseProvider.ExecuteScalarHelper when 
var r = cmd.ExecuteScalar();
is executed

**Comment by pleb** [comment]
I would suggest disabling the trigger to confirm it's causing the problem

**Comment by hpposch** [comment]
I am afraid to say that this is not possible because i need that trigger for my application to work properly..

**Comment by pleb** [comment]
@hpposch Sorry, I think I didn't make myself clear. I'm not saying to remove it and not use a trigger, I'm simply saying disable it to confirm PP works. If it doesn't work, you know the PP configuration is wrong and your issue likely is unrelated to the trigger. If it does work, then you know the trigger is the cause. Knowing which is important at this stage.

**Comment by hpposch** [comment]
Ok i understand what you mean :)
So i already investigated on that and here are the results and what i did.
1. I tried to insert a record with enabled trigger with Microsoft Sql Managment Studio -> Everything Works 
2. I disabled the trigger and tried to insert with petapoco -> Works
3. I enabled the trigger again and tried to insert with petapoco -> Does not work

So i can clearly say that the problem is with petapoco and the trigger.
The trigger itself is fine and works without any problems.
I even debugged my code and stopped before the insert, to copy the values from the entity to insert it later manually.
The result is always the same, if i do it in managment studio it works, if i do it with petapoco i get an exception.

**Comment by hpposch** [comment]
Any idea how to resolve that?

**Comment by pleb** [comment]
If you wanted to try the fix in #201 you can do a custom provider (below), whic you could pass in when constructing a new instance of PP

    public class CustomSqlServerDatabaseProvider : SqlServerDatabaseProvider
    {
        public override string GetInsertOutputClause(string primaryKeyName) => " SELECT SCOPE_IDENTITY()";
    }

**Comment by hpposch** [comment]
Where does this happen?
I have already created the new provider..

**Comment by pleb** [comment]
Another one you may want to try is 

    public class CustomSqlServerDatabaseProvider : SqlServerDatabaseProvider
    {
        public override object ExecuteInsert(Database db, IDbCommand cmd, string primaryKeyName)
        {
            cmd.CommandText = "DECLARE @t TABLE (ID INT PRIMARY KEY); " + cmd.CommandText + "; SELECT @t.ID";

            return ExecuteScalarHelper(db, cmd);
        }

        public override string GetInsertOutputClause(string primaryKeyName)
            => $" OUTPUT INSERTED.[{primaryKeyName}] INTO @t(ID)";
    }

**Comment by pleb** [comment]
See the last example on wiki page https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Ways-to-instantiate-PetaPoco

**Comment by hpposch** [comment]
I know what you mean..
I have the problem that i instantiate my Database with connection string and provider name, because i made a generic code around this..
Therefore i need a way to instantiate my custom connector by provider name, is this possible?

**Comment by hpposch** [comment]
i am getting this as a result:
System.Data.SqlClient.SqlException: "Incorrect syntax near the keyword 'VALUES'."

The result query looks as follows:
INSERT INTO [SiConnectorStorage] ([Name],[IsCore],[Type],[ConnectionString]) SELECT SCOPE_IDENTITY() VALUES (@0,@1,@2,@3)

**Comment by hpposch** [comment]
And the second solution results in:
System.Data.SqlClient.SqlException: "Must declare the scalar variable "@t"."

**Comment by pleb** [comment]
Ah, sorry. Yeah i free handed those. Um, I don’t have my PC with me at the moment. Maybe try the second one. I’ll have a proper look later tonight, if I get time

**Comment by hpposch** [comment]
ok no problem :)
thank you

**Comment by pleb** [comment]
Ok, try this one. 

    public class CustomSqlServerDatabaseProvider : SqlServerDatabaseProvider
    {
        public override object ExecuteInsert(Database db, IDbCommand cmd, string primaryKeyName)
        {
            cmd.CommandText += ";\nSELECT SCOPE_IDENTITY()";
            return ExecuteScalarHelper(db, cmd);
        }
        
        public override string GetInsertOutputClause(string primaryKeyName) => string.Empty;
    }

**Comment by hpposch** [comment]
Thank you, that solved my problem :)
