### ISSUE TITLE
Async Transactions 

### ISSUE THREAD

**Issue by groogiam** [CollaboratingPlatypus/PetaPoco#545]
Are there any plans to add Async calls for transaction? Similar to

https://github.com/tmenier/AsyncPoco/blob/master/AsyncPoco/Database.cs Line 251

**Comment by pleb** [comment]
I think it’s already there

https://github.com/CollaboratingPlatypus/PetaPoco/blob/96639bdf1909c422f776665d00cac1496bffb01b/PetaPoco/Database.cs#L481

**Comment by pleb** [comment]
ah, I think I get it. You’d like a method to begin and return the transaction?

**Comment by groogiam** [comment]
The GetTransactionAsync method does not appear to be implemented. Is it recommended to use the BeginTransaction vs GetTransaction?

**Comment by groogiam** [comment]
Yes. Something like the AsyncPocos BeginTransactionAsync. The usage is a little cleaner.

**Comment by pleb** [comment]
The NPoco implementation seems to smell - IMO. I'd probably just use ambient transactions if you wanted to bypass the PP handling of them.

**Comment by groogiam** [comment]
Sounds good. Thanks for your help.
