### ISSUE TITLE
Typo in Wiki

### ISSUE THREAD

**Issue by davidrot** [CollaboratingPlatypus/PetaPoco#546]
On the following page is a typo, authors alias is not existing in the  query:
https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Multi-Poco-Queries#usage

old:
```
var sql = PetaPoco.Sql.Builder
                .Append("SELECT articles.*, authors.*")
```

new:
```
var sql = PetaPoco.Sql.Builder
                .Append("SELECT articles.*, users.*")
```

**Comment by iadaz** [comment]
Thanks for the correction. Page updated.
