### ISSUE TITLE
Save method crashes

### ISSUE THREAD

**Issue by mergoktas** [CollaboratingPlatypus/PetaPoco#551]
if you call this method for not modified item or not new item, it throws an exception. Since  there is no modified columns, there is no column name in SET part of the produced SQL statement.  I think if an entity is not new or no modification done on it, Save method should just do nothing? Right? Or am I mistaken?

**Comment by asherber** [comment]
Can you give a brief code example?

**Comment by tobarja** [comment]
Note that the Save method uses the (IMHO) naive `IsNew` method to determine if it should issue an insert or update statement. If your primary key is filled in already in your new record, you'll get a DB exception as it tries to update that nonexistent record in the DB.

**Comment by mergoktas** [comment]
I am reading all rows from a table into a SortableBindingList and bind it to a DataGridView. Through
the gridview I modify some of the rows and add some rows too. Since I do not know which items has been modified by means of the SortableBindingList, I apply the Save() method on all items in the bounded list. If the item is newly added or modified by means of the gridview, it works for that item. But if the item is untouched ( not modified) then exception happens. When I debug it, I saw that SET part of the produced SQL statement by Peta-poco has no column names.  This the sql command I got by debuging:

UPDATE dbo.DelayTypes SET  WHERE [ID] = @0
You can see there is no column name, since I have not modified any column. By the way ModifiedColumns is active. I think petapoco should check if ModifiedColumns.Count before calling Update on behalf of Save(). Am I right?

**Comment by asherber** [comment]
I see you're using v5, although I think the same issue exists in v6. 

I think the root of the problem is that `Update(object poco, object primaryKeyValue, IEnumerable<string> columns)` in `Database.cs` should probably check to see if `columns` is empty before proceeding, and return `0` if it is.

(`columns == null` is actually okay; it will update the whole object.)

**Comment by pleb** [comment]
@mergoktas 

The very nice @asherber has identified and fixed this issue for you. It's currently in the **v6 Beta** build.

Please note though, that this fix will not be back ported to V5, and as such, to take advantage of it you'll need to upgrade to **v6 Beta**, then v6 upon release.

V6 does not include T4 template support. If you previously had been generating your entities classes via the T4 template, you can continue to do so by downloading and referencing the T4 template files yourself. 

- See [here](https://github.com/CollaboratingPlatypus/PetaPoco/tree/development/T4Templates)

An alternative is to use the [PetaPoco.DBEntityGenerator](https://github.com/hippasus/PetaPoco.DBEntityGenerator) by @hippasus

**Comment by mergoktas** [comment]
It is good to be hear that is solved.
Thanks

**Comment by mergoktas** [comment]
Sorry for leaving a comment for a closed issue, but I think the correction should be done in petapoco.cs as following since the columns is not null but has no element, means count is zero
      ```
/// <summary>
        ///     Performs an SQL update
        /// </summary>
        /// <param name="poco">The POCO object that specifies the column values to be updated</param>
        /// <param name="columns">The column names of the columns to be updated, or null for all</param>
        /// <returns>The number of affected rows</returns>
        public int Update(object poco, IEnumerable<string> columns) //line 1477
        {
            `if (columns.Count<string>() == 0) return 0; //This line added by mergoktas`
            return Update(poco, null, columns);
        }
```

**Comment by asherber** [comment]
It has indeed been fixed this way in the [current codebase](https://github.com/CollaboratingPlatypus/PetaPoco/blob/development/PetaPoco/Database.cs#L2024). But as @pleb indicated, this fix will not be backported to v5.
