### ISSUE TITLE
Guid PrimaryKey Update Error

### ISSUE THREAD

**Issue by mzy666888** [CollaboratingPlatypus/PetaPoco#553]
I use asp.net core mvc 2.2.
when I use SqlKata.Query create an Update SQL segment.

```
var query = new Query("aspnetusers");
            query.AsUpdate(new {approvalstatus = status});
            query.Where("Id", userId);
            var sql = query.ToSql(CompilerType.MySql);
```

![image](https://user-images.githubusercontent.com/2587129/67137296-3701e300-f265-11e9-9b66-b2efd54b1c42.png)

Update after：error，I find the args 2 Incomplete
```
MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UPDATE `aspnetusers` SET `approvalstatus` = 1 WHERE `Id` = '306338c0-c2cd-405c-9' at line 2
```

**Comment by asherber** [comment]
The error message may be misleading. Can you check `db.LastCommand` after the error?

**Comment by mzy666888** [comment]
I use ExecuteAsync  right.

UpdateAsync wrong

**Comment by asherber** [comment]
What is the value of `db.LastCommand`?

**Comment by mzy666888** [comment]
![image](https://user-images.githubusercontent.com/2587129/67138087-45ee9280-f271-11e9-8e5c-0655026103cc.png)

```
UPDATE `Sql` SET `SQL` = @0, `Arguments` = @1 WHERE `` = @2
	 -> @0 [String] = "UPDATE `aspnetusers` SET `approvalstatus` = @0 WHERE `Id` = @1"
	 -> @1 [Object[]] = "System.Object[]"
	 -> @2 [DBNull] = ""
```

![image](https://user-images.githubusercontent.com/2587129/67138102-69b1d880-f271-11e9-8201-cefee06183a9.png)

**Comment by asherber** [comment]
Ah, okay. When you do `db.Update(sql)`, PetaPoco assumes that the SQL you're passing in is everything after the `UPDATE tablename`. So this works:
```
db.Update<MyClass>("SET approvalstatus=1 where id=12345");
// PetaPoco turns this into "UPDATE MyClass SET approvalstatus=1 where id=12345"
```
But if you're using `AsUpdate()` in SqlKata, then the SQL generated from that already includes `UPDATE MyClass`, and then PetaPoco adds it again.

So if you're building the whole query in SqlKata then `db.Execute()` is correct. `db.Update()` will not work. This is expected behavior.

**Comment by mzy666888** [comment]
OK, Thank you!
