### ISSUE TITLE
'RegexColumns' replace with COUNT(*) has some problems

### ISSUE THREAD

**Issue by feilingdeng** [CollaboratingPlatypus/PetaPoco#555]
just like the following sql:
select [email].[from],[email].[to] from [email]

and the result is like that:
select count(*) from],[email].[to] from [email]

**Comment by pleb** [comment]
What version are you using?

What is the problem?

**Comment by feilingdeng** [comment]
nuget installed: petapoco.complied 6.0.434
the above sql, select columns contains 'from' field,after replace with COUNT(*)  error occurred

**Comment by pleb** [comment]
No worries, can you try version 6.0.415 please?

**Comment by feilingdeng** [comment]
thanks for your reply
6.0.415 same problem,and then i upgrade to 6.0.434,but looks like still.

**Comment by pleb** [comment]
Ok, no worries. Thanks for trying version 6.0.415. I was just making sure it wasn't the latest release causing the problem.

It seems like the regex is getting confused by the `[From]` column. Sadly, this is pretty much consistent with why not to use Regex to parse SQL. But, the trade-off for using Regex is not having to write/support a SQL parse for each language.

To work around this, you're probably going to have to use the full page API where you supply everything that's required

```
Page<T> Page<T>(long page, long itemsPerPage, string sqlCount, object[] countArgs, string sqlPage, object[] pageArgs);
```

or 

```
Task<Page<T>> PageAsync<T>(CancellationToken cancellationToken, long page, long itemsPerPage, string sqlCount, object[] countArgs, string sqlPage, object[] pageArgs);
```

**Comment by feilingdeng** [comment]
thank you. that's great!
