### ISSUE TITLE
Find Page Time consuming

### ISSUE THREAD

**Issue by mzy666888** [CollaboratingPlatypus/PetaPoco#556]
I use Page function，on web  time consuming，I log time
 On Mariadb ,the table only 4 rows data.

```
Stopwatch stop = new Stopwatch();
            stop.Start();
            var pages = await _context.PageAsync<ProductDto>(page, itemsPerPage);

            stop.Stop();
            _logger.Information($"Async查询的执行时间:{stop.Elapsed}");

            stop.Restart();
            var ps =  _context.Page<ProductDto>(page, itemsPerPage);

            stop.Stop();
            _logger.Information($"查询的执行时间:{stop.Elapsed}");
            stop.Restart();

            var x = _mapper.Map<Page<ProductViewModel>>(pages);
            stop.Stop();
            _logger.Information($"Mapper的执行时间:{stop.Elapsed}");
```

![image](https://user-images.githubusercontent.com/2587129/67350122-63c33c80-f57c-11e9-81fe-a58242481138.png)

**Comment by pleb** [comment]
@mzy666888 It's on the [roadmap](https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Roadmap) to make this easier.

For now, I would look at the following events you can subscribe to

        /// <summary>
        ///     Occurs when a database command is about to be executed.
        /// </summary>
        public event EventHandler<DbCommandEventArgs> CommandExecuting;

        /// <summary>
        ///     Occurs when a database command has been executed.
        /// </summary>
        public event EventHandler<DbCommandEventArgs> CommandExecuted;

**Comment by feilingdeng** [comment]
i also got this problem, then i tried to downgrade one by one，the version 6.0.415 is stable.

**Comment by pleb** [comment]
Oh, right. I think I understand. I thought @mzy666888 found timing page loads, with regards to PetaPoco, time consuming. I see now

**Comment by mzy666888** [comment]
I use `Page` or `PageAsync`with `order by`  very fast, but no with `order by` very slow.

**Comment by ArgoZhang** [comment]
@mzy666888 please review Issue #548  

u can add my QQ:5196060

**Comment by ArgoZhang** [comment]
> I use `Page` or `PageAsync`with `order by` very fast, but no with `order by` very slow.

order by is required by Page method even use sql
