### ISSUE TITLE
AnsiString  and nulls

### ISSUE THREAD

**Issue by abbottmw** [CollaboratingPlatypus/PetaPoco#557]
I haven't found if this has been reported, or if I am using this wrong.  I am using PetaPoco v 5.1.259   and when you use new PetaPoco.AnsiString(str)  and str is null, it throws an error. 

Is this working as designed?  Is there a way around this issue?

**Comment by asherber** [comment]
Thanks, good catch. I've submitted a PR to fix this, but I suspect the fix will only go to v6, not to v5.
