### ISSUE TITLE
Pluralize table names

### ISSUE THREAD

**Issue by hmihail** [CollaboratingPlatypus/PetaPoco#561]
I want to use plural table names, and I get an error that table 'Products' not found, but the table is there. My code is like this:

```
   var db = DatabaseConfiguration.Build()
                .UsingConnectionString(_connectionString)
                .UsingProviderName(_providerName)
                .UsingDefaultMapper<ConventionMapper>(m =>
                {
                    // Pluralize table names
                    m.InflectTableName = (inflector, tn) => inflector.Pluralise(tn);
                })
                .Create();
```
Am I missing something, or doing something wrong?

**Comment by asherber** [comment]
I'm not able to reproduce this at the moment. 

Can you share more of your code -- your POCO definition? How you are fetching records?

**Comment by ArgoZhang** [comment]
need more info for `inflector.Pluralise(tn)` method and POCO definition

**Comment by asherber** [comment]
(The `Inflector` code is [part of PetaPoco](https://github.com/CollaboratingPlatypus/PetaPoco/blob/development/PetaPoco/Core/Inflection/EnglishInflector.cs).)

**Comment by ArgoZhang** [comment]
great! not used the Pluralise method yet. :smail

**Comment by hmihail** [comment]
Looks like it is related to Firebird, where column names are case sensitive. I solved it by adding `m.InflectColumnName = (inflector, cn) => cn.ToUpper();`
