### ISSUE TITLE
byte[], Binary, PreExecute

### ISSUE THREAD

**Issue by asherber** [CollaboratingPlatypus/PetaPoco#562]
I'm working with an oddball database engine for which I wrote my own custom `DatabaseProvider`. This database has a `Blob` field type, which I can read just fine using a `byte[]` property. But when I try to write to a table with one of those fields, I get `ArgumentException: Unable to infer parameter data type`. This has led me to a couple of questions.

1. **Should `byte[]` automatically map to `DbType.Binary`?** There is no code in `Database.SetParameterProperties()` to handle `byte[]` -- except when the parameter value is null and the property type is `byte[]`, in which case the `DbType` does get set to `Binary`. It seems like always treating `byte[]` as `Binary` would be a good thing. (NPoco does this, FWIW.)

1. **Should `DatabaseProvider.PreExecute()` get called in a different place?** I initially worked around my issue by using the `Database.CommandExecuting` event and setting the `DbType` to `Binary` for any `byte[]` properties. Then I thought that since `SetParameterProperties()` doesn't handle this globally, I could use `PreExecute()` in my `DatabaseProvider` to accomplish the same thing. The help text for `PreExecute()` says "Called immediately before a command is executed", but in fact it's called as part of `Database.CreateCommand()`. This means that for Insert and Update operations, `PreExecute()` sees the `DbCommand` object before any SQL or parameters have been added, which isn't very useful. What about calling `_provider.PreExecute()` as part of `Database.DoPreExecute()`, which does get called as part of every db call?

I'm happy to work on PRs for these.

**Comment by pleb** [comment]
Both sound good. Good for it ;)
