### ISSUE TITLE
Horrible performance using Async methods with large data

### ISSUE THREAD

**Issue by QianMoXi** [CollaboratingPlatypus/PetaPoco#570]
I use the FetchAsync method to query the large data, but it is very slow。

This question already has an answer here:
[https://stackoverflow.com/questions/42415969/horrible-performance-using-sqlcommand-async-methods-with-large-data](url)
We need to call ExecuteReaderAsync with CommandBehavior.SequentialAccess.

It works well in my tests.
But I'm not sure it's going to have any bad effects.

**Comment by pleb** [comment]
> Query vs Fetch
The Database class has two methods for retrieving records Query and Fetch. These are pretty much identical except Fetch returns a List<> of POCO's whereas Query uses yield return to iterate over the results without loading the whole set into memory.

You're probably causing excessive memory load, and likely, garbage collection load

**Comment by QianMoXi** [comment]
> > Query vs Fetch
> > The Database class has two methods for retrieving records Query and Fetch. These are pretty much identical except Fetch returns a List<> of POCO's whereas Query uses yield return to iterate over the results without loading the whole set into memory.
> 
> You're probably causing excessive memory load, and likely, garbage collection load

You are right. I found this problem.
 I will use another way to query data.
