### ISSUE TITLE
Does Petapoco work with Asp.net core 3+?

### ISSUE THREAD

**Issue by biapar** [CollaboratingPlatypus/PetaPoco#574]
Does Petapoco work with Asp.net core 3+?

**Comment by pleb** [comment]
Yes

**Comment by biapar** [comment]
Thanks.
Strange, but I install it with nuget but nit see the namespace.
________________________________
Da: Wade Baglin <notifications@github.com>
Inviato: lunedì 20 aprile 2020 10:12
A: CollaboratingPlatypus/PetaPoco <PetaPoco@noreply.github.com>
Cc: BIAGIO PARUOLO <biapar@redconsulting.it>; Author <author@noreply.github.com>
Oggetto: Re: [CollaboratingPlatypus/PetaPoco] Does Petapoco work with Asp.net core 3+? (#574)


Yes

**Comment by pleb** [comment]
Make sure you’re using https://www.nuget.org/packages/PetaPoco.Compiled/

**Comment by biapar** [comment]
Why Is there another package?

**Comment by pleb** [comment]
They are actually three packages. 

The `PetaPoco` package was original a version which copied a file into the solution upon adding the nuget package. Somewhat popular back in the day. 

The second is `PetaPoco.Core` which was the `PetaPoco` package without the T4 template (nothing to do with .net core which came out 5 or so years later). 

And the last, `PetaPoco.Compiled` the package the more modern package which doesn't include the T4 templates and is a compiled assembly file (the more popular modern-day delivery method) **and the only version to support .net standard (usable via the .net core runtime).

Yep... WHAT A MESS

But, there's not much we can do without breaking existing solutions/ci-cd pipelines

**Comment by biapar** [comment]
Ok. I understand , now. Thanks.
