### ISSUE TITLE
Explicit transactions mode for queuing commands

### ISSUE THREAD

**Issue by nhaberl** [CollaboratingPlatypus/PetaPoco#575]
For some DDD scenarios I would have the demand of storing statements / commands in a kind of queue but they should only be executed when calling COMMIT explicitely as a batch.

Is there a way of queuing commands or batch processing?

Problem is that I have huge write operations with lot of business logic and I have the need that some instances in code execute commands separately but should remain in one single transaction

**Comment by asherber** [comment]
Yes, PetaPoco supports transactions: https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Transactions

**Comment by nhaberl** [comment]
Thanks, but it's not what I was asking ... what I need is some sort of queuing commands and commiting at last possible point in time. (like context in EF)

E.g. when you call db.Insert(...) the command is executed immediately but I would like to queue it until all commands are sent to PetaPoco Database and when doing something like db.SaveChanges() all the commands gets executed.

So the thing to do is "parking" all internal commands and manually release it.

**Comment by asherber** [comment]
Ah, okay. PP doesn't support anything like that, but I wonder if you could accomplish something similar by accumulating your db commands in a list.
```csharp
var commandQueue= new List<Action>();
commandQueue.Add(() => db.Insert(...));

...

db.BeginTransaction();
commandQueue.ForEach(c => c());
db.CompleteTransaction();
```
You could even create your own `Database` descendant and give it a `CommandQueue` property and an `ExecuteQueue()` method.

**Comment by nhaberl** [comment]
@asherber sounds good !
I will try that!
