### ISSUE TITLE
Support for hierarchy id

### ISSUE THREAD

**Issue by cklenk** [CollaboratingPlatypus/PetaPoco#576]
Hello, I can't seem to find information on this. Does PetaPoco support the hierarchyid sql data type? Or is that an issue with LINQ? I'm trying to just do a simple Get by Id on a table that has hierarchyid as one of the columns. Does everything have to be done through stored procedures, or is some sort of cast needed?

Thanks

**Comment by pleb** [comment]
Hey @cklenk, I've posted an answer to your SO [question](https://stackoverflow.com/questions/61525248/dnn-mvc-module-with-sql-hierarchy-id/61535690#61535690).
