### ISSUE TITLE
Which databases Do it support?

### ISSUE THREAD

**Issue by biapar** [CollaboratingPlatypus/PetaPoco#578]
Which databases Do it support?

**Comment by iadaz** [comment]
There's a list in the Wiki, although you can write a custom DBProvider for an unsupported platform yourself. https://github.com/CollaboratingPlatypus/PetaPoco/wiki/DB-Providers

**Comment by asherber** [comment]
Please see: https://github.com/CollaboratingPlatypus/PetaPoco/wiki/DB-Providers

**Comment by biapar** [comment]
Thx.

**Comment by biapar** [comment]
What Do you mean with "Nothing noteworthy"? That is not supported?

**Comment by asherber** [comment]
All the DBs listed on the page are supported. 'Nothing noteworthy' just means that there are no special notes regarding usage.
