### ISSUE TITLE
Question: How to create table from POCO Class?

### ISSUE THREAD

**Issue by biapar** [CollaboratingPlatypus/PetaPoco#583]
Hi,

Is there a command to create / delete table from class as I see into Umbraco CMS?

**Comment by asherber** [comment]
No.

**Comment by biapar** [comment]
Maybe an'idea: https://github.com/umbraco/Umbraco-CMS/blob/9ffb3bed571af2be853127064514983d56501f25/src/Umbraco.Core/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs

**Comment by pleb** [comment]
Happy for a PR and Doc update. However, no plans to add it myself
