### ISSUE TITLE
DECLARE causes errors with SQL parsing parameters

### ISSUE THREAD

**Issue by jakcharlton** [CollaboratingPlatypus/PetaPoco#59]
I have a query somewhat similar to the following (though considerably more complex):

DECLARE @rates TABLE (
      ID INT PRIMARY KEY
      , Value float
)

INSERT @rates SELECT  ID, Value FROM OtherTable

SELECT \* FROM @rates

But this produces an exception:
[ArgumentException: Parameter '@rates' specified but none of the passed arguments have a property with this name (in '

It seems PetaPoco is assuming that anything with @ against it is a supplied parameter?

**Comment by naughtyGitCat** [comment]
> Yeah. I'm looking at being able to set the parameter value (currently @) to whatever you like, so for sql server you might choose ":". It will then convert them to @ before running the sql.

Is there some helper to  escape any @ in sql string?

**Comment by asherber** [comment]
See above -- you can escape it by using @@.

**Comment by naughtyGitCat** [comment]
> See above -- you can escape it by using @@.

I have tried with `TargetString.Replace("@","@@")`

but the final result is @@ in TargetString, not  single @

**Comment by asherber** [comment]
Can you post a short code example?
