### ISSUE TITLE
Support for Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by AsifulNobel** [CollaboratingPlatypus/PetaPoco#591]
Is there any plan to support Microsoft.Data.SqlClient instead of System.Data.SqlClient?

**Comment by pleb** [comment]
It's a pretty small change. I might have time over the next few weeks or so. If you think you have the skill, are you able to submit a PR? In the meantime, as PetaPoco is a ado.net wrapper, you can simply supply the connection and do the connection management yourself :)

**Comment by AsifulNobel** [comment]
Thanks for the info. I used the connection string class from Microsoft.Data.SqlClient.
