### ISSUE TITLE
Page<T> Page<T>(long page, long itemsPerPage, Sql sql) Slow implementation

### ISSUE THREAD

**Issue by nk-rotten** [CollaboratingPlatypus/PetaPoco#593]
Very slow when SQL is “select * from tableName where id in (1,2,3,4,5,6......)”, After checking the source code, it is found that it is caused by regular

  public Regex RegexOrderBy =
            new Regex(
                @"\bORDER\s+BY\s+(?!.*?(?:\)|\s+)AS\s)(?:\((?>\((?<depth>)|\)(?<-depth>)|.?)*(?(depth)(?!))\)|[\[\]`""\w\(\)\.])+(?:\s+(?:ASC|DESC))?(?:\s*,\s*(?:\((?>\((?<depth>)|\)(?<-depth>)|.?)*(?(depth)(?!))\)|[\[\]`""\w\(\)\.])+(?:\s+(?:ASC|DESC))?)*",
                RegexOptions.RightToLeft | RegexOptions.IgnoreCase | RegexOptions.Multiline | RegexOptions.Singleline | RegexOptions.Compiled);

**Comment by pleb** [comment]
@nk-rotten many people have attempted to optimise the regx over the years. I don't believe there will ever be a perfect solution. My only advice is to use the paging features where it makes sense and to do the paging yourself where it doesn't.
