### ISSUE TITLE
Add Support for Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by EricRohlfs** [CollaboratingPlatypus/PetaPoco#594]
Please consider adding provider support for Microsoft.Data.SqlClient.

In our use case, we have extra paperwork we have to fill out for libraries used in our applications. Since EntityFramework is already approved and it uses Microsoft.Data.SqlClient , that is just one less piece of paperwork I need to fill out. 

Also, according to Microsoft, Microsoft.Data.SqlClient is the way forward for new stuff.

**Comment by iadaz** [comment]
To use Microsoft.Data.SqlClient with PetaPoco now you should just be able to create your own class inheriting from DatabaseProvider (which will just be a copy of SqlServerDatabaseProvider) and update the GetFactory parameter. Then pass your new provider into DatabaseConfiguration.Build().

I'm not saying direct support for Microsoft.Data.SqlClient wouldn't be welcome. But it's not my call. See the similar question regarding MySQL connectors here: https://github.com/CollaboratingPlatypus/PetaPoco/issues/586

**Comment by pleb** [comment]
I've added support for the new MS Data Sql Client.

Let me know how you go ;)

https://www.nuget.org/packages/PetaPoco.Compiled/6.0.466-beta

**Comment by EricRohlfs** [comment]
Thank you, this is a big help.  I'll pivot to testing this out next week.

**Comment by iadaz** [comment]
I've been using Microsoft.Data.SqlClient  in a new .net 5 application. No issues so far.

**Comment by michaelmarziani** [comment]
I've been using this to initialize PetaPoco:

```csharp
var db = new PetaPoco.Database(connectionString, "Microsoft.Data.SqlClient");
```

I notice that when I see DB Exceptions they are coming through as `Microsoft.Data.SqlClient.SqlException`. This is a .NET 6 project.
