### ISSUE TITLE
@picasso566 I was thinking that if the code gen feature is kept, it would be best as a dotnet tool (https://github.com/aspnet/DotNetTools/)

### ISSUE THREAD

**Issue by Quttia** [CollaboratingPlatypus/PetaPoco#597]
@picasso566 I was thinking that if the code gen feature is kept, it would be best as a dotnet tool (https://github.com/aspnet/DotNetTools/)

Before the current netcore sdk release, a dotnet tool was installed to the local project. However, now it can also be global. This reminds a little of NPM - if you've ever used it.

As for the API maybe, and this is just me thinking out loud....

    dotnet petapoco generate --connection-string "sdfsdfsdf" --out-location "\Project\Data\Models" --filter-out "%User%" --filter "%Ordre%" --template "Default"|"Single file"

    dotnet petapoco generate -cs "sdfsdfsdf" -ol "\Project\Data\Models" -fo "%User%" -f "%Ordre%" -t "Default"|"Single file"

Minimum

    dotnet petapoco generate -cs "sdfsdfsdf" -ol "\Project\Data\Models"

after the first call is made, a shorter path to re-running it (would involve saving previous options)

    dotnet petapoco update

_Originally posted by @pleb in https://github.com/CollaboratingPlatypus/PetaPoco/issues/460#issuecomment-402326588_

**Comment by Quttia** [comment]
@pleb hello, Does this feature carry out?

**Comment by pleb** [comment]
Give  #368 a read. 

The closes thing to this would be https://github.com/hippasus/PetaPoco.DBEntityGenerator
