### ISSUE TITLE
ExecuteReader requires an open and available Connection. The connection's current state is closed.

### ISSUE THREAD

**Issue by kion-admin** [CollaboratingPlatypus/PetaPoco#598]
Hello, i using autofac in my .net core project for di

I have customdatabase class

`    public class CustomDatabase : Database
    {
        public CustomDatabase(IDbConnection connection) : base(connection)
        {

        }

        public CustomDatabase(string connectionString) : this(new SqlConnection(connectionString))
        {
        }
    }`

and my class use it like that

`    public class UserOps 
    {
        private readyonly CustomDatabase _database;
        public UserOps(CustomDatabase database) 
        {
            _database = databse;
        }

        public List<SelectListItemDto> getGroupList()
        {

            {
                var resultItem = Database.Fetch<SelectListItemDto>(";exec sp_03_30_Group_List");
                 return resultItem;
            }

        }`
........
}

any my autofac config like bellow

`            builder.RegisterType<CustomDatabase>()
                .WithParameter((pi, c) => pi.Name == "connectionString",
                    (pi, c) => "CONNECTIONSTRING")
                .InstancePerLifetimeScope();`

but its throw ExecuteReader requires an open and available Connection. The connection's current state is closed. error

if i change my CustomDatabase class like bellow its working

`    public class CustomDatabase : Database
    {
        public CustomDatabase(IDbConnection connection) : base(connection)
        {
                   if (connection.State == ConnectionState.Broken)
                connection.Close();
            if (connection.State == ConnectionState.Closed)
                connection.Open();
        }

        public CustomDatabase(string connectionString) : this(new SqlConnection(connectionString))
        {
        }
    }`

so why i have to open connection in ctor i saw source code already petapoco open sharedconnection if closed, sharedconnection is it diffirent from connection?

**Comment by asherber** [comment]
If you pass in a connection string, PetaPoco creates the connection and will open it and dispose of it for you. If you pass in an actual connection, you are responsible for opening it and disposing of it yourself.

**Comment by kion-admin** [comment]
thank you for the quick turnaround
