### ISSUE TITLE
Add support for Snowflake database

### ISSUE THREAD

**Issue by shortgrass** [CollaboratingPlatypus/PetaPoco#599]
Many of our data warehouse databases are being migrated from Oracle to Snowflake.  I was able to get PetaPoco partially working with Snowflake by creating an implementation of the DatabaseProvider class.  Query calls that use parameters don't work.  Is there any plan to support Snowflake?  Is there any guidance you can provide for what the DataProvider class should implement for Snowflake?

**Comment by pleb** [comment]
@shortgrass there's no immediate plan to support Snowflake. If you want to add it, the steps would be 

1) Add the prodivder
2) Update the integration tests
3) Get all the tests working
