### ISSUE TITLE
How to map table POCO names

### ISSUE THREAD

**Issue by LeifUK** [CollaboratingPlatypus/PetaPoco#601]
I'm using PetaPoco.NetCore and I have objects and tables with names like Attribute and attributes respectively. I'm trying to figure out how to allow this without having to decorate the POCO class definitions, as that ties each POCO to PetaPoco. 
    
This is what I don't want: 

    [TableName("attributes")]
    public class Attribute : IObject
    {
        public Int64 id { get; set; }
        public Int64 key_id { get; set; }
        public string description { get; set; }
    }

This is what I want: 

    public class Attribute : IObject
    {
        public Int64 id { get; set; }
        public Int64 key_id { get; set; }
        public string description { get; set; }
    }

I've checked this page out: 

https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Mapping-Pocos

But I can't understand it, what is UsingDefaultMapper for example? It looks like I have to set the Mapper static with an instance of a class derived from IMapper, that looks like a nightmare to do, and removes the benefits of PetaPoco ie less work than native SQL code.

**Comment by asherber** [comment]
PetaPoco uses a mapper to determine how to map between class names and table names, and between property names and column names (and a couple of other things, but those are the main ones). The default mapper that you get by doing nothing assumes that class names and table names are the same; in your case, it looks like you need a mapper that tells PetaPoco that your class names are singular but your table names are plural.

There are a few different ways of doing this. If you're using fluent configuration, you can do something like this:

```csharp
var config = DatabaseConfiguration.Build()
    .UsingConnectionStringName("foo")
    .UsingDefaultMapper<ConventionMapper>(m =>
     {
         // Attribute becomes Attributes
         m.InflectTableName = (inflector, tn) => inflector.Pluralise(tn);
    })

using (var db = new Database(config))
{
    ...
}
```
Note that `InflectTableName` gives you an inflector object that you can use to handle the pluralization. 

If you're not using fluent configuration, or if you're using fluent in multiple places, you can create your own mapper class somewhere in a few lines of code and then use that.
```csharp
public class MyPluralMapper : ConventionMapper
{
    public MyPluralMapper()
    {
        InflectTableName = (i, tn) => i.Pluralise(tn);
    }
}

using (var db = new Database("foo", new MyPluralMapper())
{
    ...
}

// OR

var config = DatabaseConfiguration.Build()
    .UsingConnectionStringName("foo")
    .UsingDefaultMapper<MyPluralMapper>();

using (var db = new Database(config))
{
    ...
}
```

**Comment by LeifUK** [comment]
Thank you. Very helpful.
