### ISSUE TITLE
Unable to instantiate database object using connectionStringName

### ISSUE THREAD

**Issue by andyle2k** [CollaboratingPlatypus/PetaPoco#606]
Hi, probably very stupid newbie question but switching to v6 + (.net Core) I am unable to construct the database object by using 

`public Database(string connectionStringName, IMapper defaultMapper = null) `

as per wiki "Traditional Constructor".

Checking the assembly, this constructor method isn't even present in version 6.0.480.0. 

I can understand the need to remove it and force a provider. For .net Core you cannot assume there is a (valid) provider referenced. However, there's still a constructor with

`public Database(string connectionString, string providerName, IMapper defaultMapper = null);`

which takes a provider name as a string anyway so is that better than including the provider in the connection string itself?

Obviously I'm extremely ignorant here so some education is greatly appreciated.

Also, does this mean the wiki entry needs updating?

Thank you very much. P.S. I forgot to mention that I've been a huge fan of PetaPoco and have been using it for years so I very much am grateful for all you do.

**Comment by asherber** [comment]
.NET Core apps do not include the same web.config/app.config files that Framework apps do, and they don't have the `ConfigurationManager` class -- so they can't automatically read connection strings by name the way that Framework apps can. If you're working in .NET Core, it's up to you to get the connection string and provider information however you like and give them to the constructor.

**Comment by andyle2k** [comment]
Thank you, I assumed as much so I wasn't too hung up on the `ConfigurationManager` aspect I was happy to let that go.

I've just got to re-write my helper methods which used to:
`var list = PPHelp.GetList<ObjectType>(string connectionStringName, string tableName = null, string conditions = null)`

Now I'm thinking the best I can do is probably something like:

```
using (System.Data.IDbConnection dbConnection = new SqlConnection(connectionString))
{
   var db = new PetaPoco.Database(dbConnection);
   var list = db.GetList<ObjectType>(string tableName = null, string conditions = null);
}

```

Off the top of my head, I'm sure there's a better/efficient way to do this.

Thanks again.

**Comment by asherber** [comment]
If you do things that way, note that you have to open the connection yourself before calling any PetaPoco methods; PetaPoco assumes that you're managing any connection you provide.

But if you already have the connection string, and you know that it's SqlServer, you can also do one of the following.

```csharp
using (var db = new Database(connectionString, "SqlServer"))
{

}

using (var db = new Database<SqlServerDatabaseProvider>(connectionString))
{

}
```

**Comment by andyle2k** [comment]
Great! I will definitely give that a go.

Anyway, your first comment already answered my question as to why the constructor methods were changed so I'm happy to close this.

Thank you.
