### ISSUE TITLE
When autoincrement identity column is not primary column, Insert and Save methods throw exception

### ISSUE THREAD

**Issue by mergoktas** [CollaboratingPlatypus/PetaPoco#607]
I use sql server express 2019 and My poco class is as follows

    [TableName("[dbo].[DELAY_REASON]")]
    [PrimaryKey("ID")]
    [ExplicitColumns]
    public partial class DELAY_REASON : Record<DELAY_REASON>
    {
        [Column]
        public int ID
        {
            get { return _ID; }
            set { _ID = value; MarkColumnModified("ID");}
        }
        private int _ID;

        [Column]
        public int CODE
        {
            get { return _CODE; }
            set { _CODE = value; MarkColumnModified("ID"); }
        }
        private int _CODE;

        [Column]
        public string DESCRIPTION
        {
            get { return _DESCRIPTION; }
            set { _DESCRIPTION = value; MarkColumnModified("DESCRIPTION");}
        }
        private string _DESCRIPTION;
        
    }
	
If I create the table like following
USE [MYDB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DELAY_REASON](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CODE] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Reasons] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

then code following

var r = new DELAY_REASON { CODE = 3, DESCRIPTION = "Automatic detection3"};
db.Insert(r);

works just fine. But ID column does not have to be primary key column always. 
So I altered the DELAY_REASON table's primary key as CODE column and changed my poco as like

    [TableName("[dbo].[DELAY_REASON]")]
    [PrimaryKey("CODE")]
    [ExplicitColumns]
    public partial class DELAY_REASON : Record<DELAY_REASON>
	....
	
and  then try to run
var r = new DELAY_REASON { CODE = 5, DESCRIPTION = "Automatic detection5"};
db.Insert(r);

is not working giving the following exception

System.Data.SqlClient.SqlException: 'Cannot insert explicit value for identity column in table 'DELAY_REASON' when IDENTITY_INSERT is set to OFF.'

Meanwhile through the sql server manager, editing the DELAY_REASON table directly, it is possible to give value to primary key column
and auto increment ID column has its own value from db manager.

I think the Save and Insert methods should also work when auto increnent ID column is not the primary key column.

**Comment by iadaz** [comment]
I think you should set IDENTITY_INSERT yourself before inserting the record, using `Execute` (and turn it off afterwards). That's what SSMS does when you're inserting data manually.

If PetaPoco were to try to manage this it may not work consistently depending on whether PP is managing the connection or using a supplied connection, because SQL only supports one table having IDENTITY_INSERT set to on:

> At any time, only one table in a session can have the IDENTITY_INSERT property set to ON. If a table already has this property set to ON, and a SET IDENTITY_INSERT ON statement is issued for another table, SQL Server returns an error message that states SET IDENTITY_INSERT is already ON and reports the table it is set ON for.

So PP can't assume this would be needed for every table, or for every insert into one particular table, therefore it would need additional overloads of Insert to enable this. These probably wouldn't be applicable to all of the database servers that PP supports. I think creating your own extension method that wraps the call to `Insert` would be a better solution.

**Comment by asherber** [comment]
I think this would work if you mark `ID` with the `ResultColumn` attribute. This tells PP not to include the column in insert or update queries. 

Note that if you want the column to be included in auto generated select queries, you need to specify `IncludeInAutoSelect.Yes` as well. See https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Mapping-Pocos#mapping-attributes

**Comment by mergoktas** [comment]
This my new poco. ID column is the identity column, CODE column is primary key.
They are same in the database table too.

[TableName("[dbo].[DELAY_REASON]")]
[PrimaryKey("CODE")]
[ExplicitColumns]
public partial class DELAY_REASON
        : Record<DELAY_REASON>
    {
        [ResultColumn(IncludeInAutoSelect.Yes)]
        public int ID
        {
            get { return _ID; }
            set
            {
                _ID = value;
                MarkColumnModified("ID");
            }
        }
        private int _ID;

        [Column]
        public int CODE
        {
            get { return _CODE; }
            set
            {
                _CODE = value;
                MarkColumnModified("CODE");
            }
        }
        private int _CODE;

        [Column]
        public string DESCRIPTION
        {
            get { return _DESCRIPTION; }
            set
            {
                _DESCRIPTION = value;
                MarkColumnModified("DESCRIPTION");
            }
        }
        private string _DESCRIPTION;      
    }

When run the following code,

DELAY_REASON r2 = new DELAY_REASON
{
    CODE = 10,
    DESCRIPTION = "Automatic detection10"

};
// Here ModifedColumns Count = 2 which is normal (CODE and DESCRIPTION are in the dictionary)
db.Insert(r2); // this line throws exception below

System.Data.SqlClient.SqlException: 'Cannot insert the value NULL into column 'CODE', table 'MYDB.dbo.DELAY_REASON'; column does not allow nulls. INSERT fails.'

db.LastCommand : INSERT INTO [dbo].[DELAY_REASON] ([DESCRIPTION]) OUTPUT INSERTED.[CODE] VALUES (@0)
	 -> @0 [String] = "Automatic detection10"
db.LastSQL: INSERT INTO [dbo].[DELAY_REASON] ([DESCRIPTION]) OUTPUT INSERTED.[CODE] VALUES (@0)	 

Why the CODE column (PK) does not exist in INSERT sql statement?

**Comment by mergoktas** [comment]
Mr. iadaz,
My aim is that,
ID column will be autoincrement Identity column so that I would not insert the value myself,
CODE column will be PK column that I will supply the value myself
whatever other columns are as usual columns and I expect the following code part to execute without an error

DELAY_REASON r2 = new DELAY_REASON
{
   CODE = 10,
   DESCRIPTION = "Automatic detection10"
};
// Here ModifedColumns Count = 2 which is normal (CODE and DESCRIPTION are in the dictionary)
db.Insert(r2); // this line throws exception below

Regards

**Comment by iadaz** [comment]
I think you probably want:

`[PrimaryKey("CODE", AutoIncrement = false)]`

...so that PP knows the CODE value isn't generated by the database.

**Comment by mergoktas** [comment]
Yes,
[PrimaryKey("CODE", AutoIncrement = false)] this works.
Thanks alot
