### ISSUE TITLE
Scalar to boolean

### ISSUE THREAD

**Issue by gentryr1987** [CollaboratingPlatypus/PetaPoco#616]
When I use ExecuteScalar or ExecuteScalarProc and try to convert a bit to a bool, the bit is the opposite of what it is supposed to be.

Here is my sample code:
DB.ExecuteScalarProc<bool>("ReProcessMemberData", new { Id })

When that proc is run it returns a 1 which should mean true, but the function is returning false. When I flipped the bit to 0, it returned true.

**Comment by asherber** [comment]
`ExecuteScalarProc()` is a generic function and needs a type argument. Are you saying that `ExecuteScalarProc<int>()` returns `1`, but `ExecuteScalarProc<bool>()` returns `false`?

**Comment by gentryr1987** [comment]
Sorry, I think think the type argument was removed because I didn't specify it was code.

`DB.ExecuteScalarProc<bool>("ReProcessMemberData", new { Id })`

It is returning false even though the stored proc is returning 1

Here is the code being executed in my stored proc `SELECT CAST(1 AS BIT)`

**Comment by asherber** [comment]
The following works as expected for me:

```sql
CREATE PROCEDURE MyProc AS BEGIN
    SELECT 1
END
```

```c#
using (var db = new Database(...))
{
    var foo = db.ExecuteScalarProc<bool>("MyProc");  // true
    var bar = db.ExecuteScalarProc<int>("MyProc");   // 1
}
```

**Comment by asherber** [comment]
The code I have above works for me even if I change the proc to `SELECT (1 as BIT).`

**Comment by asherber** [comment]
@gentryr1987 What do you get if you call `DB.ExecuteScalarProc<int>("ReProcessMemberData", new { Id })` ?

**Comment by gentryr1987** [comment]
I removed the cast and it is working correctly now.

**Comment by gentryr1987** [comment]
Thanks for your help.
