### ISSUE TITLE
Sqlite Mapper

### ISSUE THREAD

**Issue by nhaberl** [CollaboratingPlatypus/PetaPoco#620]
Is there anywhere a sqlite mapper which maps all .NET types to sqlite ? Or where can I find an existing mapper to fit my needs for sqlite ? I have seen the example for datetime but is there anything already for any other type ? Like GUIDs and so on ?

**Comment by nhaberl** [comment]
Sorry I guess it works (I am evaluating) but would like to know how .NET dataypes are converted ... like GUIDs as there is no adequate datatype its going to be serialzed as blob or as string. I am loking through the source and for datetime it's clear. Just that I know what converters I have to code or custom mappers or whatever.
So is more an informational question than a bug report ... sorry (would like to store the date as iso8601 string)

**Comment by asherber** [comment]
For most uses, I think you shouldn't need to code any custom converters or mappers. SQLite doesn't have many native data types, so anything text-like will be serialized as text.

Here's some Linqpad code demonstrating basic usage with DateTime and Blob, and no custom code.

```csharp
void Main()
{
    var config = DatabaseConfiguration.Build()
        .UsingConnectionString("Data Source=:memory:")
        .UsingProvider<SQLiteDatabaseProvider>();
        
    using (var db = new Database(config))
    {
        db.KeepConnectionAlive = true;
        
        db.Execute("CREATE TABLE IF NOT EXISTS Foo (ID INTEGER PRIMARY KEY, Date TEXT, Guid TEXT)");
        db.Insert(new Foo() { ID = 1, Date = DateTime.Now, Guid = Guid.NewGuid() });
        db.Fetch<Foo>().Dump();
    }
}

public class Foo
{
    public int ID { get; set; }
    public DateTime Date { get; set; }
    public Guid Guid { get; set; }
}
```

The output is:

![image](https://user-images.githubusercontent.com/5248041/130098482-1a9c6440-d142-4a65-a3ce-f336504321bd.png)

**Comment by asherber** [comment]
If you explicitly want to store DateTimes in ISO format, there are a couple of ways to do it. One would be to implement your own custom mapper.

```csharp
public class MyMapper : ConventionMapper
{
    public override Func<object, object> GetToDbConverter(PropertyInfo sourceProperty)
    {
        if (sourceProperty.PropertyType == typeof(DateTime))
            return o => ((DateTime)o).ToString("O");
        else
            return base.GetToDbConverter(sourceProperty);
    }
}

var config = DatabaseConfiguration.Build()
    .UsingConnectionString("Data Source=:memory:")
    .UsingProvider<SQLiteDatabaseProvider>()
    .UsingDefaultMapper<MyMapper>();
```

You could also do this with a ValueConverter instead of a mapper, but then you'd need to explicitly decorate each DateTime property in order to apply the converter.

```csharp
public class IsoDateConverter : ValueConverterAttribute
{
    public override object ConvertFromDb(object value)
    {
        return DateTime.Parse(value.ToString());
    }

    public override object ConvertToDb(object value)
    {
        return ((DateTime)value).ToString("O");
    }
}

public class Foo
{
    public int ID { get; set; }
    [IsoDateConverter]
    public DateTime Date { get; set; }
    public Guid Guid { get; set; }
}
```
