### ISSUE TITLE
SingleOrDefaultAsync(object primaryKey) is quoting the pk when it passing in int.

### ISSUE THREAD

**Issue by bnowlin** [CollaboratingPlatypus/PetaPoco#625]
Provider: Npgsql

ID is postgres type integer. Primary key with identity field.

```csharp
    [TableName("Foo")]
    [PrimaryKey("ID", AutoIncrement = true)]
    [ExplicitColumns]
    public class Foo
    {
          [Column] public int ID { get; set; }
    }

   public Task<Foo> SingleOrDefault(int id)
    {
          return _db.SingleOrDefaultAsync<Foo>(id);
    } 
```

`_db.lastCommand` is `Select "Foo"."ID" from "Foo" where "ID" is "1"` . 
Edit: The "1" is erroring with "42883: operator does not exist: text = integer".
_db is IDatabase.

Using (string, args) version for now. e.i. ("WHERE \"ID\" = @0", id)

**Comment by asherber** [comment]
This code works fine for me.

What is the exact output of `_db.LastCommand`? Mine looks like this:

```
SELECT "foo"."id" FROM "foo" WHERE "id" = @0
   -> @0 [Int32] = "1"
```

(My table has lowercase names.)

You can see that the query is correctly parameterized, and that the type of the parameter passed in is, correctly, `Int32`.

**Comment by bnowlin** [comment]
... Thanks. Found issue in ` [PrimaryKey("ID", AutoIncrement = true)]` in codebase. I had changed the PK after creating the attributes and forgot to update the attribute.
