### ISSUE TITLE
Partial update methods seem missing

### ISSUE THREAD

**Issue by dotnetchris** [CollaboratingPlatypus/PetaPoco#63]
I'm using PetaPoco Core 4.0.3

The Update method seems to only have the overloads of 

```C#
public int Update<T>(string sql, params object[] args)
public int Update<T>(Sql sql)
```
This doesn't seem to match your blog post http://www.toptensoftware.com/Articles/116/PetaPoco-Partial-Record-Updates

that shows `db.Update<user>(u, new string[] { "last_login" });` should be a valid method.

**Comment by pleb** [comment]
I know this was from some time ago, but I'm closing as V5 is the version which is being maintained.
