### ISSUE TITLE
InsertAsync exception when using derived DatabaseProvider

### ISSUE THREAD

**Issue by Ed156** [CollaboratingPlatypus/PetaPoco#631]
Hello. I always use the following provider below with the latest stable precompiled PP. 
It is needed (AFAIK) because when a table has triggers, the return value of an insert is not being returned. This solves this:

    public class OurSqlServerDatabaseProvider : SqlServerDatabaseProvider
    {
	    public override object ExecuteInsert(Database db, System.Data.IDbCommand cmd, string primaryKeyName)
	    {
		    cmd.CommandText += ";\nSELECT CAST(isnull(scope_identity(), -1) AS INT) AS NewID";
		    return ExecuteScalarHelper(db, cmd);
	    }
    
	    public override string GetInsertOutputClause(string primaryKeyName) => string.Empty;
    }

Recently I am starting to use async methods of PetaPoco and noticed an exception when doing InsertAsync:

    Database db = new Database(connectionString, new SqlServerDatabaseProvider(), null);
    LicLog poco = new LicLog { ll_fieldname = "Test"};

     int newId = (int)await db.InsertAsync("LicLog", "ll_id", true, poco);

while the normal Insert method works fine.
In this example it is a very simple table, without triggers.

    [TableName("[dbo].[LicLog]")]
    [PrimaryKey("ll_id")]
    [ExplicitColumns]
    public partial class LicLog
    {
	    [Column]
	    public string ll_fieldname { get; set; }
    
	    [Column]
	    public int ll_id { get; set; }
    }

This is some exception info:

    Object reference not set to an instance of an object.     
    at PetaPoco.Core.PocoColumn.ChangeType(Object val)
       at PetaPoco.Database.ExecuteInsertAsync(CancellationToken cancellationToken, String tableName, String primaryKeyName, Boolean autoIncrement, Object poco)
    
       at PetaPoco.Core.PocoColumn.ChangeType(Object val)
       at PetaPoco.Database.<ExecuteInsertAsync>d__198.MoveNext()
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at SBServicesData.MasterUserRepo.<Insert>d__9.MoveNext() in ...

If I use the standard SqlServerDatabaseProvider insteady of OurSqlServerDatabaseProvider then all is fine when doing InsertAsync, but then my tables with triggers will give problems.

Is a derived Provider currently still the best way to deal with inserting into tables with triggers?

if so, would I need a change or addition in OurSqlServerDatabaseProvider  to handle InsertAsync?

**Comment by pleb** [comment]
@Ed156 are you forgetting to override `ExecuteInsertAsync` too?

**Comment by Ed156** [comment]
Ah so simple. I added that and it is working fine again.

    public class OurSqlServerDatabaseProvider : SqlServerDatabaseProvider
    {
        public override object ExecuteInsert(Database db, IDbCommand cmd, string primaryKeyName)
        {
            AddIdentitySelect(cmd);
            return ExecuteScalarHelper(db, cmd);
        }

        public override Task<object> ExecuteInsertAsync(CancellationToken cancellationToken, Database db, IDbCommand cmd, string primaryKeyName)
        {
            AddIdentitySelect(cmd);
            return ExecuteScalarHelperAsync(cancellationToken, db, cmd);
        }

        private static void AddIdentitySelect(IDbCommand cmd)
        {
            cmd.CommandText += ";\nSELECT CAST(isnull(scope_identity(), -1) AS INT) AS NewID";
        }

        public override string GetInsertOutputClause(string primaryKeyName) => string.Empty;
    }

**Comment by Ed156** [comment]
Thank you @pleb !
