### ISSUE TITLE
How to use injection in. Net 6?？

### ISSUE THREAD

**Issue by hdwubinw** [CollaboratingPlatypus/PetaPoco#634]

**Comment by hdwubinw** [comment]
123

**Comment by asherber** [comment]
@hdwubinw Can you please provide more information about what you're looking for?

**Comment by hdwubinw** [comment]
> @hdwubinw Can you please provide more information about what you're looking for?

I am currently using ASP Net core webapi, want to know how to use petapoco?

**Comment by asherber** [comment]
There are lots of ways to use PetaPoco. The docs are [here](https://github.com/CollaboratingPlatypus/PetaPoco/wiki). If you're trying to do something that isn't working, please post an example of your code.

**Comment by hdwubinw** [comment]
> There are lots of ways to use PetaPoco. The docs are [here](https://github.com/CollaboratingPlatypus/PetaPoco/wiki). If you're trying to do something that isn't working, please post an example of your code.

First of all, thank you very much for your help. I have read the document, but I want to see if there are any injection examples. The examples in the document do not indicate how to inject again Net core API.

**Comment by asherber** [comment]
What are you trying to inject, and what injection mechanism are you using? What have you tried?

**Comment by hdwubinw** [comment]
> What are you trying to inject, and what injection mechanism are you using? What have you tried?

Injection petapoco

**Comment by pleb** [comment]
For dotnet core, I'd assume something like

```c#
services.AddSingleton<IDatabaseBuildConfiguration>(DatabaseConfiguration.Build()
    .UsingCommandTimeout(180)
    .WithAutoSelect()
    .WithNamedParams()
    .UsingConnectionString("some connection string")
    .UsingDefaultMapper<ConventionMapper>());
			
services.AddScoped<IDatabase>((s) => s.GetService<IDatabaseBuildConfiguration>().Create());
```

**Comment by hdwubinw** [comment]
> For dotnet core, I'd assume something like
> 
> ```cs
> services.AddSingleton<IDatabaseBuildConfiguration>(DatabaseConfiguration.Build()
>     .UsingCommandTimeout(180)
>     .WithAutoSelect()
>     .WithNamedParams()
>     .UsingConnectionString("some connection string")
>     .UsingDefaultMapper<ConventionMapper>());
> 			
> services.AddScoped<IDatabase>((s) => s.GetService<IDatabaseBuildConfiguration>().Create());
> ```

thank you!
