### ISSUE TITLE
Insert ou update japanese and chinese characters

### ISSUE THREAD

**Issue by nicoacb** [CollaboratingPlatypus/PetaPoco#636]
I Team,

I'am trying to insert japanese and chinese characters using binding method into SQL Server NVARCHAR(MAX) fields and into Oracle NCLOB fields.
Using SQL request into SQL Server Management Studio "insert into TABLE values N'ぁ'" works.
How to achieve this with PetaPoco ?

Thanks, and great job everyone!

**Comment by asherber** [comment]
PetaPoco uses unicode strings by default, so the usual methods for [inserting ](https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Inserting )should work out of the box.

**Comment by nicoacb** [comment]
It's right. Sorry misreplacement...
There is no error and no exception.
`_db.Insert(toinsert)` return `null`
Data is inserted but not correctly, it gave me the same result as `INSERT INTO [MyTable] ([MyText]) VALUES ('むかし')` : a question mark in database.
My manual insert in SQL Management studio with a N before work : `INSERT INTO [MyTable] ([MyText]) VALUES (N'むかし')`

**Comment by asherber** [comment]
@Curlack I'm not sure that's relevant. That passage is about a new feature in Sql Server 2019 which provides Unicode support to the `char` and `varchar` data types. Older versions certainly support Unicode characters, using the `nchar` and `nvarchar` data types, as in our samples above. As it happens, I'm using Sql Server 2012 in 2008 compatibility mode with SQL\_Latin1\_General\_CP1\_CI\_AS collation. @nicoacb may be using something different, but if he were using some collation that somehow didn't allow Unicode in `nvarchar` (not sure if that's possible), then his raw SQL inserts wouldn't work either.

**Comment by Curlack** [comment]
Yes. I meant that the database collation might be the reason you both
getting different results. Sorry for the confusion.

**Comment by asherber** [comment]
I'm pretty sure that all collations support Unicode in `nchar` and `nvarchar` columns. And since @nicoacb gets the expected results with raw SQL, it's clear that there's no issue storing Unicode in his table.

@nicoacb What happens if you take PP out of the equation and use straight C#:

```c#
var cmd = Connection.CreateCommand();
cmd.CommandType = CommandType.Text;
cmd.CommandText = "insert into [MyTable] values (@0)";

var parm = cmd.CreateParameter();
parm.DbType = DbType.String;
parm.Value = "むかし";
parm.ParameterName = "@0";

cmd.Parameters.Add(parm);
cmd.ExecuteNonQuery();
```

**Comment by Curlack** [comment]
I just found [this on StackOverflow](https://stackoverflow.com/questions/10025032/what-is-the-meaning-of-the-prefix-n-in-t-sql-statements-and-when-should-i-use-it#:~:text=You%20may%20have%20seen%20Transact,to%20CHAR%2C%20VARCHAR%20or%20TEXT.)
Quote from Microsoft: 

> Prefix Unicode character string constants with the letter N. Without the N prefix, the string is converted to the default code page of the database. This default code page may not recognize certain characters.

@nicoacb can use the following statement to check Collation and Code Page:
```sql
SELECT * FROM sys.fn_helpcollations()
WHERE name = SERVERPROPERTY('Collation')
```
Assuming same column datatypes and collation, the only explanation I can come up with, to explain the different results, is the characters in @nicoacb's test is not recognized by the default code page, but the characters in @asherber's test is.

@asherber, would you mind testing with the same characters as @nicoacb ?

If that's not the case, then I'm raising the white flag. I'm intrigued...

**Comment by asherber** [comment]
@Curlack I have tested with the same characters as @nicoacb, no change.

Regarding your post about Unicode character strings and the `N` prefix, yes, that's all true. He's able to use that in raw SQL to insert Unicode characters, which is why I said that there doesn't appear to be an issue with the table or collation.

Regarding parameter types, your line of code is explicitly creating a `SqlParameter` and therefore needs to use `SqlDbType.NVarChar`. The code I posted above is more connection-agnostic; the command is a `DbCommand` and the parameter is a `DbParameter`, which is why I'm using `DbType.String`. The ADO.NET provider will translate all of these as needed.

**Comment by Curlack** [comment]
I've adapted my code accordingly and I can confirm that it saves correctly, thanks.

**Comment by nicoacb** [comment]
Thanks a lot for lot for your help ! You gave me some ideas and i finally found.
I use dotConnect Universal from Devart as driver. It return by default AnsiString as DbType (`var p = cmd.CreateParameter();` line 617 in Database.cs) and DbType is not override in `SetParameterProperties` function for `string` type (line 663 in Database.cs).

I use this workaround in my provider :
```
public override void PreExecute(IDbCommand cmd)
{
    foreach (IDbDataParameter param in cmd.Parameters)
    {
        var t = param.Value.GetType();
        if (param.DbType == DbType.AnsiString && t == typeof(string))
        {
            param.DbType = DbType.String;
        }                
    }
    base.PreExecute(cmd);
}
```

**Comment by asherber** [comment]
Aha! The fact that you're using a different driver and a custom provider is important information.

Yes, that seems like the right solution for your case.
