### ISSUE TITLE
Enhance Insert(object poco)

### ISSUE THREAD

**Issue by dotnetchris** [CollaboratingPlatypus/PetaPoco#64]
I recommend enhancing this method 

    public object Insert(object poco)
    {
	    var pd = PocoData.ForType(poco.GetType());
	    return Insert(pd.TableInfo.TableName, pd.TableInfo.PrimaryKey, pd.TableInfo.AutoIncrement, poco);
    }

to 

    public object Insert(object poco, string tableName = null, string primaryKeyName = null, bool? autoIncrement = null)
    {
	    var pd = PocoData.ForType(poco.GetType());
	    return Insert(tableName  ?? pd.TableInfo.TableName,primaryKeyName  ?? pd.TableInfo.PrimaryKey, (autoIncrement ?? (bool?)pd.TableInfo.AutoIncrement).Value, poco);
    }

This would also potentially make the other methods redundant, other than potentially the full expanded method to skip the cost of calling PocoData.ForType

**Comment by pleb** [comment]
I'm sorry that your issue has been left for so long. In an effort to reboot PetaPoco your issue has been closed. If you think this is still a problem. Please feel free to open and another issue. Please pass the word on that PetaPoco is back. We're looking for people #204.
