### ISSUE TITLE
Inherited attributes on properties are skipped

### ISSUE THREAD

**Issue by asherber** [CollaboratingPlatypus/PetaPoco#640]
I discovered this today when looking into d-p-y/statically-typed-poco-queries#10

```c#
public class Parent
{
	[Column("Foo")]
	public virtual int ID { get; set; }
}

public class Child : Parent
{
	public override int ID { get; set; }
}

db.Query<Child>();
// EXPECTED: SELECT [Foo] FROM [Child]
// ACTUAL: SELECT [ID] FROM [Child]
```

The reason for this is that in `ColumnInfo`, when PP looks for attributes on a property, it does  `pi.GetCustomAttributes(typeof(xxxAttribute), true)`. As the Microsoft docs [indicate](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.getcustomattributes?view=net-6.0). the second parameter to `GetCustomAttributes()`, which indicates whether to look for inherited attributes, is ignored when you're looking at properties. What this really means is that it behaves as though the value were `false` and ignores inherited attributes. Oddly, if you omit the second parameter completely, the code follows a different path and _does_ return inherited attributes (which is the behavior we would prefer here).

This affects `ColumnAttribute`, `IgnoreAttribute`, and `ResultColumnAttribute`. I think it would also affect a `ValueConverterAttribute` in the parent class.

Note that in the (probably) more usual case of an inherited but not overridden property, everything is fine.

```c#
public class Parent
{
	[Column("Foo")]
	public virtual int ID { get; set; }
}

public class Child : Parent
{
}

db.Query<Child>();
// EXPECTED: SELECT [Foo] FROM [Child]
// ACTUAL: SELECT [Foo] FROM [Child]
```

I understand that this is an edge case -- an overridden property in a child class that doesn't also override the attribute. I've never come across it in real life. And fixing it would be a breaking change, since it would change the established public behavior. So if you decide you don't want to address it, that's fine -- I just wanted to bring it up for awareness.

**Comment by Curlack** [comment]
If we check both (first non inherited, if not found, then inherited),
wouldn't that cover the edge case and avoid a breaking change?

**Comment by Curlack** [comment]
I found it here if you want to take a look [https://blog.seancarpenter.net/2012/12/15/getcustomattributes-and-overridden-properties/](url)

**Comment by Curlack** [comment]
This is the code I tested with:
```c#
var a = typeof(Child).GetProperty(nameof(Child.Id));
var b = a.GetCustomAttributes(typeof(ColumnAttribute), true); //<--No attribute
var c = Attribute.GetCustomAttributes(a, typeof(ColumnAttribute), true); //<--1 attribute
```

**Comment by pleb** [comment]
In my opinion, it's a bug. Yes, fixing it might cause some breaking changes, but I guess that's potentially true for any bug fix.

So long as it's a quick change to revert to pre-fix behaviour, I don't see a big issue with it.

```c#

public class Parent
{
	[Column("Foo")]
	public virtual int ID { get; set; }
}

public class Child : Parent1
{
        [Column("ID")] // 👈Revert by adding attribute
	public override int ID { get; set; }
}

db.Query<Child>();
// EXPECTED: SELECT [ID] FROM [Child]
// ACTUAL: SELECT [ID] FROM [Child]
``

**Comment by asherber** [comment]
Okay, I can put together a PR tomorrow with some new tests.
