### ISSUE TITLE
Azure.Identity - Support

### ISSUE THREAD

**Issue by chiragconsultant** [CollaboratingPlatypus/PetaPoco#643]
We are using PetaPoco and wanted to see if we can connect to the database using AccessToken taking leverage of Azure.Identity as the database is SQL Database on Azure.  I know its possible on Entity Famework but not sure if its possible using PetaPoco?

**Comment by pleb** [comment]
@chiragconsultant PetaPoco can be thought of as a wrapper. So long as the database connection providers does {x-feature} it should be possible with PetaPoco.

**Comment by chiragconsultant** [comment]
Thank you for getting back @pleb  - the connection works on the basis of AccessToken and I don't think PetaPoco has that property?  Entity Framework has DbContext class which will allow you to make database connection using AccessToken.

**Comment by asherber** [comment]
It's true that PetaPoco doesn't have this property, but what you can do is establish your `SqlConnection` using an access token and then do `var db = new Database(myConnection)`.

**Comment by chiragconsultant** [comment]
Thank you @asherber  - We got it to work!  Thanks a lot 👍
