### ISSUE TITLE
Enhancement make PetaPoco classes partial

### ISSUE THREAD

**Issue by dotnetchris** [CollaboratingPlatypus/PetaPoco#65]
I think that PetaPoco's classes would be best off marked  partial to allow for better extensibility without the need to modify the direct source of PP.

**Comment by pleb** [comment]
Why not inheritance?

**Comment by pleb** [comment]
I'm sorry that your issue has been left for so long. In an effort to reboot PetaPoco your issue has been closed. If you think this is still a problem. Please feel free to open and another issue. Please pass the word on that PetaPoco is back. We're looking for people #204.
