### ISSUE TITLE
New Release Request

### ISSUE THREAD

**Issue by EricRohlfs** [CollaboratingPlatypus/PetaPoco#654]
Our certification authority is giving us a hard time about using PetaPoco only because there hasn't been a new release since 2018. Requesting that you update the license copywrite or something trivial and push out a new release?  I know this sounds like a silly request, but it is the unfortunate world I live in.

We enjoy PetaPoco, and especially how we don't have to re-write our code every 18 months as with some other libraries out there.

**Comment by asherber** [comment]
Are you able to upgrade to v6 of [PetaPoco](https://www.nuget.org/packages/PetaPoco.Compiled)? The only significant thing removed was support for T4 files.

**Comment by EricRohlfs** [comment]
Yes we are using that.  When they look at the GitHub site and it shows the last release was 2018, they are going off that date and getting nervous.

**Comment by asherber** [comment]
The latest release of v6 was a month ago.

![](https://user-images.githubusercontent.com/5248041/186685111-b06e56cf-395f-44eb-8625-30884a420b47.png)

**Comment by pleb** [comment]
I deleted the releases and switched off showing them on the Github repo. Nuget it where people should be pulling PetaPoco from. 

@asherber is correct. Maybe you can link them to the Nuget page?

**Comment by EricRohlfs** [comment]
That works. I will have them look at nuget for release info.  Thank you very much
