### ISSUE TITLE
Chinese string query may return null，in Mysql,  Character set convert problem

### ISSUE THREAD

**Issue by winxp2002** [CollaboratingPlatypus/PetaPoco#658]
like  Query<T>("where address=@0", "中国")

Mysql database Character set is latin1 ，And column type is varbinary(200)，Normally, this can be cross Character set  store

I want to provide a default parameter type converter, provide a configurable database string encoding conversion, and automatically convert the string to Binary in mysql

My current temporary modifiy， is work well
at ：
private void AddParam(IDbCommand cmd, object value, PocoColumn pc)

var t = value.GetType();
if (t == typeof(string))
{
    //mysql chinese is miss
   p.DbType = DbType.Binary;
   p.Value = Encoding.GetEncoding("gb2312").GetBytes(value as string);
}

**Comment by asherber** [comment]
You can intercept parameters in `Database.CommandExecuting`.

```c#
using (var db = new Database(...))
{
  db.CommandExecuting += FixChineseStrings;
  ...
}

public static void FixChineseStrings(object sender, DbCommandEventArgs args)
{
  bool IsStringParam(IDataParameter p) => p.DbType == DbType.String;
  foreach (var parm in args.Command.Parameters.Cast<IDataParameter>().Where(IsStringParam))
  {
    parm.DbType = DbType.Binary;
    parm.Value = Encoding.GetEncoding("gb2312").GetBytes(parm.Value as string);
  }
}
```

There are several ways that you could make this part of your database construction. For example:

```c#
public Database GetMyDatabase()
{
  var config = DatabaseConfiguration.Build()
  	.UsingCommandExecuting(FixChineseStrings)
  	.UsingConnectionString(...);
  return new Database(config);
}

using (var db = GetMyDatabase())
{
  ...
}  
  	
```

**Comment by winxp2002** [comment]
Thanks for solving my problem

**Comment by winxp2002** [comment]
This can solve the problem, but there is no default solution later. I think it is a kind of problem in MySQL. There is no such problem in other databases. Is it possible for us to provide a default conversion method later?

**Comment by asherber** [comment]
Sorry, I didn't fully understand what the issue is. Can you provide some regular ADO.NET code that works the way you want it to?

**Comment by winxp2002** [comment]
The problem is that the transfer character encoding can’t convert db encidng
I change it  in mysql  connectstring  ，but  nothing change 
how to set default  string parameter transfer encoding

**Comment by winxp2002** [comment]
Yes ,it'not PetaPoco problem ,I try it in MySqlConnector , The problem still exists ，I'm sorry to disturb you

**Comment by asherber** [comment]
So it sounds like this is not a PetaPoco issue. If you want to work around the issue, my suggestion above should work. Otherwise, I don't think we want to add code to the library that makes it behave differently from the underlying ADO.NET provider.

**Comment by pleb** [comment]
Maybe try the other connector https://www.nuget.org/packages/MySql.Data

**Comment by winxp2002** [comment]
MySqlConnector only supports UTF-8 (utf8mb3 or utf8mb4) as the client character set.  
I changed mysql.data provider ，It's working well
