### ISSUE TITLE
Sql.Append bug? 

### ISSUE THREAD

**Issue by peterfelice** [CollaboratingPlatypus/PetaPoco#67]
First off, thanks so much for the platform. It is such a great platform and have saved me so much time. I found a small issue with Sql.Append (or anything that calls it) with certain ordering of multiple WHERE clauses (or multiple ORDER BY clauses) where PetaPoco will try and convert multiple WHERE to WHERE/AND statements.

Basically for the following scenario:

        Sql sql1 = Sql.Builder
                .Where("Column1 = @0", column1)
                .Where("Column2 = @0", column2);

        Sql sql2 = Sql.Builder
                .Where("Column3 = @0", column3)
                .Where("Column4 = @0", column4);

        Sql finalSql = Sql1.Append(sql2);

Will end up generating the following sql: "WHERE Column1 = @0 AND Column2 = @1 WHERE Column3 = @2  AND Column4 = @3". I know this is a trivial example, but I was generating parts of my sql statement in different methods so I had this happen all over the place. 

Making a small change to the Sql.Append method seems to fix it right up.

        public Sql Append(Sql sql)
        {
            if (_rhs != null)
                _rhs.Append(sql);
            else if (_sql != null)
                _rhs = sql;
            else
            {
                _sql = sql._sql;
                _args = sql._args;
                _rhs = sql._rhs;
            }

            return this;
        }

Anyways, there might be a cleaner way to fix this up or a better way to structure/chain your Sql but this small change has helped me out so I thought i would share.

Cheers

**Comment by pleb** [comment]
The bug is `sql2.SQL` is not called in `Sql finalSql = Sql1.Append(sql2);`. I've added a ToString() overload to resolve this in the future
