### ISSUE TITLE
Contributing to documentation & wiki

### ISSUE THREAD

**Issue by Ste1io** [CollaboratingPlatypus/PetaPoco#677]
I would like to help update and improve the documentation/wiki; are you accepting contributions for that currently? Is so, what is the preferred method of submitting updates? I can provide patch files if that is easiest for you.

**Comment by pleb** [comment]
@Ste1io I've invited you to the team. Welcome aboard

**Comment by Ste1io** [comment]
Cheers, @pleb, I appreciate the opportunity. Already made significant headway on my local wiki clone, and I expect to have a first run of updates ready for review and posting sometime next week.
