### ISSUE TITLE
Feature suggestion: Intellisense code XML documentation

### ISSUE THREAD

**Issue by litera** [CollaboratingPlatypus/PetaPoco#68]
Code is basically just documented via code comments and that's arguably not documentation and can't be considered as such. Some parts don't have any comments whatsoever (ie. `AutoJoinAttribute` - to me as a SQL Server developer this attribute doesn't mean anything per se so it definitely needs documentation).

I'm not sure why is that code isn't properly documented since it will require much more work to document all public stuff in it now as if it was properly done from the very beginning.

### Feature request
**Please provide proper XML documentation** to aid faster development due to intellisense (which is built into dev env for a reason and a damn good one).

To a developer proper XML documentation is arguably more useful than anything else and makes coding much faster.

### Example

```
///<summary>Represents a result from a paged database request.</summary>
public class Page<T>
{
    ...
}
```

**Comment by pleb** [comment]
Agree. Bump!

**Comment by pleb** [comment]
I'm going to ensure better xml docs are added
