### ISSUE TITLE
Moq alternative

### ISSUE THREAD

**Issue by Ste1io** [CollaboratingPlatypus/PetaPoco#688]
[As of v4.20](https://www.reddit.com/r/dotnet/comments/15ljdcc/does_moq_in_its_latest_version_extract_and_send/), Moq is now apparently scanning the local git config for the configured email address using an obfuscated closed-source .NET analyzer by SponsorLink, and uploading it to an Azure-hosted service for cross referencing against a list of sponsors. 😠 

This poses a couple of potential issues, aside from the obvious lack of transparency behind the decision:

- Potential GDPR violation, which I would assume (inject "I'm not a lawyer" notice here) would probably bubble up from them, through us, and to our dependents (which, PetaPoco being a library, is rather unsettling).
- Interference with CI/CD pipelines for projects that treat warnings as errors (something I do with nearly all of my projects), as this change now generates an [insuppressible warning MOQ101](https://github.com/moq/moq/issues/1370).
- Privacy these days is paramount, and *even if* Moq deserves to be trusted with my email address after this, there's no guarantees or statements (to my knowledge) from the developers providing an assurance as to the the transmission and storage protocols of these emails in the event of a security breach.

A possible alternative to Moq that I've seen suggested would be NSubstitute; I haven't used it before, but I'll be happy to help with the switchover if need be.

**Comment by asherber** [comment]
SponsorLink has been removed from Moq in 4.20.2. The official reason given in the commit is that it breaks something on MacOS, but given the [considerable traffic](https://github.com/moq/moq/issues?q=is%3Aissue+is%3Aopen+sponsorlink) about this issue, it wouldn't surprise me if it didn't come back anyway. (I haven't read through all the threads, so I haven't seen an author response.) And even if it came back, users of Moq always have the option of just not upgrading to a version that includes it. Looks like PetaPoco is way back on 4.8.2, so not an issue.

Also, from the perspective of PetaPoco, something like this would only be an issue for people who are developing against the repo (i.e., running PP tests), not end users. I'm not saying this makes the issue moot, just that it wouldn't be that widespread.

Someone who has [looked into it](https://github.com/moq/moq/issues/1372#issuecomment-1670344399) has determined that what's sent to SponsorLink is a hash of your email, not your actual email.

So I think it's a poor decision by the authors of Moq, but not something that affects us right now.

**Comment by pleb** [comment]
Oh wow. [Crazy](https://github.com/moq/moq/issues/1372). 

Yep, Moq can't be trusted anymore! 

PetaPoco mainly relies on integration-level tests, so I assume replacing Moq won't be all that painful.

As @asherber pointed out, there's no risk to PetaPoco users.

**Comment by asherber** [comment]
Or just don't update Moq. The version PP uses is perfectly fine and always will be.
