### ISSUE TITLE
System.InvalidCastException in Pagination Petapoco error With Query return null result

### ISSUE THREAD

**Issue by kauaquino** [CollaboratingPlatypus/PetaPoco#689]
System.InvalidCastException in Pagination Petapoco error With Query return null result

![image](https://github.com/CollaboratingPlatypus/PetaPoco/assets/54816886/c89881df-753d-4862-af65-16cce0a6b2bd)

![image](https://github.com/CollaboratingPlatypus/PetaPoco/assets/54816886/4619c4dc-5af6-45b0-b00d-62e6991ee3c8)

If I try to fetch a query from Petapoco page that doesn't return anything, it gives an error. If there's something, it works. What should I do??

**Comment by asherber** [comment]
What's the contents of the line where you call `Db.Page()`, and what's the definition of the object you're trying to return?

**Comment by kauaquino** [comment]
Model:
![image](https://github.com/CollaboratingPlatypus/PetaPoco/assets/54816886/d6325748-0201-451d-8110-73381d7d0424)
 
 
 In this case, it's empty because there was no return, but when it comes, it works correctly.

**Comment by asherber** [comment]
And what's the rest of the line that says `return Db.Fetch<Re`? It's hidden by the exception dialog.

**Comment by Ste1io** [comment]
Also a screenshot of the callstack would be helpful.

**Comment by Ste1io** [comment]
<details><summary>Tradução Portuguesa 👈🏻 </summary>
<p>

@kauaquino Dei outra olhada nas suas capturas de tela e notei que existem alguns tipos de valor anuláveis na geração do seu SQL (`inicio` e `fim`, também um `DateTime?`), mas nenhum no tipo de modelo `RegistroPontoDTO`. Não tenho certeza se algum deles está referenciando propriedades no tipo de modelo, porém. Algumas considerações...

A mensagem de exceção na sua captura de tela, "O objeto nulo não pode ser convertido em um tipo de valor.", parece indicar uma tentativa de usar uma referência nula onde um tipo de valor não anulável é esperado. A definição do seu modelo não tem tipos de valor anuláveis (como `DateTime? Data`), mas há tipos de valor anuláveis sendo referenciados na geração do seu SQL (parcialmente visíveis atrás da mensagem de exceção), então eu sugeriria verificar todos eles e certificar-se de que o mapeamento de tipos está correto.

O português não é minha língua nativa, então *espero* que essa versão traduzida faça algum sentido. Se isso não resolver o seu problema, por favor responda com as informações que @asherber solicitou e uma captura de tela da sua pilha de chamadas.

</p>
</details>

---

@kauaquino I took another look at your screenshots, and noticed there are some nullable value types in your sql generation (the start and end variables `inicio` and `fin`, also a `DateTime?`), but none in your model type `RegistroPontoDTO`. I'm not sure if any of them are referencing properties in the model type, though. A couple thoughts...

The exception message in your screenshot, "The null object cannot be converted to a value type." seems to indicate an attempt to use a null reference where a non-nullable value type is expected. Your model definition has no nullable value types (such as `DateTime? Data`), but there are nullable value types being referenced in your sql generation (partly visible behind the exception message), so I would suggest checking all of them and making sure your type mapping is correct.

Portugese is not my native language, so *hopefully* this translated version makes some sense. If this doesn't solve your issue, please respond with the info @asherber requested, and a screenshot of your call stack.

**Comment by asherber** [comment]
@Ste1io That's fine -- a null column value mapping to a non-nullable value type should result in the default for that type (e.g., a null value mapping to an `int` property yields 0).

The OP says his query "doesn't return anything". I took that to mean that there were no records returned. @kauaquino Is that true? Or are you getting records in which some values are null?

**Comment by Ste1io** [comment]
> That's fine -- a null column value mapping to a non-nullable value type should result in the default for that type (e.g., a null value mapping to an int property yields 0).

@asherber you are correct, in the context of PetaPoco. What I was referring to was the possibility that in the OP's DTO implementation, or in a ConvertFromDB func, unboxing a `null` value into a non-nullable value type could throw; eg:

```cs
public override object ConvertFromDb(object value) => value; // assume value is null, no error handling
//...
registroPontoDto.TipoRegime = (TipoRegime)value; // unboxing null object cast to enum, for example
```

I could still be wrong, but it's the closest possible reason I can think of based on code fragments we have to work with (especially the code in the faulting method, `RodizioColaborador.Data.Dapper.PontoRepository.GetPointsByCompanyId` (rough english translation).

For what it's worth, I took "In this case, it's empty because there was no return" as a reply to your question with "of the line" overlooked or miss-translated... the contents of the list in `Db.Page<T>` would being empty because there was no return value.

> What's the contents ~~of the line~~ where you call Db.Page(),
