### ISSUE TITLE
Problem with switching database connection strings in. Net 7

### ISSUE THREAD

**Issue by hdwubinw** [CollaboratingPlatypus/PetaPoco#692]
Petapoc has a default database connection string configured in. Net 7. For example, if I want to use another database connection string in a certain method, how should I set it?

**Comment by iadaz** [comment]
See these pages in the Wiki:
https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Ways-to-instantiate-PetaPoco
https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Fluent-Configuration

The fluent configuration has a `UsingConnectionString()` method where you can pass the connection string.

**Comment by Ste1io** [comment]
Did that solve your question, @hdwubinw?
