### ISSUE TITLE
dynamic type resolution failure on net4.X targets

### ISSUE THREAD

**Issue by Ste1io** [CollaboratingPlatypus/PetaPoco#697]
While fixing the tests in PR #696, a previously unnoticed bug has surfaced thanks to the tests included in offending PR #687. Using `ExpandoObject`/`dynamic` types in Update operations with the older .NET Framework targets (net40, net45, net472) fails gloriously throwing a `RuntimeBinderException`.

As it turns out, the older runtimes are unable to resolve the `IAlterPoco.Update` method when called with a `dynamic` object, though some gentle coaxing with a cast at the call site fixes the problem. The .NET Standard 2.1 target builds are unaffected, and pass all current tests.

Adding (yet another) overload(sssss) for the `Update` method that accepts a `dynamic` type in place of the `object poco` parameter, and delegating to the appropriate existing `Update` method with an explicit cast as `object` would fix this.

```cs
#if !NETSTANDARD
public int Update(string tableName, string primaryKeyName, dynamic poco)
    => Update(tableName, primaryKeyName, (object)poco);

// TODO: lots more cool overloads here
#endif
```

I'll open a PR shortly, just felt this should be fixed outside of the tests resurrection PR for cataloguing reasons.

**Comment by Ste1io** [comment]
Scratch that, overload resolution is clueless about the two, even with a dummy overload. Even using a unique signature that has zero ambiguity, and resolves correctly by intellisense in the IDE, runtime is clueless as to what it's working with, and continues to throw if not explicitly cast as `object` at the callsite.

I'm thinking it may just be best to document this caveat for users who do happen to be using an older .NET Framework, and call it a day, especially since support for the problematic targets isn't planned for v7 and onward.

**Comment by camielverdult** [comment]
Disappointing to hear that you won't fix this for older versions of .NET since it directly contradicts the goal of an ORM...

**Comment by pleb** [comment]
> Disappointing to hear that you won't fix this for older versions of .NET since it directly contradicts the goal of an ORM...

Feel free to raise a PR with a fix.

**Comment by camielverdult** [comment]
You are right to not support the older versions, I was able to achieve my goal differently. Thank you for the work on this libray
