### ISSUE TITLE
Single<T>(object primaryKey) Single<T>(string sql, params object[] args) clash

### ISSUE THREAD

**Issue by mstijak** [CollaboratingPlatypus/PetaPoco#71]
For string primary keys, if cast to object is not explicitly made, wrong method is called.
Maybe method should be renamed to SingleById<T>(object primaryKey) or something similar.

**Comment by pleb** [comment]
This is where a quick extension method could be utilised. Changing the API because to fit a use case where a string ID is used probably isn't a great reason.
