### ISSUE TITLE
How to integrate MiniProfiler ?

### ISSUE THREAD

**Issue by nhaberl** [CollaboratingPlatypus/PetaPoco#723]
Hello,

When using the fluent builder of PetaPoco, how can I add MiniProfiler by wrapping the connection to ProfiledDbConnection.
If I set within fluentBuilder on UseConnection() I have to manage all connections by mayself which is not what the behaviour should be like. (like stated in the docs)

Any help appreciated
Norbert

**Comment by asherber** [comment]
The `OnConnectionOpening` event fires after PetaPoco assigns a connection string to its internal connection and before the connection is actually opened. You can use this event to wrap the connection.

```csharp
var config = DatabaseConfiguration.Build()
    .UsingConnectionString(myConnString)
    .UsingProvider<SqlServerDatabaseProvider>()
    .UsingConnectionOpening((sender, args) => 
        args.Connection = new ProfiledDbConnection((DbConnection)args.Connection, MiniProfiler.Current)
    );
```

**Comment by nhaberl** [comment]
Thanks, worked perfectly!
