### ISSUE TITLE
Question: Best practices for resource disposal

### ISSUE THREAD

**Issue by Jeremy-Code-F** [CollaboratingPlatypus/PetaPoco#728]
Hi,

I had a question regarding the best practices around resource disposal for database objects, this mainly comes from the context of an ASPNET Core project.

The common pattern I see is initializing the database in the constructor of a repository, for example: 

```
private Database db;

// Registered as 'Scoped' in the DI container
public DbRepo(string conString)
{
    db = new Database(conString, "System.Data.SqlClient");
}
```

db holds the reference and then is used later

```
internal List<SomeModel> SearchDb(string searchWord)
        {
            List<SomeModel> myList = new List<SomeModel>();

            myList = db.Fetch<SomeModel>("QueryHere");
            return myList .OrderBy(e => e.SomeField).ThenBy(e => e.SomeOtherField).ToList();
        }
```

It seems like there should be a using statement here since `Database` implements `IDisposable` like...

```
internal List<SomeModel> SearchDb(string searchWord)
        {
        using(var db = new Database(connStr, ""){
        List<SomeModel> myList = new List<SomeModel>();

            myList = db.Fetch<SomeModel>("QueryHere");
            return myList .OrderBy(e => e.SomeField).ThenBy(e => e.SomeOtherField).ToList();
        }
            
            }
```

Is there any benefit to wrapping it in a using statement here/is that the expected way it would be used? 

Thanks!

**Comment by asherber** [comment]
If `DbRepo` is registered as scoped, then the DI container will take care of instantiating one when needed -- and disposing it when done. The `DbRepo` class, in turn, is responsible for disposing any disposable objects it owns. So `DbRepo` should implement `IDisposable`, and its `Dispose` method should dispose the `Database`.

Your third example (creating a `Database` on demand in a `using` block) also works fine, but the big advantage of a DI container is centralizing creation of these objects for you.

**Comment by Jeremy-Code-F** [comment]
Ah interesting I hadn't thought about that so something like 

```
public class DbRepo: IDbRepo, IDisposable
    {
        private Database _database;
        public DbRepo()
        {
            _database = new Database("connStr", "");
        }
        public void Dispose()
        {
            _database.Dispose();
        }
}
```

That feels like the best approach with the way our project is organized

**Comment by asherber** [comment]
That's the right idea, but do check out the docs for properly implementing the [Dispose pattern](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern).

**Comment by Jeremy-Code-F** [comment]
Will do appreciate you looking!
