### ISSUE TITLE
Help petapoco with Excute Sql

### ISSUE THREAD

**Issue by java1001** [CollaboratingPlatypus/PetaPoco#78]
I connect to SQL Server by code : 

var db = new PetaPoco.Database("conenctstring");

It is success . But when I implement query  Execute , it not execute  sucess . This is my  code :

var db = new PetaPoco.Database("conenctstring");
db.OpenSharedConnection();
int query = db.Execute("SELECT * FROM level");
db.CloseSharedConnection();

Result of query : -1 

Would you help me with error ? Thank you!

**Comment by pleb** [comment]
Closing issue - as per @schotime
