### ISSUE TITLE
Null String

### ISSUE THREAD

**Issue by paganaye** [CollaboratingPlatypus/PetaPoco#80]
When you have a database with a non null string column, it doesn't really map to the poco strings very well.
A new class will not insert in the database until you manually set all the non-nullable string to empty string.
The issue is that there are no non-nullable string in C#.

I believe PetaPoco could be forgiving on this still; If the string has its default value (null) then the column should have its default value (empty string).

I wonder what you think of that.

---- ---- ---- ---- ---- ---- ---- ---- ---- ---- 

I have butchered your code, to check if it was doable and it seems to behave
(I don't know how to use github).

Here are the changes I made so far. 

PetaPoco.Generator.ttInclude

    <# if (col.Name!=col.PropertyName) { #>
            [Column("<#=col.Name#>"<# 
    	if (col.PropertyType == "string" && !col.IsNullable) #>, NotNull = true<#
    		#>)]     	
    <# } else { #>
            [Column<# 
    	if (col.PropertyType == "string" && !col.IsNullable) #>(NotNull = true)<#
    		#>] 
    <# } #>

PetaPoco.cs
Class ColumnAttribute

    	[AttributeUsage(AttributeTargets.Property)]
    	public class ColumnAttribute : Attribute
    	{
    		public ColumnAttribute() { }
    		public ColumnAttribute(string name) { Name = name; }
    		public string Name { get; set; }
    		public bool NotNull { get; set; } // this is a new line
    	}

Class PocoColumn

    		public class PocoColumn
    		{
    			public string ColumnName;
    			public PropertyInfo PropertyInfo;
    			public bool ResultColumn;
    			public virtual void SetValue(object target, object val) { PropertyInfo.SetValue(target, val, null); }
    			public virtual object GetValue(object target) { return PropertyInfo.GetValue(target, null); }
    			public virtual object ChangeType(object val) { return Convert.ChangeType(val, PropertyInfo.PropertyType); }
    			public bool NotNull { get; set; } // this is a new line
    		}
When we build the actual command

                                // PG : AddParam(cmd, i.Value.GetValue(poco), _paramPrefix);
                                var val = i.Value.GetValue(poco);
                                if (val == null)
                                {
                                    if (i.Value.NotNull && i.Value.PropertyInfo.PropertyType == typeof(string)) val = string.Empty;
                                }
                                AddParam(cmd, val, _paramPrefix);

When we create the columns

    					if (ColAttrs.Length > 0)
    					{
    						var colattr = (ColumnAttribute)ColAttrs[0];
    						pc.ColumnName = colattr.Name;
    						pc.NotNull = colattr.NotNull; // this is a new line
    						if ((colattr as ResultColumnAttribute) != null)
    							pc.ResultColumn = true;
    					}

**Comment by pleb** [comment]
Hi there. Sorry it's been so long in getting back to you about this issue. Where you say 

_If the string has its default value (null) then the column should have its default value (empty string)_

I don't agree. If the default value is null, then null it is. Now because there's no difference with setting a nullable/not nullable string column to String.Empty, you could enforce this yourself. 

As I don't believe a change is required for PP. I'm closing this issue.
