### ISSUE TITLE
IsNew fails on GUIDs

### ISSUE THREAD

**Issue by paganaye** [CollaboratingPlatypus/PetaPoco#81]
Is new return false when the primary columns is of type GUID
I am not really sure why Guid don't overload the operator == but it appears they don't.
Object.Equals seems to work though.

		public bool IsNew(string primaryKeyName, object poco)
		{
		...
				// Create a default instance and compare
				// return pk == Activator.CreateInstance(pk.GetType());
				// Changed by PG
				return Activator.CreateInstance(pk.GetType()).Equals(pk);
			 }
			else
			{
				return pk == null;
			}
		}

**Comment by pleb** [comment]
Based on the code, this has already been addressed. However, I've added unit tests and expanded the feature.
