### ISSUE TITLE
Page in MS-SQL and Aggregate throws exception

### ISSUE THREAD

**Issue by StephenPAdams** [CollaboratingPlatypus/PetaPoco#82]
Hey!

Love PetaPoco, but receiving this exception:
Exception Details: System.Data.SqlClient.SqlException: Invalid column name 'TotalVotesByDate'.

When using a SELECT COUNT(id) aggregate with an ORDER BY of that aggregate name. For example:

DataContext.Page<ShowcaseSummary>(1, maxShowcases,
                                                         @"SELECT ssv.*, (SELECT COUNT(sv.ShowcaseVoteId)
			                                                                   FROM ShowcaseVote AS sv
			                                                                   WHERE sv.ShowcaseId = ssv.ShowcaseId
                                                                                     AND CAST(sv.DateCreated AS Date) = CAST(@0 AS Date)) AS TotalVotesByDate
                                                           FROM ShowcaseSummaryView AS ssv
                                                           WHERE ssv.LanguageId = @1
                                                           ORDER BY TotalVotesByDate DESC",
                                                         cutoffDate, languageId).Items;

This statement works perfectly fine in SQL Server Management Studio, however, when running via the Page command, it fails.

**Comment by pleb** [comment]
Closing this as it's very old. If this is still an issue, please feel free open another issue for it.
