### ISSUE TITLE
Use class Linq to Petapoco

### ISSUE THREAD

**Issue by java1001** [CollaboratingPlatypus/PetaPoco#83]
My project use Linq + SQl  but I want use class in LinQ for Petapoco .

I have trouble when update . This my code : 

                    db.Insert("Posts", "ID", Post);
                  
Error :
No mapping exists from object type System.Data.Linq.EntitySet`1[[Data.PostFavo, Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] to a known managed provider native type.

Can you help me about this error ? Thank you!

**Comment by pleb** [comment]
Thanks for the report. I'm closing this because it's very old. If it's still an issue, please feel free to open another issue
