### ISSUE TITLE
Provide a DLL version of the NuGet package

### ISSUE THREAD

**Issue by gimmi** [CollaboratingPlatypus/PetaPoco#87]
I know that all MicroORMs out ther are included as source file into the needed project, but many people (like me) prefer to include external libraries using the classic way of referencing DLLs. 

Would be nice if you provide this option via a dedicated NuGet package, maybe only the PetaPoco.Core version.

What do you think?

**Comment by pleb** [comment]
Bump!

**Comment by pleb** [comment]
Hey everyone. This has been actioned. https://www.nuget.org/packages/PetaPoco.Core.Compiled/
