### ISSUE TITLE
SCOPE_IDENTITY fails

### ISSUE THREAD

**Issue by lukebakken** [CollaboratingPlatypus/PetaPoco#89]
Hello,

Currently when using UNIQUEIDENTIFIER pks on SQL Server using SCOPE_IDENTITY () fails to retrieve the new ID value. Changing to use "OUTPUT" would fix this. Pull request on its way.

**Comment by pleb** [comment]
I'm sorry that your issue has been left for so long. In an effort to reboot PetaPoco your issue has been closed. If you think this is still a problem. Please feel free to open and another issue. Please pass the word on that PetaPoco is back. We're looking for people #204.
