### ISSUE TITLE
Helper method "Count<T>()" easily added

### ISSUE THREAD

**Issue by genez** [CollaboratingPlatypus/PetaPoco#99]
I think it would be easy to implement a Count<T>() method and it would be helpful - here is my code, tested and working

        public int Count<T>(string sql, params object[] args)
        {
            if (EnableAutoSelect)
                sql = AddSelectClause<T>(sql);

            // Split the SQL into the bits we need
            string sqlSelectRemoved, sqlOrderBy, sqlCount;
            if (!SplitSqlForPaging(sql, out sqlCount, out sqlSelectRemoved, out sqlOrderBy))
                throw new Exception("Unable to parse SQL statement for count query");

            OpenSharedConnection();
            try
            {
                using (var cmd = CreateCommand(_sharedConnection, sqlCount, args))
                {
                    int count = 0;

                    try
                    {
                        count = (int)cmd.ExecuteScalar();
                        OnExecutedCommand(cmd);
                    }
                    catch (Exception x)
                    {
                        OnException(x);
                        throw;
                    }

                    return count;
                }
            }
            finally
            {
                CloseSharedConnection();
            }
        }

        public int Count<T>(PetaPoco.Sql sql)
        {
            return Count<T>(sql.SQL, sql.Arguments);
        }

**Comment by pleb** [comment]
Thanks for the suggestion. If you'd like to see this is PetaPoco, please send a PR. Read more about contributing here https://guides.github.com/activities/contributing-to-open-source/
